"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

// Define available languages
export type Language = "en" | "tr" | "el" | "bg"

// Define language context type
type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

// Create context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "tr", // Default to Turkish
  setLanguage: () => {},
  t: (key) => key,
})

// Define translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    "app.name": "La Strada Restaurant",
    "app.hotel": "The Plaza Hotel Edirne",
    "app.selectLanguage": "Select Language",
    "app.search": "Search",
    "app.cart": "Cart",
    "app.menu": "Menu",
    "app.order": "Order",
    "app.processOrder": "Process Order",
    "app.orderSummary": "Order Summary",
    "app.subtotal": "Subtotal",
    "app.total": "Total",
    "app.tax": "Tax",
    "app.roomNumber": "Room Number",
    "app.tableNumber": "Table Number",
    "app.enterRoomOrTable": "Enter Room or Table Number",
    "app.notes": "Notes",
    "app.addNotes": "Add Notes",
    "app.back": "Back",
    "app.continue": "Continue",
    "app.orderConfirmation": "Order Confirmation",
    "app.orderSent": "Your order has been sent!",
    "app.orderNumber": "Order Number",
    "app.orderTime": "Order Time",
    "app.orderTotal": "Order Total",
    "app.newOrder": "New Order",
    "app.emptyCart": "Your cart is empty",
    "app.addItems": "Add Items",
    "app.add": "Add",
    "app.select": "Select",
    "app.addToCart": "Add to Cart",
    "app.details": "Details",
    "app.allergens": "Allergens",
    "app.reviews": "Reviews",
    "app.options": "Options",
    "app.portion": "Portion",
    "app.allergenInfo": "Allergen Information",
    "app.containsAllergens": "This product contains the following allergens",
    "app.allergenWarning": "If you have allergies, please inform the staff before ordering",
    "app.customerReviews": "Customer Reviews",
    "app.bestSeller": "Best Seller",

    // Categories
    "category.all": "All Menu",
    "category.breakfast": "Breakfast",
    "category.starters": "Starters & Appetizers",
    "category.salads": "Salads",
    "category.mainDishes": "Main Dishes",
    "category.pasta": "Pasta",
    "category.burgers": "Burgers",
    "category.desserts": "Desserts",
    "category.drinks": "Drinks",
    "category.spirits": "Spirits",
    "category.cocktails": "Cocktails",
    "category.beers": "Beers",
    "category.wines": "Wines",
    "category.extras": "Extras",

    // Allergens
    "allergen.contains": "Contains",
    "allergen.gluten": "Gluten",
    "allergen.dairy": "Dairy",
    "allergen.nuts": "Nuts",
    "allergen.eggs": "Eggs",
    "allergen.fish": "Fish",
    "allergen.shellfish": "Shellfish",
    "allergen.soy": "Soy",
    "allergen.wheat": "Wheat",
    "allergen.alcohol": "Alcohol",

    // Wine
    "wine.pairing": "Pairing",
    "wine.pairsWellWith": "This wine pairs well with",
    "wine.foodPairings": "Food Pairings",

    // Items - Breakfast (Machine Translated)
    "item.breakfast.continental-kahvalti.name": "Continental Breakfast",
    "item.breakfast.continental-kahvalti.description": "Edirne white cheese, plain omelette, cheddar, tomato, cucumber, pepper, olives, etc..",
    "item.breakfast.serpme-kahvalti.name": "Spread Breakfast",
    "item.breakfast.serpme-kahvalti.description": "In addition to continental breakfast: pancake, sausage, salami, cookie, bagel, etc..",
    "item.breakfast.pankek-pastasi.name": "Pancake Stack",
    "item.breakfast.pankek-pastasi.description": "3 pancakes and seasonal fruits",
    "item.breakfast.acik-bufe-kahvalti.name": "Open Buffet Breakfast",
    "item.breakfast.acik-bufe-kahvalti.description": "Between 07:30 - 10:30",
    "item.breakfast.omlet.name": "Omelette",
    "item.breakfast.omlet.description": "Plain, with cheese, vegetables, cheddar, sucuk, sausage, roasted meat",
    "item.breakfast.sahanda-goz-yumurta.name": "Fried Eggs (Sunny Side Up)",
    "item.breakfast.sahanda-goz-yumurta.description": "Freshly cooked fried eggs",
    "item.breakfast.menemen.name": "Menemen",
    "item.breakfast.menemen.description": "Menemen mix prepared with village peppers and summer tomatoes, with 2 eggs..",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.name": "Sourdough Double Cheese Toast",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.description": "Sourdough square toast bread, Thracian fresh cheddar, served with homemade tomato paste, mixed olives, tomato, cucumber",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.name": "Sourdough Toast with Cheese and Sucuk",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.description": "Sourdough square toast bread, Thracian fresh cheddar, beef sucuk, served with homemade tomato paste, mixed olives, tomato, cucumber",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.name": "Sourdough 3 Cheese Toast",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.description": "Sourdough square toast bread, Thracian fresh cheddar, Edirne white cheese, and Thracian aged kashkaval, served with homemade tomato paste, mixed olives, tomato, cucumber",
    "item.breakfast.akitma.name": "Akıtma (Thracian Style Crepe)",
    "item.breakfast.akitma.description": "Thracian style crepe, served with Edirne white cheese, organic blackberry jam, tomato, cucumber, and olives",
    "item.breakfast.cicipapa.name": "Cicipapa (French Toast)",
    "item.breakfast.cicipapa.description": "4 slices of French toast, Edirne white cheese and fresh cheddar, homemade walnut acuka sauce, tomato, cucumber, green pepper",

    // Items - Starters (Machine Translated)
    "item.starters.trakya-koy-tarhanasi.name": "Thracian Village Tarhana Soup",
    "item.starters.trakya-koy-tarhanasi.description": "Prepared with natural ingredients, a heartwarming flavor. Leaves an unforgettable taste with Edirne white cheese and toasted village bread.",
    "item.starters.zeytinyagli-aysekadin-fasulye.name": "Green Beans in Olive Oil",
    "item.starters.zeytinyagli-aysekadin-fasulye.description": "A light and healthy Aegean flavor decorated with lemon and dill.",
    "item.starters.caciki.name": "Caciki (Tzatziki)",
    "item.starters.caciki.description": "The perfect harmony of yogurt, cucumber, garlic - olive oil prepared Greek style. Adds flavor to your table as a refreshing and light appetizer.",
    "item.starters.caciki.review0.comment": "Amazing caciki! Garlic ratio is just right, very refreshing.",
    "item.starters.caciki.review1.comment": "Made Greek style, really delicious.",
    "item.starters.caciki.review2.comment": "Very fresh and tasty, goes great with bread.",
    "item.starters.saksuka.name": "Şakşuka",
    "item.starters.saksuka.description": "The unique harmony of fried eggplant, pepper, and tomato sauce. This mildly spicy and flavorful Mediterranean appetizer will add color to your table.",
    "item.starters.trakya-mamzana.name": "Thracian Mamzana",
    "item.starters.trakya-mamzana.description": "This unique flavor, created by combining roasted eggplant, pepper, and onion with garlic yogurt, brings the authentic taste of Thrace to your table.",
    "item.starters.atom-haydari.name": "Atom Haydari",
    "item.starters.atom-haydari.description": "This delicious appetizer, prepared with crispy Edirne peppers on garlic yogurt, appeals to both the eyes and the palate.",
    "item.starters.guvecte-manda-yogurdu.name": "Buffalo Yogurt in Clay Pot",
    "item.starters.guvecte-manda-yogurdu.description": "Natural and delicious buffalo yogurt fermented in clay pots. Adds a unique taste to your table with its thick consistency and rich aroma.",
    "item.starters.karpuz-peynir.name": "Watermelon and Cheese",
    "item.starters.karpuz-peynir.description": "Refreshing watermelon slices meet fresh white cheese. This classic duo, indispensable in summer, is a refreshing and flavorful snack.",
    "item.starters.soka-kaymakli-biber-tursusu.name": "Soka Pickled Peppers with Cream",
    "item.starters.soka-kaymakli-biber-tursusu.description": "The famous pickled peppers with cheese and cream from Thrace and the Balkans. Adds a refreshing touch to your table with its unique flavor.",
    "item.starters.soka-kaymakli-biber-tursusu.review0.comment": "I didn't think I could find the Balkan flavor in Istanbul. Amazing taste!",
    "item.starters.soka-kaymakli-biber-tursusu.review1.comment": "Perfect for those missing Edirne, the harmony of cream and pickle is magnificent.",
    "item.starters.tereyagli-kasarli-mantar.name": "Mushrooms with Butter and Cheese",
    "item.starters.tereyagli-kasarli-mantar.description": "Cultivated, oyster, and sarıkız mushrooms cooked in their own juice, with gratin Thracian fresh cheddar on top.",
    "item.starters.tereyagli-soganli-yaprak-ciger.name": "Leaf Liver with Butter and Onion",
    "item.starters.tereyagli-soganli-yaprak-ciger.description": "Veal leaf liver sautéed with onion and butter. A traditional flavor with its soft texture and rich aroma.",
    "item.starters.pacanga-boregi.name": "Paçanga Börek",
    "item.starters.pacanga-boregi.description": "Prepared with pastrami, fresh cheddar, tomato, and pepper. A hot and flavorful start with the harmony of its ingredients and crispy exterior.",
    "item.starters.pacanga-boregi.review0.comment": "A great snack with its crispy exterior and delicious interior.",
    "item.starters.pacanga-boregi.review1.comment": "The harmony of pastrami and cheese is perfect, I will order again.",
    "item.starters.patates-kizartmasi.name": "French Fries",
    "item.starters.patates-kizartmasi.description": "Golden and crispy french fries, with optional cheese. A classic flavor enjoyable in every bite.",
    "item.starters.ev-yapimi-patates-kizartmasi.name": "Homemade French Fries",
    "item.starters.ev-yapimi-patates-kizartmasi.description": "Crispy homemade french fries, with optional cheese. A warm and satisfying flavor.",
    "item.starters.kizartma-sepeti.name": "Fried Platter",
    "item.starters.kizartma-sepeti.description": "A flavorful variety consisting of french fries, halloumi, onion rings, sausage, chicken fingers, and cheeseburger börek.",
    "item.starters.sarkuteri-tahtasi.name": "Charcuterie Board",
    "item.starters.sarkuteri-tahtasi.description": "This exquisite charcuterie board, prepared with local meats, cheeses, and fruits, offers a different taste experience in every bite.",

    // Items - Salads (EN Corrected)
    "item.salads.bruschetta.name": "Bruschetta",
    "item.salads.bruschetta.description": "is prepared with garlic-toasted bread slices topped with tomatoes in pesto sauce, cheese, and basil. A light and refreshing Italian classic.",
    "item.salads.yesil-salata.name": "Green Salad",
    "item.salads.yesil-salata.description": "is a mix of Mediterranean greens served with a mustard olive oil dressing. This fresh and light salad is ideal for those seeking a healthy option.",
    "item.salads.peynirli-yesil-salata.name": "Cheese Green Salad",
    "item.salads.peynirli-yesil-salata.description": "is served with cheese, a mix of Mediterranean greens, and mustard olive oil dressing. This healthy, and flavorful salad will delight your palate.",
    "item.salads.roka-salata.name": "Rocket Salad",
    "item.salads.roka-salata.description": "is prepared with rocket, sun-dried tomatoes, balsamic dressing, and grated Trakya aged kashar cheese.",
    "item.salads.shopska-salata.name": "Shopska Salata",
    "item.salads.shopska-salata.description": "is prepared with tomatoes, onions, cucumbers, peppers, parsley, olives, and grated white cheese. Served with toasted sourdough bread.",
    "item.salads.shopska-salata.review0.comment": "A fantastic salad that truly reflects the Balkan flavor.",
    "item.salads.shopska-salata.review1.comment": "The harmony of fresh vegetables and white cheese is magnificent, I always order it.",
    "item.salads.istanbul-salata.name": "Istanbul Salad",
    "item.salads.istanbul-salata.description": "is prepared with tomatoes, red onions, fresh thyme, and croutons. Crowned with a balsamic tomato dressing.",
    "item.salads.sezar-salata.name": "Caesar Salad",
    "item.salads.sezar-salata.description": "is prepared with crispy iceberg lettuce and marinated chicken, Caesar dressing, garlic croutons, and Parmesan cheese.",
    "item.salads.ananas-ve-buzlu-badem-salatasi.name": "Pineapple and Iced Almond Salad",
    "item.salads.ananas-ve-buzlu-badem-salatasi.description": "is a fresh mix of Mediterranean greens, pineapple slices, almonds, and balsamic dressing, offering a tropical flavour.",

    // Main Dishes
    "item.mainDishes.edirne-koftesi.name": "Edirne Meatballs",
    "item.mainDishes.edirne-koftesi.description": "Regionally famous Edirne meatballs, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.name": "Keşan Butcher's Meatballs",
    "item.mainDishes.kesan-satir-kofte.description": "Special butcher's meatballs made with the traditional Keşan cleaver technique, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.review0.comment": "The cleaver technique really makes a difference, delicious!",
    "item.mainDishes.kesan-satir-kofte.review1.comment": "Best meatballs I've had in Edirne.",
    "item.mainDishes.bosnak-kofte.name": "Bosnian Meatballs",
    "item.mainDishes.bosnak-kofte.description": "Traditional Bosnian meatballs (pljeskavica) served with pita bread, ajvar, onions, and potatoes.",
    "item.mainDishes.bosnak-kofte.review0.comment": "Authentic Balkan taste, just like homemade.",
    "item.mainDishes.bosnak-kofte.review1.comment": "Very generous portion and great flavor.",
    "item.mainDishes.izgara-kasap-sucugu.name": "Grilled Butcher's Sausage",
    "item.mainDishes.izgara-kasap-sucugu.description": "Flavorful grilled butcher's sausage, served with roasted peppers, onions, and rice.",
    "item.mainDishes.izgara-tavuk-sis.name": "Grilled Chicken Skewers",
    "item.mainDishes.izgara-tavuk-sis.description": "Tender grilled chicken skewers, served with roasted peppers, onions, and rice.",
    "item.mainDishes.pilic-kulbasti.name": "Chicken Külbastı",
    "item.mainDishes.pilic-kulbasti.description": "Grilled chicken fillet marinated in yogurt and spices, served with roasted peppers, onions, and rice.",
    "item.mainDishes.tavuk-schnitzel.name": "Chicken Schnitzel",
    "item.mainDishes.tavuk-schnitzel.description": "Breaded and fried chicken cutlet, served with french fries and lemon.",
    "item.mainDishes.tereyagli-dana-bonfile.name": "Butter Beef Tenderloin",
    "item.mainDishes.tereyagli-dana-bonfile.description": "Juicy beef tenderloin cooked in butter, served with grilled vegetables.",
    "item.mainDishes.antrikot-sis.name": "Ribeye Skewers",
    "item.mainDishes.antrikot-sis.description": "Marinated ribeye skewers, grilled to perfection, served with roasted peppers, onions, and rice.",
    "item.mainDishes.antrikot-sis.review0.comment": "The meat was incredibly tender and flavorful.",
    "item.mainDishes.antrikot-sis.review1.comment": "A must-try for meat lovers!",
    "item.mainDishes.coban-kavurma.name": "Shepherd's Sauté",
    "item.mainDishes.coban-kavurma.description": "Diced beef sautéed with onions, tomatoes, and peppers, served with rice.",
    "item.mainDishes.kuzu-tandir.name": "Lamb Tandoori",
    "item.mainDishes.kuzu-tandir.description": "Slow-cooked lamb tandoori, tender and flavorful, served with rice and grilled vegetables.",

    // Pasta
    "item.pasta.peynirli-edirne-koy-eristesi.name": "Edirne Noodles",
    "item.pasta.peynirli-edirne-koy-eristesi.description": "are cooked in a sauce of butter, mint, red pepper flakes, and parsley, then crowned with crumbled cheese and walnuts.",
    "item.pasta.peynirli-edirne-koy-eristesi.review0.comment": "Edirne's famous noodles, the combination of butter and cheese is perfect.",
    "item.pasta.peynirli-edirne-koy-eristesi.review1.comment": "Tastes like homemade noodles, the walnut and cheese combination is great.",
    "item.pasta.kiyma-el-acmasi-makarna.name": "Homemade Minced Meat Pasta",
    "item.pasta.kiyma-el-acmasi-makarna.description": "is a delicious dish made with roasted ground beef and fresh homemade pasta. It adds a warm, homemade touch to your table.",
    "item.pasta.penne-alfredo.name": "Penne Alfredo",
    "item.pasta.penne-alfredo.description": "brings together penne pasta with Alfredo sauce made from chicken, cream, mushrooms, Parmesan, and pesto sauce.",
    "item.pasta.penne-napoliten.name": "Penne Napoliten",
    "item.pasta.penne-napoliten.description": "combines penne pasta with a basil and garlic tomato sauce made from summer tomatoes, topped with Thrace aged kashar cheese.",

    // Burgers
    "item.burgers.la-strada-burger.name": "La Strada Burger",
    "item.burgers.la-strada-burger.description": "is made of ground beef ribs, cheddar cheese, iceberg lettuce, pickles, tomatoes, and crispy onion pieces. This unique burger offers a rich and satisfying flavour with every bite.",
    "item.burgers.la-strada-crispy-burger.name": "La Strada Crispy Burger",
    "item.burgers.la-strada-crispy-burger.description": "has crispy chicken thighs, pickles, pickled red onions, and tomatoes. This delicious burger offers a crispy and fresh flavour experience with every bite.",
    "item.burgers.balkan-burger.name": "Balkan Burger",
    "item.burgers.balkan-burger.description": "brings the flavours of the Balkans to your table with roasted red pepper sauce, tomatoes, red onions, crispy pastrami slices, and ground beef ribs. This unique burger offers a rich and satisfying taste experience.",
    "item.burgers.balkan-burger.review0.comment": "A magnificent flavor with pastrami and roasted pepper sauce.",
    "item.burgers.balkan-burger.review1.comment": "A great idea combining Balkan flavors with a burger, very tasty.",

    // Desserts
    "item.desserts.cup-dondurma.name": "Cup Dondurma",
    "item.desserts.cup-dondurma.description": "is a delightful ice cream extravaganza with wafer and fresh fruits! This delicious ice cream offers a refreshing and sweet treat.",
    "item.desserts.trilece.name": "Trileçe",
    "item.desserts.trilece.description": "is the famous caramel three-milk cake from the Balkans. With its soft texture and rich milk aroma, it offers a sweet explosion of flavor with every bite.",
    "item.desserts.karamelli-affogato.name": "Caramel Affogato",
    "item.desserts.karamelli-affogato.description": "is a magnificent dessert with a cake base, ice cream, espresso, chocolate chips, walnuts, and caramel sauce.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.name": "Baked Edirne Cheese Halva",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.description": "is prepared with a traditional recipe and served with an option of ice cream. Each bite offers a unique flavour.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review0.comment": "It's great to find Edirne's famous cheese halva here, perfectly cooked.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review1.comment": "Serving it with ice cream is a great idea, perfect harmony.",
    "item.desserts.brownie.name": "Brownie",
    "item.desserts.brownie.description": "is served intensely chocolatey with an option of ice cream. Enjoy a chocolate extravaganza with every bite, featuring a warm and soft texture.",
    "item.desserts.fistikli-havuc-dilim-baklava.name": "Baklava with Pistachio",
    "item.desserts.fistikli-havuc-dilim-baklava.description": "will delight your palate with its crispy texture and intense pistachio flavour in every bite.",

    // Drinks
    // Coffee
    "item.drinks.turk-kahvesi.name": "Turkish Coffee",
    "item.drinks.turk-kahvesi.description": "Traditional Turkish coffee, served plain, medium, or sweet upon request.",
    "item.drinks.espresso.name": "Espresso",
    "item.drinks.espresso.description": "Intense Italian espresso.",
    "item.drinks.double-espresso.name": "Double Espresso",
    "item.drinks.double-espresso.description": "Double shot of espresso.",
    "item.drinks.americano.name": "Americano",
    "item.drinks.americano.description": "Prepared with espresso and hot water.",
    "item.drinks.latte.name": "Latte",
    "item.drinks.latte.description": "Prepared with espresso and steamed milk.",
    "item.drinks.cappuccino.name": "Cappuccino",
    "item.drinks.cappuccino.description": "Prepared with espresso, steamed milk, and milk foam.",
    "item.drinks.sicak-cikolata.name": "Hot Chocolate",
    "item.drinks.sicak-cikolata.description": "Hot beverage with intense chocolate flavor.",
    "item.drinks.salep.name": "Salep",
    "item.drinks.salep.description": "Traditional Turkish drink, served with cinnamon.",
    "item.drinks.filter-coffee.name": "Filter Coffee",
    "item.drinks.filter-coffee.description": "Prepared from daily ground coffee beans.",
    "item.drinks.sade-kahve.name": "Black Coffee",
    "item.drinks.sade-kahve.description": "Turkish style black coffee.",
    "item.drinks.sutlu-kahve.name": "Coffee with Milk",
    "item.drinks.sutlu-kahve.description": "Turkish style coffee with milk.",
    "item.drinks.soguk-kahve.name": "Cold Brew",
    "item.drinks.soguk-kahve.description": "Iced cold coffee.",
    "item.drinks.frappe.name": "Frappe",
    "item.drinks.frappe.description": "Greek style foamy cold coffee.",
    // Soft Drinks
    "item.drinks.cay.name": "Tea",
    "item.drinks.cay.description": "Traditional Turkish tea.",
    "item.drinks.bitki-cayi.name": "Herbal Tea",
    "item.drinks.bitki-cayi.description": "Various herbal teas (Linden, Sage, Chamomile, Green Tea).",
    "item.drinks.su-small.name": "Water (Small)",
    "item.drinks.su-small.description": "Natural spring water.",
    "item.drinks.su-large.name": "Water (Large)",
    "item.drinks.su-large.description": "Natural spring water.",
    "item.drinks.san-pellegrino.name": "San Pellegrino",
    "item.drinks.san-pellegrino.description": "Italian mineral water.",
    "item.drinks.soda.name": "Mineral Water",
    "item.drinks.soda.description": "Plain or lemon mineral water.",
    "item.drinks.kola.name": "Coke",
    "item.drinks.kola.description": "Coca-Cola, Diet Coke, Coca-Cola Zero.",
    "item.drinks.ayran.name": "Ayran",
    "item.drinks.ayran.description": "Traditional Turkish yogurt drink.",
    "item.drinks.meyve-suyu.name": "Juice",
    "item.drinks.meyve-suyu.description": "Orange, cherry, peach, apricot, pineapple.",
    "item.drinks.limonata.name": "Lemonade",
    "item.drinks.limonata.description": "Homemade fresh lemonade.",
    "item.drinks.tonic.name": "Tonic",
    "item.drinks.tonic.description": "Schweppes Tonic Water.",
    "item.drinks.red-bull.name": "Red Bull",
    "item.drinks.red-bull.description": "Energy drink.",
    // Fresh Juices
    "item.drinks.portakal-suyu.name": "Orange Juice",
    "item.drinks.portakal-suyu.description": "Freshly squeezed orange juice.",
    "item.drinks.nar-suyu.name": "Pomegranate Juice",
    "item.drinks.nar-suyu.description": "Freshly squeezed pomegranate juice.",
    "item.drinks.elma-havuc-bal.name": "Apple Carrot Honey",
    "item.drinks.elma-havuc-bal.description": "Freshly squeezed apple and carrot juice, sweetened with honey.",
  },
  tr: {
    // Common
    "app.name": "La Strada Restaurant",
    "app.hotel": "The Plaza Hotel Edirne",
    "app.selectLanguage": "Dil Seçin",
    "app.search": "Ara",
    "app.cart": "Sepet",
    "app.menu": "Menü",
    "app.order": "Sipariş",
    "app.processOrder": "Siparişi Tamamla",
    "app.orderSummary": "Sipariş Özeti",
    "app.subtotal": "Ara Toplam",
    "app.total": "Toplam",
    "app.tax": "Vergi",
    "app.roomNumber": "Oda Numarası",
    "app.tableNumber": "Masa Numarası",
    "app.enterRoomOrTable": "Oda veya Masa Numarası Girin",
    "app.notes": "Notlar",
    "app.addNotes": "Not Ekle",
    "app.back": "Geri",
    "app.continue": "Devam",
    "app.orderConfirmation": "Sipariş Onayı",
    "app.orderSent": "Siparişiniz gönderildi!",
    "app.orderNumber": "Sipariş Numarası",
    "app.orderTime": "Sipariş Zamanı",
    "app.orderTotal": "Sipariş Toplamı",
    "app.newOrder": "Yeni Sipariş",
    "app.emptyCart": "Sepetiniz boş",
    "app.addItems": "Ürün Ekle",
    "app.add": "Ekle",
    "app.select": "Seç",
    "app.addToCart": "Sepete Ekle",
    "app.details": "Detaylar",
    "app.allergens": "Alerjenler",
    "app.reviews": "Yorumlar",
    "app.options": "Seçenekler",
    "app.portion": "Porsiyon",
    "app.allergenInfo": "Alerjen Bilgisi",
    "app.containsAllergens": "Bu üründe aşağıdaki alerjenler bulunmaktadır",
    "app.allergenWarning": "Alerjiniz varsa lütfen sipariş vermeden önce personele bildiriniz",
    "app.customerReviews": "Müşteri Yorumları",
    "app.bestSeller": "En Çok Satan",

    // Categories
    "category.all": "Tüm Menü",
    "category.breakfast": "Kahvaltı",
    "category.starters": "Başlangıçlar ve Mezeler",
    "category.salads": "Salatalar",
    "category.mainDishes": "Ana Yemekler",
    "category.pasta": "Makarnalar",
    "category.burgers": "Hamburgerler",
    "category.desserts": "Tatlılar",
    "category.drinks": "İçecekler",
    "category.spirits": "Yüksek Alkollü İçecekler",
    "category.cocktails": "Kokteyller",
    "category.beers": "Biralar",
    "category.wines": "Şaraplar",
    "category.extras": "Ekstralar",

    // Allergens
    "allergen.contains": "İçerir",
    "allergen.gluten": "Gluten",
    "allergen.dairy": "Süt Ürünleri",
    "allergen.nuts": "Kuruyemiş",
    "allergen.eggs": "Yumurta",
    "allergen.fish": "Balık",
    "allergen.shellfish": "Kabuklu Deniz Ürünleri",
    "allergen.soy": "Soya",
    "allergen.wheat": "Buğday",
    "allergen.alcohol": "Alkol",

    // Wine
    "wine.pairing": "Eşleşme",
    "wine.pairsWellWith": "Bu şarap şu yemeklerle iyi eşleşir",
    "wine.foodPairings": "Yemek Eşleşmeleri",

    // Items - Breakfast
    "item.breakfast.continental-kahvalti.name": "Continental Kahvaltı",
    "item.breakfast.continental-kahvalti.description": "Edirne beyaz peyniri, sade omlet, kaşar, domates, salatalık, biber, zeytin, vs..",
    "item.breakfast.serpme-kahvalti.name": "Serpme Kahvaltı",
    "item.breakfast.serpme-kahvalti.description": "Continental kahvaltıya ek olarak pankek, sosis, salam, kurabiye, simit, vs..",
    "item.breakfast.pankek-pastasi.name": "Pankek Pastası",
    "item.breakfast.pankek-pastasi.description": "3 adet pankek ve mevsim meyveleri",
    "item.breakfast.acik-bufe-kahvalti.name": "Açık Büfe Kahvaltı",
    "item.breakfast.acik-bufe-kahvalti.description": "07:30 - 10:30 saatleri arası",
    "item.breakfast.omlet.name": "Omlet",
    "item.breakfast.omlet.description": "Sade, peynirli, sebzeli, kaşarlı, sucuklu, sosisli, kavurmalı",
    "item.breakfast.sahanda-goz-yumurta.name": "Sahanda Göz Yumurta",
    "item.breakfast.sahanda-goz-yumurta.description": "Taze pişirilmiş göz yumurta",
    "item.breakfast.menemen.name": "Menemen",
    "item.breakfast.menemen.description": "Köy biberi ve yaz domatesiyle hazırlanmış menemen harcı, 2 yumurta ile..",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.name": "Ekşi Mayalı Ekmeğe Çift Kaşarlı Tost",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.description": "Ekşi mayalı kare tost ekmeği, trakya taze kaşarı ve yanında ev salçası, karışık zeytin, domates salatalık ile",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.name": "Ekşi Mayalı Ekmeğe Kaşarlı Sucuklu Tost",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.description": "Ekşi mayalı kare tost ekmeği, trakya taze kaşarı, dana sucuğu ve yanında ev salçası, karışık zeytin, domates salatalık ile",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.name": "Ekşi Mayalı Ekmeğe 3 Peynirli Tost",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.description": "Ekşi mayalı kare tost ekmeği, trakya taze kaşarı, edirne beyaz peyniri ve trakya eski kaşarı yanında ev salçası, karışık zeytin, domates salatalık ile",
    "item.breakfast.akitma.name": "Akıtma (Trakya Usulü Krep)",
    "item.breakfast.akitma.description": "Trakya usulü krep, yanında edirne beyaz peyniri, organik böğürtlen reçeli, domates salatalık ve zeytin ile",
    "item.breakfast.cicipapa.name": "Cicipapa",
    "item.breakfast.cicipapa.description": "4 dilim yumurtalı ekmek, edirne beyaz peynir ve taze kaşarı, ev yapımı cevizli acuka sos, domates, salatalık sivri biber",

    // Items - Starters
    "item.starters.trakya-koy-tarhanasi.name": "Trakya Köy Tarhanası",
    "item.starters.trakya-koy-tarhanasi.description": "Doğal malzemelerle hazırlanmış, iç ısıtan bir lezzet. Edirne beyaz peyniri ve kızarmış köy ekmeği ile damaklarda unutulmaz bir tat bırakır.",
    "item.starters.zeytinyagli-aysekadin-fasulye.name": "Zeytinyağlı Ayşekadın Fasulye",
    "item.starters.zeytinyagli-aysekadin-fasulye.description": "Limon ve dereotu ile süslenen hafif ve sağlıklı bir Ege lezzeti.",
    "item.starters.caciki.name": "Caciki",
    "item.starters.caciki.description": "Yunan usulü olarak hazırlanan yoğurt, salatalık, sarımsak - zeytinyağının mükemmel uyumu. Ferahlatıcı ve hafif bir meze olarak sofranıza lezzet katacak.",
    "item.starters.caciki.review0.comment": "Harika bir cacıki! Sarımsak oranı tam kıvamında, çok ferahlatıcı.",
    "item.starters.caciki.review1.comment": "Yunan usulü yapılmış, gerçekten çok lezzetli.",
    "item.starters.caciki.review2.comment": "Çok taze ve lezzetli, yanında ekmekle harika gidiyor.",
    "item.starters.saksuka.name": "Şakşuka",
    "item.starters.saksuka.description": "Kızartılmış patlıcan, biber ve domates sosunun eşsiz uyumu. Hafif acı ve lezzet dolu bu Akdeniz mezesi, sofralarınıza renk katacak.",
    "item.starters.trakya-mamzana.name": "Trakya Mamzana",
    "item.starters.trakya-mamzana.description": "Közlenmiş patlıcan, biber ve soğan, sarımsaklı yoğurt ile birleşerek oluşturulan bu eşsiz lezzet, Trakya'nın otantik tadını sofralarınıza getiriyor.",
    "item.starters.atom-haydari.name": "Atom Haydari",
    "item.starters.atom-haydari.description": "Sarımsaklı yoğurt üzerine çıtır Edirne biberleriyle hazırlanan bu lezzetli meze, hem gözlere hem de damaklara hitap eder.",
    "item.starters.guvecte-manda-yogurdu.name": "Güveçte Manda Yoğurdu",
    "item.starters.guvecte-manda-yogurdu.description": "Toprak güveçlerde mayalandırılmış, doğal ve lezzetli manda yoğurdu. Yoğun kıvamı ve zengin aromasıyla sofralarınıza eşsiz bir tat katıyor.",
    "item.starters.karpuz-peynir.name": "Karpuz Peynir",
    "item.starters.karpuz-peynir.description": "Serinletici karpuz dilimleri, taze beyaz peynirle buluşuyor. Yazın vazgeçilmezi olan bu klasik ikili, ferahlatıcı ve lezzet dolu bir atıştırmalık.",
    "item.starters.soka-kaymakli-biber-tursusu.name": "Şoka Kaymaklı Biber Turşusu",
    "item.starters.soka-kaymakli-biber-tursusu.description": "Trakya ve Balkanların meşhur peynirli ve kaymaklı biber turşusu. Adds a refreshing touch to your table with its unique flavor.",
    "item.starters.soka-kaymakli-biber-tursusu.review0.comment": "Balkan lezzetini İstanbul'da bulabileceğimi düşünmezdim. Amazing taste!",
    "item.starters.soka-kaymakli-biber-tursusu.review1.comment": "Perfect for those missing Edirne, the harmony of cream and pickle is magnificent.",
    "item.starters.tereyagli-kasarli-mantar.name": "Tereyağlı Kaşarlı Mantar",
    "item.starters.tereyagli-kasarli-mantar.description": "Kendi suyunda pişmiş kültür, istiridye ve sarıkız mantarları, üzerinde graten Trakya taze kaşarı ile.",
    "item.starters.tereyagli-soganli-yaprak-ciger.name": "Tereyağlı Soğanlı Yaprak Ciğer",
    "item.starters.tereyagli-soganli-yaprak-ciger.description": "Soğan ve tereyağ ile sotelenmiş dana yaprak ciğer. Yumuşak dokusu ve zengin aromasıyla, geleneksel bir lezzet.",
    "item.starters.pacanga-boregi.name": "Paçanga Böreği",
    "item.starters.pacanga-boregi.description": "Pastırma, taze kaşar, domates ve biber ile hazırlanır. İçindeki malzemelerin uyumu ve çıtır dışıyla, sıcak ve lezzet dolu bir başlangıç.",
    "item.starters.pacanga-boregi.review0.comment": "Çıtır çıtır dışı, lezzetli içi ile harika bir atıştırmalık.",
    "item.starters.pacanga-boregi.review1.comment": "Pastırma ve peynir uyumu mükemmel, tekrar sipariş edeceğim.",
    "item.starters.patates-kizartmasi.name": "Patates Kızartması",
    "item.starters.patates-kizartmasi.description": "Altın sarısı ve çıtır patates kızartmaları, isteğe bağlı peynir seçeneği ile. Her lokmada keyif veren klasik bir lezzet.",
    "item.starters.ev-yapimi-patates-kizartmasi.name": "Ev Yapımı Patates Kızartması",
    "item.starters.ev-yapimi-patates-kizartmasi.description": "Çıtır çıtır ev yapımı patates kızartması, isteğe bağlı peynir seçeneği ile. Sıcacık ve doyurucu bir lezzet.",
    "item.starters.kizartma-sepeti.name": "Kızartma Sepeti",
    "item.starters.kizartma-sepeti.description": "Patates kızartması, hellim, soğan halkası, sosis, finger tavuk ve cheeseburger börekten oluşan lezzet dolu bir çeşitlilik.",
    "item.starters.sarkuteri-tahtasi.name": "Şarküteri Tahtası",
    "item.starters.sarkuteri-tahtasi.description": "Yöresel et, peynir ve meyveler ile hazırlanan bu enfes şarküteri tahtası, her lokmada farklı bir lezzet deneyimi sunar.",

    // Items - Salads
    "item.salads.bruschetta.name": "Bruschetta",
    "item.salads.bruschetta.description": "Sarımsaklı kızarmış ekmek dilimleri, üzerinde pesto soslu domates, peynir ve fesleğen ile hazırlanır. Hafif ve ferahlatıcı bir İtalyan klasiği.",
    "item.salads.yesil-salata.name": "Yeşil Salata",
    "item.salads.yesil-salata.description": "is a mix of Mediterranean greens served with a mustard olive oil dressing. This fresh and light salad is ideal for those seeking a healthy option.",
    "item.salads.peynirli-yesil-salata.name": "Peynirli Yeşil Salata",
    "item.salads.peynirli-yesil-salata.description": "is served with cheese, a mix of Mediterranean greens, and mustard olive oil dressing. This healthy, and flavorful salad will delight your palate.",
    "item.salads.roka-salata.name": "Roka Salata",
    "item.salads.roka-salata.description": "is prepared with rocket, sun-dried tomatoes, balsamic dressing, and grated Trakya aged kashar cheese.",
    "item.salads.shopska-salata.name": "Shopska Salata",
    "item.salads.shopska-salata.description": "is prepared with tomatoes, onions, cucumbers, peppers, parsley, olives, and grated white cheese. Served with toasted sourdough bread.",
    "item.salads.shopska-salata.review0.comment": "A fantastic salad that truly reflects the Balkan flavor.",
    "item.salads.shopska-salata.review1.comment": "The harmony of fresh vegetables and white cheese is magnificent, I always order it.",
    "item.salads.istanbul-salata.name": "İstanbul Salad",
    "item.salads.istanbul-salata.description": "is prepared with tomatoes, red onions, fresh thyme, and croutons. Crowned with a balsamic tomato dressing.",
    "item.salads.sezar-salata.name": "Caesar Salad",
    "item.salads.sezar-salata.description": "is prepared with crispy iceberg lettuce and marinated chicken, Caesar dressing, garlic croutons, and Parmesan cheese.",
    "item.salads.ananas-ve-buzlu-badem-salatasi.name": "Pineapple and Iced Almond Salad",
    "item.salads.ananas-ve-buzlu-badem-salatasi.description": "is a fresh mix of Mediterranean greens, pineapple slices, almonds, and balsamic dressing, offering a tropical flavour.",

    // Main Dishes
    "item.mainDishes.edirne-koftesi.name": "Edirne Meatballs",
    "item.mainDishes.edirne-koftesi.description": "Regionally famous Edirne meatballs, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.name": "Keşan Butcher's Meatballs",
    "item.mainDishes.kesan-satir-kofte.description": "Special butcher's meatballs made with the traditional Keşan cleaver technique, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.review0.comment": "The cleaver technique really makes a difference, delicious!",
    "item.mainDishes.kesan-satir-kofte.review1.comment": "Best meatballs I've had in Edirne.",
    "item.mainDishes.bosnak-kofte.name": "Boşnak Köfte",
    "item.mainDishes.bosnak-kofte.description": "Traditional Bosnian meatballs (pljeskavica) served with pita bread, ajvar, onions, and potatoes.",
    "item.mainDishes.bosnak-kofte.review0.comment": "Authentic Balkan taste, just like homemade.",
    "item.mainDishes.bosnak-kofte.review1.comment": "Very generous portion and great flavor.",
    "item.mainDishes.izgara-kasap-sucugu.name": "Izgara Kasap Sucuğu",
    "item.mainDishes.izgara-kasap-sucugu.description": "Flavorful grilled butcher's sausage, served with roasted peppers, onions, and rice.",
    "item.mainDishes.izgara-tavuk-sis.name": "Izgara Tavuk Şiş",
    "item.mainDishes.izgara-tavuk-sis.description": "Yumuşacık ızgara tavuk şiş, közlenmiş biber, soğan ve pilav ile servis edilir.",
    "item.mainDishes.pilic-kulbasti.name": "Piliç Külbastı",
    "item.mainDishes.pilic-kulbasti.description": "Grilled chicken fillet marinated in yogurt and spices, served with roasted peppers, onions, and rice.",
    "item.mainDishes.tavuk-schnitzel.name": "Tavuk Şnitzel",
    "item.mainDishes.tavuk-schnitzel.description": "Breaded and fried chicken cutlet, served with french fries and lemon.",
    "item.mainDishes.tereyagli-dana-bonfile.name": "Butter Beef Tenderloin",
    "item.mainDishes.tereyagli-dana-bonfile.description": "Juicy beef tenderloin cooked in butter, served with grilled vegetables.",
    "item.mainDishes.antrikot-sis.name": "Antrikot Şiş",
    "item.mainDishes.antrikot-sis.description": "Marinated ribeye skewers, grilled to perfection, served with roasted peppers, onions, and rice.",
    "item.mainDishes.antrikot-sis.review0.comment": "The meat was incredibly tender and flavorful.",
    "item.mainDishes.antrikot-sis.review1.comment": "A must-try for meat lovers!",
    "item.mainDishes.coban-kavurma.name": "Çoban Kavurma",
    "item.mainDishes.coban-kavurma.description": "Soğan, domates ve biberle kavrulmuş kuşbaşı dana eti, pilav ile servis edilir.",
    "item.mainDishes.kuzu-tandir.name": "Kuzu Tandır",
    "item.mainDishes.kuzu-tandir.description": "Ağır ateşte pişirilmiş kuzu tandır, yumuşacık ve lezzetli, pilav ve ızgara sebzeler ile servis edilir.",

    // Pasta
    "item.pasta.peynirli-edirne-koy-eristesi.name": "Peynirli Edirne Köy Eriştesi",
    "item.pasta.peynirli-edirne-koy-eristesi.description": "Tereyağı, nane, pul biber ve maydanozlu sosta pişen erişte makarna, kırık peynir ve ceviz ile taçlanır.",
    "item.pasta.peynirli-edirne-koy-eristesi.review0.comment": "Edirne'nin meşhur eriştesi, tereyağı ve peynir ile mükemmel bir uyum yakalamış.",
    "item.pasta.peynirli-edirne-koy-eristesi.review1.comment": "Ev yapımı erişte tadında, ceviz ve peynir kombinasyonu harika.",
    "item.pasta.kiyma-el-acmasi-makarna.name": "Kıymalı El Açması Makarna",
    "item.pasta.kiyma-el-acmasi-makarna.description": "Kavrulmuş dana kıyması ve taze el açması makarna ile hazırlanan bu lezzetli yemek, ev yapımı tadıyla sofralarınıza lezzet katıyor.",
    "item.pasta.penne-alfredo.name": "Penne Alfredo",
    "item.pasta.penne-alfredo.description": "Tavuk, krema, mantar, parmesan ve pesto sos ile hazırlanan Alfredo sos, penne makarna ile buluşuyor. Bu zengin lezzet sizi mutlu edecek.",
    "item.pasta.penne-napoliten.name": "Penne Napoliten",
    "item.pasta.penne-napoliten.description": "combines penne pasta with a basil and garlic tomato sauce made from summer tomatoes, topped with Thrace aged kashar cheese.",

    // Burgers
    "item.burgers.la-strada-burger.name": "La Strada Burger",
    "item.burgers.la-strada-burger.description": "Dana kaburga kıyması, cheddar peyniri, iceberg lettuce, pickles, tomatoes, and crispy onion pieces. This unique burger offers a rich and satisfying flavour with every bite.",
    "item.burgers.la-strada-crispy-burger.name": "La Strada Crispy Burger",
    "item.burgers.la-strada-crispy-burger.description": "has crispy chicken thighs, pickles, pickled red onions, and tomatoes. This delicious burger offers a crispy and fresh flavour experience with every bite.",
    "item.burgers.balkan-burger.name": "Balkan Burger",
    "item.burgers.balkan-burger.description": "brings the flavours of the Balkans to your table with roasted red pepper sauce, tomatoes, red onions, crispy pastrami slices, and ground beef ribs. This unique burger offers a rich and satisfying taste experience.",
    "item.burgers.balkan-burger.review0.comment": "A magnificent flavor with pastrami and roasted pepper sauce.",
    "item.burgers.balkan-burger.review1.comment": "A great idea combining Balkan flavors with a burger, very tasty.",

    // Desserts
    "item.desserts.cup-dondurma.name": "Cup dondurma",
    "item.desserts.cup-dondurma.description": "is a delightful ice cream extravaganza with wafer and fresh fruits! This delicious ice cream offers a refreshing and sweet treat.",
    "item.desserts.trilece.name": "Trileçe",
    "item.desserts.trilece.description": "is the famous caramel three-milk cake from the Balkans. With its soft texture and rich milk aroma, it offers a sweet explosion of flavor with every bite.",
    "item.desserts.karamelli-affogato.name": "Karamelli Affogato",
    "item.desserts.karamelli-affogato.description": "is a magnificent dessert with a cake base, ice cream, espresso, chocolate chips, walnuts, and caramel sauce.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.name": "Baked Edirne Cheese Halva",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.description": "is prepared with a traditional recipe and served with an option of ice cream. Each bite offers a unique flavour.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review0.comment": "It's great to find Edirne's famous cheese halva here, perfectly cooked.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review1.comment": "Serving it with ice cream is a great idea, perfect harmony.",
    "item.desserts.brownie.name": "Brownie",
    "item.desserts.brownie.description": "is served intensely chocolatey with an option of ice cream. Enjoy a chocolate extravaganza with every bite, featuring a warm and soft texture.",
    "item.desserts.fistikli-havuc-dilim-baklava.name": "Fıstıklı Havuç Dilim Baklava",
    "item.desserts.fistikli-havuc-dilim-baklava.description": "Her lokmada çıtırdayan dokusu ve yoğun fıstık aromasıyla damaklarınızı şenlendirecek.",

    // Drinks
    // Coffee
    "item.drinks.turk-kahvesi.name": "Türk Kahvesi",
    "item.drinks.turk-kahvesi.description": "Geleneksel Türk kahvesi, isteğe göre sade, orta veya şekerli.",
    "item.drinks.espresso.name": "Espresso",
    "item.drinks.espresso.description": "Yoğun aromalı İtalyan espresso.",
    "item.drinks.double-espresso.name": "Double Espresso",
    "item.drinks.double-espresso.description": "Çift shot espresso.",
    "item.drinks.americano.name": "Americano",
    "item.drinks.americano.description": "Espresso ve sıcak su ile hazırlanır.",
    "item.drinks.latte.name": "Latte",
    "item.drinks.latte.description": "Espresso ve buharla ısıtılmış süt ile hazırlanır.",
    "item.drinks.cappuccino.name": "Cappuccino",
    "item.drinks.cappuccino.description": "Espresso, buharla ısıtılmış süt ve süt köpüğü ile hazırlanır.",
    "item.drinks.sicak-cikolata.name": "Sıcak Çikolata",
    "item.drinks.sicak-cikolata.description": "Yoğun çikolata aromalı sıcak içecek.",
    "item.drinks.salep.name": "Salep",
    "item.drinks.salep.description": "Geleneksel Türk içeceği, tarçın ile servis edilir.",
    "item.drinks.filter-coffee.name": "Filtre Kahve",
    "item.drinks.filter-coffee.description": "Günlük öğütülmüş kahve çekirdeklerinden hazırlanır.",
    "item.drinks.sade-kahve.name": "Sade Kahve",
    "item.drinks.sade-kahve.description": "Türk usulü sade kahve.",
    "item.drinks.sutlu-kahve.name": "Sütlü Kahve",
    "item.drinks.sutlu-kahve.description": "Türk usulü sütlü kahve.",
    "item.drinks.soguk-kahve.name": "Soğuk Kahve",
    "item.drinks.soguk-kahve.description": "Buzlu soğuk kahve.",
    "item.drinks.frappe.name": "Frappe",
    "item.drinks.frappe.description": "Yunan usulü köpüklü soğuk kahve.",
    // Soft Drinks
    "item.drinks.cay.name": "Çay",
    "item.drinks.cay.description": "Geleneksel Türk çayı.",
    "item.drinks.bitki-cayi.name": "Bitki Çayı",
    "item.drinks.bitki-cayi.description": "Çeşitli bitki çayları (Ihlamur, Ada Çayı, Papatya, Yeşil Çay).",
    "item.drinks.su-small.name": "Su (Küçük)",
    "item.drinks.su-small.description": "Doğal kaynak suyu.",
    "item.drinks.su-large.name": "Su (Büyük)",
    "item.drinks.su-large.description": "Doğal kaynak suyu.",
    "item.drinks.san-pellegrino.name": "San Pellegrino",
    "item.drinks.san-pellegrino.description": "İtalyan maden suyu.",
    "item.drinks.soda.name": "Soda",
    "item.drinks.soda.description": "Sade veya limonlu maden suyu.",
    "item.drinks.kola.name": "Kola",
    "item.drinks.kola.description": "Coca-Cola, Diet Coke, Coca-Cola Zero.",
    "item.drinks.ayran.name": "Ayran",
    "item.drinks.ayran.description": "Geleneksel Türk yoğurt içeceği.",
    "item.drinks.meyve-suyu.name": "Meyve Suyu",
    "item.drinks.meyve-suyu.description": "Portakal, vişne, şeftali, kayısı, ananas.",
    "item.drinks.limonata.name": "Limonata",
    "item.drinks.limonata.description": "Ev yapımı taze limonata.",
    "item.drinks.tonic.name": "Tonic",
    "item.drinks.tonic.description": "Schweppes Tonik.",
    "item.drinks.red-bull.name": "Red Bull",
    "item.drinks.red-bull.description": "Enerji içeceği.",
    // Fresh Juices
    "item.drinks.portakal-suyu.name": "Portakal Suyu",
    "item.drinks.portakal-suyu.description": "Taze sıkılmış portakal suyu.",
    "item.drinks.nar-suyu.name": "Nar Suyu",
    "item.drinks.nar-suyu.description": "Taze sıkılmış nar suyu.",
    "item.drinks.elma-havuc-bal.name": "Elma Havuç Bal",
    "item.drinks.elma-havuc-bal.description": "Taze sıkılmış elma ve havuç suyu, bal ile tatlandırılmış.",
  },
  el: {
    // Common
    "app.name": "La Strada Restaurant",
    "app.hotel": "The Plaza Hotel Edirne",
    "app.selectLanguage": "Επιλέξτε Γλώσσα",
    "app.search": "Αναζήτηση",
    "app.cart": "Καλάθι",
    "app.menu": "Μενού",
    "app.order": "Παραγγελία",
    "app.processOrder": "Ολοκλήρωση Παραγγελίας",
    "app.orderSummary": "Σύνοψη Παραγγελίας",
    "app.subtotal": "Μερικό Σύνολο",
    "app.total": "Σύνολο",
    "app.tax": "Φόρος",
    "app.roomNumber": "Αριθμός Δωματίου",
    "app.tableNumber": "Αριθμός Τραπεζιού",
    "app.enterRoomOrTable": "Εισάγετε Αριθμό Δωματίου ή Τραπεζιού",
    "app.notes": "Σημειώσεις",
    "app.addNotes": "Προσθήκη Σημειώσεων",
    "app.back": "Πίσω",
    "app.continue": "Συνέχεια",
    "app.orderConfirmation": "Επιβεβαίωση Παραγγελίας",
    "app.orderSent": "Η παραγγελία σας έχει σταλεί!",
    "app.orderNumber": "Αριθμός Παραγγελίας",
    "app.orderTime": "Ώρα Παραγγελίας",
    "app.orderTotal": "Σύνολο Παραγγελίας",
    "app.newOrder": "Νέα Παραγγελία",
    "app.emptyCart": "Το καλάθι σας είναι άδειο",
    "app.addItems": "Προσθήκη Προϊόντων",
    "app.add": "Προσθήκη",
    "app.select": "Επιλογή",
    "app.addToCart": "Προσθήκη στο Καλάθι",
    "app.details": "Λεπτομέρειες",
    "app.allergens": "Αλλεργιογόνα",
    "app.reviews": "Κριτικές",
    "app.options": "Επιλογές",
    "app.portion": "Μερίδα",
    "app.allergenInfo": "Πληροφορίες Αλλεργιογόνων",
    "app.containsAllergens": "Αυτό το προϊόν περιέχει τα ακόλουθα αλλεργιογόνα",
    "app.allergenWarning": "Εάν έχετε αλλεργίες, παρακαλούμε ενημερώστε το προσωπικό πριν παραγγείλετε",
    "app.customerReviews": "Κριτικές Πελατών",
    "app.bestSeller": "Δημοφιλές",

    // Categories
    "category.all": "Όλο το Μενού",
    "category.breakfast": "Πρωινό",
    "category.starters": "Ορεκτικά και Μεζέδες",
    "category.salads": "Σαλάτες",
    "category.mainDishes": "Κυρίως Πιάτα",
    "category.pasta": "Ζυμαρικά",
    "category.burgers": "Μπέργκερ",
    "category.desserts": "Επιδόρπια",
    "category.drinks": "Ποτά",
    "category.spirits": "Οινοπνευματώδη Ποτά",
    "category.cocktails": "Κοκτέιλ",
    "category.beers": "Μπύρες",
    "category.wines": "Κρασιά",
    "category.extras": "Έξτρα",

    // Allergens
    "allergen.contains": "Περιέχει",
    "allergen.gluten": "Γλουτένη",
    "allergen.dairy": "Γαλακτοκομικά",
    "allergen.nuts": "Ξηροί Καρποί",
    "allergen.eggs": "Αυγά",
    "allergen.fish": "Ψάρι",
    "allergen.shellfish": "Οστρακοειδή",
    "allergen.soy": "Σόγια",
    "allergen.wheat": "Σιτάρι",
    "allergen.alcohol": "Αλκοόλ",

    // Wine
    "wine.pairing": "Συνδυασμός",
    "wine.pairsWellWith": "Αυτό το κρασί ταιριάζει καλά με",
    "wine.foodPairings": "Συνδυασμοί Φαγητού",

    // Items - Breakfast (Machine Translated)
    "item.breakfast.continental-kahvalti.name": "Ηπειρωτικό Πρωινό",
    "item.breakfast.continental-kahvalti.description": "Λευκό τυρί Εντιρνέ, απλή ομελέτα, τσένταρ, ντομάτα, αγγούρι, πιπεριά, ελιές, κ.λπ..",
    "item.breakfast.serpme-kahvalti.name": "Σερβιριστό Πρωινό",
    "item.breakfast.serpme-kahvalti.description": "Επιπλέον του ηπειρωτικού πρωινού: τηγανίτα, λουκάνικο, σαλάμι, μπισκότο, κουλούρι, κ.λπ..",
    "item.breakfast.pankek-pastasi.name": "Στοίβα Τηγανίτες",
    "item.breakfast.pankek-pastasi.description": "3 τηγανίτες και φρούτα εποχής",
    "item.breakfast.acik-bufe-kahvalti.name": "Πρωινό σε Μπουφέ",
    "item.breakfast.acik-bufe-kahvalti.description": "Μεταξύ 07:30 - 10:30",
    "item.breakfast.omlet.name": "Ομελέτα",
    "item.breakfast.omlet.description": "Απλή, με τυρί, λαχανικά, τσένταρ, σουτζούκι, λουκάνικο, καβουρμά",
    "item.breakfast.sahanda-goz-yumurta.name": "Τηγανητά Αυγά (Μάτια)",
    "item.breakfast.sahanda-goz-yumurta.description": "Φρεσκομαγειρεμένα τηγανητά αυγά",
    "item.breakfast.menemen.name": "Μενεμέν",
    "item.breakfast.menemen.description": "Μείγμα μενεμέν φτιαγμένο με πιπεριές χωριάτικες και καλοκαιρινές ντομάτες, με 2 αυγά..",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.name": "Τοστ με Διπλό Τυρί σε Προζυμένιο Ψωμί",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.description": "Τετράγωνο ψωμί τοστ με προζύμι, φρέσκο κασέρι Θράκης, σερβιρισμένο με σπιτική σάλτσα ντομάτας, ανάμεικτες ελιές, ντομάτα, αγγούρι",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.name": "Τοστ με Κασέρι και Σουτζούκι σε Προζυμένιο Ψωμί",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.description": "Τετράγωνο ψωμί τοστ με προζύμι, φρέσκο κασέρι Θράκης, μοσχαρίσιο σουτζούκι, σερβιρισμένο με σπιτική σάλτσα ντομάτας, ανάμεικτες ελιές, ντομάτα, αγγούρι",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.name": "Τοστ με 3 Τυριά σε Προζυμένιο Ψωμί",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.description": "Τετράγωνο ψωμί τοστ με προζύμι, φρέσκο κασέρι Θράκης, λευκό τυρί Εντιρνέ και παλαιωμένο κασκαβάλι Θράκης, σερβιρισμένο με σπιτική σάλτσα ντομάτας, ανάμεικτες ελιές, ντομάτα, αγγούρι",
    "item.breakfast.akitma.name": "Ακίτμα (Κρέπα Θρακιώτικη)",
    "item.breakfast.akitma.description": "Κρέπα Θρακιώτικη, σερβιρισμένη με λευκό τυρί Εντιρνέ, βιολογική μαρμελάδα βατόμουρο, ντομάτα, αγγούρι και ελιές",
    "item.breakfast.cicipapa.name": "Τσιτσιπάπα (Αυγοφέτες)",
    "item.breakfast.cicipapa.description": "4 φέτες αυγοφέτες, λευκό τυρί Εντιρνέ και φρέσκο κασέρι, σπιτική σάλτσα ατζούκα με καρύδια, ντομάτα, αγγούρι, πράσινη πιπεριά",

    // Items - Starters (Machine Translated)
    "item.starters.trakya-koy-tarhanasi.name": "Θρακιώτικη Χωριάτικη Σούπα Τραχανά",
    "item.starters.trakya-koy-tarhanasi.description": "Προετοιμασμένη με φυσικά υλικά, μια γεύση που ζεσταίνει την καρδιά. Αφήνει μια αξέχαστη γεύση με λευκό τυρί Εντιρνέ και φρυγανισμένο χωριάτικο ψωμί.",
    "item.starters.zeytinyagli-aysekadin-fasulye.name": "Φασολάκια Λαδερά",
    "item.starters.zeytinyagli-aysekadin-fasulye.description": "Μια ελαφριά και υγιεινή γεύση του Αιγαίου διακοσμημένη με λεμόνι και άνηθο.",
    "item.starters.caciki.name": "Τζατζίκι",
    "item.starters.caciki.description": "Η τέλεια αρμονία γιαουρτιού, αγγουριού, σκόρδου - ελαιόλαδου, παρασκευασμένη με ελληνικό τρόπο. Προσθέτει γεύση στο τραπέζι σας ως δροσιστικό και ελαφρύ ορεκτικό.",
    "item.starters.caciki.review0.comment": "Καταπληκτικό τζατζίκι! Η αναλογία σκόρδου είναι ακριβώς σωστή, πολύ δροσιστικό.",
    "item.starters.caciki.review1.comment": "Φτιαγμένο με ελληνικό τρόπο, πραγματικά νόστιμο.",
    "item.starters.caciki.review2.comment": "Πολύ φρέσκο και νόστιμο, ταιριάζει τέλεια με ψωμί.",
    "item.starters.saksuka.name": "Σακσούκα",
    "item.starters.saksuka.description": "Η μοναδική αρμονία τηγανητής μελιτζάνας, πιπεριάς και σάλτσας ντομάτας. Αυτό το ελαφρώς πικάντικο και γευστικό μεσογειακό ορεκτικό θα προσθέσει χρώμα στο τραπέζι σας.",
    "item.starters.trakya-mamzana.name": "Θρακιώτικη Μαμζάνα",
    "item.starters.trakya-mamzana.description": "Αυτή η μοναδική γεύση, που δημιουργείται συνδυάζοντας ψητή μελιτζάνα, πιπεριά και κρεμμύδι με γιαούρτι σκόρδου, φέρνει την αυθεντική γεύση της Θράκης στο τραπέζι σας.",
    "item.starters.atom-haydari.name": "Άτομ Χαϊντάρι",
    "item.starters.atom-haydari.description": "Αυτό το νόστιμο ορεκτικό, παρασκευασμένο με τραγανές πιπεριές Εντιρνέ πάνω σε γιαούρτι σκόρδου, απευθύνεται τόσο στα μάτια όσο και στον ουρανίσκο.",
    "item.starters.guvecte-manda-yogurdu.name": "Γιαούρτι Βουβαλίσιο σε Πήλινο",
    "item.starters.guvecte-manda-yogurdu.description": "Φυσικό και νόστιμο βουβαλίσιο γιαούρτι που έχει υποστεί ζύμωση σε πήλινα δοχεία. Προσθέτει μια μοναδική γεύση στο τραπέζι σας με την πηχτή του σύσταση και το πλούσιο άρωμά του.",
    "item.starters.karpuz-peynir.name": "Καρπούζι και Τυρί",
    "item.starters.karpuz-peynir.description": "Δροσιστικές φέτες καρπουζιού συναντούν φρέσκο λευκό τυρί. Αυτό το κλασικό δίδυμο, απαραίτητο το καλοκαίρι, είναι ένα δροσιστικό και γευστικό σνακ.",
    "item.starters.soka-kaymakli-biber-tursusu.name": "Πιπεριές Τουρσί Σόκα με Καϊμάκι",
    "item.starters.soka-kaymakli-biber-tursusu.description": "Οι διάσημες πιπεριές τουρσί με τυρί και καϊμάκι από τη Θράκη και τα Βαλκάνια. Προσθέτει μια δροσιστική πινελιά στο τραπέζι σας με τη μοναδική του γεύση.",
    "item.starters.soka-kaymakli-biber-tursusu.review0.comment": "Δεν πίστευα ότι θα μπορούσα να βρω τη βαλκανική γεύση στην Κωνσταντινούπολη. Καταπληκτική γεύση!",
    "item.starters.soka-kaymakli-biber-tursusu.review1.comment": "Ιδανικό για όσους τους λείπει η Αδριανούπολη, η αρμονία καϊμακιού και τουρσί είναι υπέροχη.",
    "item.starters.tereyagli-kasarli-mantar.name": "Μανιτάρια με Βούτυρο και Κασέρι",
    "item.starters.tereyagli-kasarli-mantar.description": "Καλλιεργημένα μανιτάρια, πλευρώτους και sarıkız μαγειρεμένα στον δικό τους χυμό, με γκρατέν φρέσκο κασέρι Θράκης από πάνω.",
    "item.starters.tereyagli-soganli-yaprak-ciger.name": "Συκώτι Φύλλο με Βούτυρο και Κρεμμύδι",
    "item.starters.tereyagli-soganli-yaprak-ciger.description": "Μοσχαρίσιο συκώτι φύλλο σοταρισμένο με κρεμμύδι και βούτυρο. Μια παραδοσιακή γεύση με τη μαλακή του υφή και το πλούσιο άρωμά του.",
    "item.starters.pacanga-boregi.name": "Πατσάνγκα Μπουρέκι",
    "item.starters.pacanga-boregi.description": "Παρασκευάζεται με παστουρμά, φρέσκο κασέρι, ντομάτα και πιπεριά. Ένα ζεστό και γευστικό ξεκίνημα με την αρμονία των υλικών του και το τραγανό εξωτερικό του.",
    "item.starters.pacanga-boregi.review0.comment": "Ένα υπέροχο σνακ με τραγανό εξωτερικό και νόστιμο εσωτερικό.",
    "item.starters.pacanga-boregi.review1.comment": "Η αρμονία παστουρμά και τυριού είναι τέλεια, θα παραγγείλω ξανά.",
    "item.starters.patates-kizartmasi.name": "Τηγανητές Πατάτες",
    "item.starters.patates-kizartmasi.description": "Χρυσαφένιες και τραγανές τηγανητές πατάτες, με προαιρετική επιλογή τυριού. Μια κλασική γεύση απολαυστική σε κάθε μπουκιά.",
    "item.starters.ev-yapimi-patates-kizartmasi.name": "Σπιτικές Τηγανητές Πατάτες",
    "item.starters.ev-yapimi-patates-kizartmasi.description": "Τραγανές σπιτικές τηγανητές πατάτες, με προαιρετική επιλογή τυριού. Μια ζεστή και χορταστική γεύση.",
    "item.starters.kizartma-sepeti.name": "Πιατέλα Τηγανητών",
    "item.starters.kizartma-sepeti.description": "Μια γευστική ποικιλία που αποτελείται από τηγανητές πατάτες, χαλούμι, κρεμμυδοδαχτυλίδια, λουκάνικο, κοτομπουκιές και μπουρέκι τσίζμπεργκερ.",
    "item.starters.sarkuteri-tahtasi.name": "Πλατώ Αλλαντικών",
    "item.starters.sarkuteri-tahtasi.description": "Αυτό το εξαιρετικό πλατώ αλλαντικών, παρασκευασμένο με τοπικά κρέατα, τυριά και φρούτα, προσφέρει μια διαφορετική γευστική εμπειρία σε κάθε μπουκιά.",

    // Items - Salads (EL Machine Translated from Corrected EN)
    "item.salads.bruschetta.name": "Μπρουσκέτα",
    "item.salads.bruschetta.description": "ετοιμάζεται με φρυγανισμένες φέτες ψωμιού με σκόρδο, γαρνιρισμένες με ντομάτες σε σάλτσα πέστο, τυρί και βασιλικό. Ένα ελαφρύ και δροσιστικό ιταλικό κλασικό.",
    "item.salads.yesil-salata.name": "Πράσινη Σαλάτα",
    "item.salads.yesil-salata.description": "είναι ένα μείγμα μεσογειακών χόρτων που σερβίρεται με σάλτσα μουστάρδας ελαιόλαδου. Αυτή η φρέσκια και ελαφριά σαλάτα είναι ιδανική για όσους αναζητούν μια υγιεινή επιλογή.",
    "item.salads.peynirli-yesil-salata.name": "Πράσινη Σαλάτα με Τυρί",
    "item.salads.peynirli-yesil-salata.description": "σερβίρεται με τυρί, μείγμα μεσογειακών χόρτων και σάλτσα μουστάρδας ελαιόλαδου. Αυτή η υγιεινή και γευστική σαλάτα θα ενθουσιάσει τον ουρανίσκο σας.",
    "item.salads.roka-salata.name": "Σαλάτα Ρόκα",
    "item.salads.roka-salata.description": "ετοιμάζεται με ρόκα, λιαστές ντομάτες, βαλσάμικο ξύδι και τριμμένο παλαιωμένο κασέρι Θράκης.",
    "item.salads.shopska-salata.name": "Σαλάτα Σόπσκα",
    "item.salads.shopska-salata.description": "ετοιμάζεται με ντομάτες, κρεμμύδια, αγγούρια, πιπεριές, μαϊντανό, ελιές και τριμμένο λευκό τυρί. Σερβίρεται με φρυγανισμένο προζυμένιο ψωμί.",
    "item.salads.shopska-salata.review0.comment": "Taze sebzeler ve lezzetli peynir, gerçek bir Trakya klasiği!",
    "item.salads.shopska-salata.review1.comment": "The best Shopska salad I've ever had, highly recommended.",
    "item.salads.istanbul-salata.name": "İstanbul Salata",
    "item.salads.istanbul-salata.description": "Domates, salatalık, biber, soğan, maydanoz, ceviz, galeta unu, nar ekşisi ve zeytinyağı.",
    "item.salads.sezar-salata.name": "Sezar Salata",
    "item.salads.sezar-salata.description": "Iceberg marul, çeri domates, kruton ekmek, parmesan peyniri, sezar sos.",
    "item.salads.ananas-ve-buzlu-badem-salatasi.name": "Ananas ve Buzlu Badem Salatası",
    "item.salads.ananas-ve-buzlu-badem-salatasi.description": "Akdeniz yeşillikleri, ananas, buzlu badem, mısır, çeri domates, limon vinaigrette sos.",

    // Main Dishes
    "item.mainDishes.edirne-koftesi.name": "Κεφτεδάκια Αδριανούπολης",
    "item.mainDishes.edirne-koftesi.description": "Φημισμένα κεφτεδάκια Αδριανούπολης, σερβιρισμένα με ψητές πιπεριές, κρεμμύδια και ρύζι.",
    "item.mainDishes.kesan-satir-kofte.name": "Κεφτεδάκια Χασάπη Κεσάν",
    "item.mainDishes.kesan-satir-kofte.description": "Ειδικά κεφτεδάκια χασάπη φτιαγμένα με την παραδοσιακή τεχνική μπαλτά Κεσάν, σερβιρισμένα με ψητές πιπεριές, κρεμμύδια και ρύζι.",
    "item.mainDishes.kesan-satir-kofte.review0.comment": "Η τεχνική του μπαλτά κάνει πραγματικά τη διαφορά, πεντανόστιμο!",
    "item.mainDishes.kesan-satir-kofte.review1.comment": "Τα καλύτερα κεφτεδάκια που έχω φάει στην Αδριανούπολη.",
    "item.mainDishes.bosnak-kofte.name": "Βοσνιακά Κεφτεδάκια",
    "item.mainDishes.bosnak-kofte.description": "Παραδοσιακά βοσνιακά κεφτεδάκια (pljeskavica) σερβιρισμένα με πίτα, άιβαρ, κρεμμύδια και πατάτες.",
    "item.mainDishes.bosnak-kofte.review0.comment": "Αυθεντική βαλκανική γεύση, σαν σπιτικό.",
    "item.mainDishes.bosnak-kofte.review1.comment": "Πολύ γενναιόδωρη μερίδα και υπέροχη γεύση.",
    "item.mainDishes.izgara-kasap-sucugu.name": "Ψητό Λουκάνικο Χασάπη",
    "item.mainDishes.izgara-kasap-sucugu.description": "Γευστικό ψητό λουκάνικο χασάπη, σερβιρισμένο με ψητές πιπεριές, κρεμμύδια και ρύζι.",
    "item.mainDishes.izgara-tavuk-sis.name": "Ψητά Σουβλάκια Κοτόπουλου",
    "item.mainDishes.izgara-tavuk-sis.description": "Τρυφερά ψητά σουβλάκια κοτόπουλου, σερβιρισμένα με ψητές πιπεριές, κρεμμύδια και ρύζι.",
    "item.mainDishes.pilic-kulbasti.name": "Κοτόπουλο Κιουλμπαστί",
    "item.mainDishes.pilic-kulbasti.description": "Ψητό φιλέτο κοτόπουλου μαριναρισμένο σε γιαούρτι και μπαχαρικά, σερβιρισμένο με ψητές πιπεριές, κρεμμύδια και ρύζι.",
    "item.mainDishes.tavuk-schnitzel.name": "Σνίτσελ Κοτόπουλου",
    "item.mainDishes.tavuk-schnitzel.description": "Παναρισμένο και τηγανητό φιλέτο κοτόπουλου, σερβιρισμένο με τηγανητές πατάτες και λεμόνι.",
    "item.mainDishes.tereyagli-dana-bonfile.name": "Μοσχαρίσιο Φιλέτο με Βούτυρο",
    "item.mainDishes.tereyagli-dana-bonfile.description": "Ζουμερό μοσχαρίσιο φιλέτο μαγειρεμένο σε βούτυρο, σερβιρισμένο με ψητά λαχανικά.",
    "item.mainDishes.antrikot-sis.name": "Σουβλάκια Ribeye",
    "item.mainDishes.antrikot-sis.description": "Μαριναρισμένα σουβλάκια ribeye, ψημένα τέλεια, σερβιρισμένα με ψητές πιπεριές, κρεμμύδια και ρύζι.",
    "item.mainDishes.antrikot-sis.review0.comment": "Το κρέας ήταν απίστευτα τρυφερό και γευστικό.",
    "item.mainDishes.antrikot-sis.review1.comment": "Ένα must-try για τους λάτρεις του κρέατος!",
    "item.mainDishes.coban-kavurma.name": "Σοτέ του Βοσκού",
    "item.mainDishes.coban-kavurma.description": "Μοσχάρι κομμένο σε κύβους σοταρισμένο με κρεμμύδια, ντομάτες και πιπεριές, σερβιρισμένο με ρύζι.",
    "item.mainDishes.kuzu-tandir.name": "Αρνί Ταντούρι",
    "item.mainDishes.kuzu-tandir.description": "Αργομαγειρεμένο αρνί ταντούρι, τρυφερό και γευστικό, σερβιρισμένο με ρύζι και ψητά λαχανικά.",

    // Pasta
    "item.pasta.peynirli-edirne-koy-eristesi.name": "Νούντλς Αδριανούπολης με Τυρί",
    "item.pasta.peynirli-edirne-koy-eristesi.description": "μαγειρεύονται σε σάλτσα από βούτυρο, μέντα, νιφάδες κόκκινης πιπεριάς και μαϊντανό, και στη συνέχεια στεφανώνονται με τριμμένο τυρί και καρύδια.",
    "item.pasta.peynirli-edirne-koy-eristesi.review0.comment": "Τα διάσημα νουντλς της Αδριανούπολης, ο συνδυασμός βουτύρου και τυριού είναι τέλειος.",
    "item.pasta.peynirli-edirne-koy-eristesi.review1.comment": "Έχουν γεύση σαν σπιτικά νουντλς, ο συνδυασμός καρυδιού και τυριού είναι υπέροχος.",
    "item.pasta.kiyma-el-acmasi-makarna.name": "Σπιτικά Ζυμαρικά με Κιμά",
    "item.pasta.kiyma-el-acmasi-makarna.description": "είναι ένα νόστιμο πιάτο φτιαγμένο με ψητό μοσχαρίσιο κιμά και φρέσκα σπιτικά ζυμαρικά. Προσθέτει μια ζεστή, σπιτική πινελιά στο τραπέζι σας.",
    "item.pasta.penne-alfredo.name": "Πέννες Αλφρέντο",
    "item.pasta.penne-alfredo.description": "συνδυάζει πέννες με σάλτσα Αλφρέντο φτιαγμένη από κοτόπουλο, κρέμα γάλακτος, μανιτάρια, παρμεζάνα και σάλτσα πέστο.",
    "item.pasta.penne-napoliten.name": "Πέννες Ναπολιτέν",
    "item.pasta.penne-napoliten.description": "συνδυάζει πέννες με σάλτσα ντομάτας με βασιλικό και σκόρδο φτιαγμένη από καλοκαιρινές ντομάτες, γαρνιρισμένη με παλαιωμένο κασέρι Θράκης.",

    // Burgers
    "item.burgers.la-strada-burger.name": "La Strada Burger",
    "item.burgers.la-strada-burger.description": "φτιάχνεται από κιμά μοσχαρίσιων πλευρών, τυρί τσένταρ, μαρούλι iceberg, αγγουράκια τουρσί, ντομάτες και τραγανά κομμάτια κρεμμυδιού. Αυτό το μοναδικό μπέργκερ προσφέρει πλούσια και ικανοποιητική γεύση με κάθε μπουκιά.",
    "item.burgers.la-strada-crispy-burger.name": "La Strada Crispy Burger",
    "item.burgers.la-strada-crispy-burger.description": "έχει τραγανά μπούτια κοτόπουλου, αγγουράκια τουρσί, κόκκινα κρεμμύδια τουρσί και ντομάτες. Αυτό το νόστιμο μπέργκερ προσφέρει μια τραγανή και φρέσκια γευστική εμπειρία με κάθε μπουκιά.",
    "item.burgers.balkan-burger.name": "Balkan Burger",
    "item.burgers.balkan-burger.description": "φέρνει τις γεύσεις των Βαλκανίων στο τραπέζι σας με σάλτσα από ψητή κόκκινη πιπεριά, ντομάτες, κόκκινα κρεμμύδια, τραγανές φέτες παστουρμά και κιμά μοσχαρίσιων πλευρών. Αυτό το μοναδικό μπέργκερ προσφέρει μια πλούσια και ικανοποιητική γευστική εμπειρία.",
    "item.burgers.balkan-burger.review0.comment": "Μια υπέροχη γεύση με παστουρμά και σάλτσα ψητής πιπεριάς.",
    "item.burgers.balkan-burger.review1.comment": "Μια εξαιρετική ιδέα που συνδυάζει τις βαλκανικές γεύσεις με ένα μπέργκερ, πολύ νόστιμο.",

    // Desserts
    "item.desserts.cup-dondurma.name": "Παγωτό σε Κύπελλο",
    "item.desserts.cup-dondurma.description": "είναι μια απολαυστική феерия παγωτού με βάφλα και φρέσκα φρούτα! Αυτό το νόστιμο παγωτό προσφέρει μια δροσιστική και γλυκιά απόλαυση.",
    "item.desserts.trilece.name": "Τριλέτσε",
    "item.desserts.trilece.description": "είναι το διάσημο καραμελωμένο κέικ τριών γάλακτων από τα Βαλκάνια. Με την απαλή του υφή και το πλούσιο άρωμα γάλακτος, προσφέρει μια γλυκιά έκρηξη γεύσης με κάθε μπουκιά.",
    "item.desserts.karamelli-affogato.name": "Καραμελωμένο Αφογκάτο",
    "item.desserts.karamelli-affogato.description": "είναι ένα υπέροχο επιδόρπιο με βάση κέικ, παγωτό, εσπρέσο, κομματάκια σοκολάτας, καρύδια και σάλτσα καραμέλας.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.name": "Ψημένος Χαλβάς με Τυρί Αδριανούπολης",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.description": "ετοιμάζεται με παραδοσιακή συνταγή και σερβίρεται με επιλογή παγωτού. Κάθε μπουκιά προσφέρει μια μοναδική γεύση.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review0.comment": "Είναι υπέροχο που βρίσκουμε τον διάσημο χαλβά με τυρί της Αδριανούπολης εδώ, τέλεια μαγειρεμένος.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review1.comment": "Το να σερβίρεται με παγωτό είναι εξαιρετική ιδέα, τέλεια αρμονία.",
    "item.desserts.brownie.name": "Μπράουνι",
    "item.desserts.brownie.description": "σερβίρεται έντονα σοκολατένιο με επιλογή παγωτού. Απολαύστε μια σοκολατένια феерия με κάθε μπουκιά, με ζεστή και απαλή υφή.",
    "item.desserts.fistikli-havuc-dilim-baklava.name": "Μπακλαβάς με Φιστίκι",
    "item.desserts.fistikli-havuc-dilim-baklava.description": "θα ενθουσιάσει τον ουρανίσκο σας με την τραγανή του υφή και την έντονη γεύση φιστικιού σε κάθε μπουκιά.",

    // Drinks
    // Coffee
    "item.drinks.turk-kahvesi.name": "Τούρκικος Καφές",
    "item.drinks.turk-kahvesi.description": "Παραδοσιακός τούρκικος καφές, σερβίρεται σκέτος, μέτριος ή γλυκός κατόπιν αιτήματος.",
    "item.drinks.espresso.name": "Εσπρέσο",
    "item.drinks.espresso.description": "Έντονος ιταλικός εσπρέσο.",
    "item.drinks.double-espresso.name": "Διπλός Εσπρέσο",
    "item.drinks.double-espresso.description": "Διπλή δόση εσπρέσο.",
    "item.drinks.americano.name": "Αμερικάνο",
    "item.drinks.americano.description": "Παρασκευάζεται με εσπρέσο και ζεστό νερό.",
    "item.drinks.latte.name": "Λάτε",
    "item.drinks.latte.description": "Παρασκευάζεται με εσπρέσο και γάλα στον ατμό.",
    "item.drinks.cappuccino.name": "Καπουτσίνο",
    "item.drinks.cappuccino.description": "Παρασκευάζεται με εσπρέσο, γάλα στον ατμό και αφρόγαλα.",
    "item.drinks.sicak-cikolata.name": "Ζεστή Σοκολάτα",
    "item.drinks.sicak-cikolata.description": "Ζεστό ρόφημα με έντονη γεύση σοκολάτας.",
    "item.drinks.salep.name": "Σαλέπι",
    "item.drinks.salep.description": "Παραδοσιακό τούρκικο ρόφημα, σερβίρεται με κανέλα.",
    "item.drinks.filter-coffee.name": "Καφές Φίλτρου",
    "item.drinks.filter-coffee.description": "Παρασκευάζεται από καθημερινά αλεσμένους κόκκους καφέ.",
    "item.drinks.sade-kahve.name": "Σκέτος Καφές",
    "item.drinks.sade-kahve.description": "Τούρκικος σκέτος καφές.",
    "item.drinks.sutlu-kahve.name": "Καφές με Γάλα",
    "item.drinks.sutlu-kahve.description": "Τούρκικος καφές με γάλα.",
    "item.drinks.soguk-kahve.name": "Κρύος Καφές (Cold Brew)",
    "item.drinks.soguk-kahve.description": "Παγωμένος κρύος καφές.",
    "item.drinks.frappe.name": "Φραπέ",
    "item.drinks.frappe.description": "Ελληνικός αφρώδης κρύος καφές.",
    // Soft Drinks
    "item.drinks.cay.name": "Τσάι",
    "item.drinks.cay.description": "Παραδοσιακό τούρκικο τσάι.",
    "item.drinks.bitki-cayi.name": "Τσάι Βοτάνων",
    "item.drinks.bitki-cayi.description": "Διάφορα τσάγια βοτάνων (Τίλιο, Φασκόμηλο, Χαμομήλι, Πράσινο Τσάι).",
    "item.drinks.su-small.name": "Νερό (Μικρό)",
    "item.drinks.su-small.description": "Φυσικό μεταλλικό νερό.",
    "item.drinks.su-large.name": "Νερό (Μεγάλο)",
    "item.drinks.su-large.description": "Φυσικό μεταλλικό νερό.",
    "item.drinks.san-pellegrino.name": "San Pellegrino",
    "item.drinks.san-pellegrino.description": "Ιταλικό μεταλλικό νερό.",
    "item.drinks.soda.name": "Σόδα (Ανθρακούχο Νερό)",
    "item.drinks.soda.description": "Απλό ή με λεμόνι ανθρακούχο νερό.",
    "item.drinks.kola.name": "Κόλα",
    "item.drinks.kola.description": "Coca-Cola, Diet Coke, Coca-Cola Zero.",
    "item.drinks.ayran.name": "Αριάνι",
    "item.drinks.ayran.description": "Παραδοσιακό τούρκικο ρόφημα γιαουρτιού.",
    "item.drinks.meyve-suyu.name": "Χυμός",
    "item.drinks.meyve-suyu.description": "Πορτοκάλι, βύσσινο, ροδάκινο, βερίκοκο, ανανάς.",
    "item.drinks.limonata.name": "Λεμονάδα",
    "item.drinks.limonata.description": "Σπιτική φρέσκια λεμονάδα.",
    "item.drinks.tonic.name": "Τόνικ",
    "item.drinks.tonic.description": "Schweppes Tonic Water.",
    "item.drinks.red-bull.name": "Red Bull",
    "item.drinks.red-bull.description": "Ενεργειακό ποτό.",
    // Fresh Juices
    "item.drinks.portakal-suyu.name": "Χυμός Πορτοκάλι",
    "item.drinks.portakal-suyu.description": "Φρεσκοστυμμένος χυμός πορτοκάλι.",
    "item.drinks.nar-suyu.name": "Χυμός Ρόδι",
    "item.drinks.nar-suyu.description": "Φρεσκοστυμμένος χυμός ρόδι.",
    "item.drinks.elma-havuc-bal.name": "Μήλο Καρότο Μέλι",
    "item.drinks.elma-havuc-bal.description": "Φρεσκοστυμμένος χυμός μήλου και καρότου, γλυκαμένος με μέλι.",
  },
  bg: {
    // Common
    "app.name": "La Strada Restaurant",
    "app.hotel": "The Plaza Hotel Edirne",
    "app.selectLanguage": "Изберете Език",
    "app.search": "Търсене",
    "app.cart": "Кошница",
    "app.menu": "Меню",
    "app.order": "Поръчка",
    "app.processOrder": "Завършване на Поръчката",
    "app.orderSummary": "Резюме на Поръчката",
    "app.subtotal": "Междинна Сума",
    "app.total": "Общо",
    "app.tax": "Данък",
    "app.roomNumber": "Номер на Стая",
    "app.tableNumber": "Номер на Маса",
    "app.enterRoomOrTable": "Въведете Номер на Стая или Маса",
    "app.notes": "Бележки",
    "app.addNotes": "Добавяне на Бележки",
    "app.back": "Назад",
    "app.continue": "Продължи",
    "app.orderConfirmation": "Потвърждение на Поръчката",
    "app.orderSent": "Вашата поръчка е изпратена!",
    "app.orderNumber": "Номер на Поръчка",
    "app.orderTime": "Време на Поръчка",
    "app.orderTotal": "Обща Сума",
    "app.newOrder": "Нова Поръчка",
    "app.emptyCart": "Вашата кошница е празна",
    "app.addItems": "Добавяне на Продукти",
    "app.add": "Добави",
    "app.select": "Избери",
    "app.addToCart": "Добави в Кошницата",
    "app.details": "Детайли",
    "app.allergens": "Алергени",
    "app.reviews": "Отзиви",
    "app.options": "Опции",
    "app.portion": "Порция",
    "app.allergenInfo": "Информация за Алергени",
    "app.containsAllergens": "Този продукт съдържа следните алергени",
    "app.allergenWarning": "Ако имате алергии, моля информирайте персонала преди да поръчате",
    "app.customerReviews": "Отзиви от Клиенти",
    "app.bestSeller": "Най-Продаван",

    // Categories
    "category.all": "Цялото Меню",
    "category.breakfast": "Закуска",
    "category.starters": "Предястия и Мезета",
    "category.salads": "Салати",
    "category.mainDishes": "Основни Ястия",
    "category.pasta": "Паста",
    "category.burgers": "Бургери",
    "category.desserts": "Десерти",
    "category.drinks": "Напитки",
    "category.spirits": "Високоалкохолни Напитки",
    "category.cocktails": "Коктейли",
    "category.beers": "Бира",
    "category.wines": "Вино",
    "category.extras": "Екстри",

    // Allergens
    "allergen.contains": "Съдържа",
    "allergen.gluten": "Глутен",
    "allergen.dairy": "Млечни Продукти",
    "allergen.nuts": "Ядки",
    "allergen.eggs": "Яйца",
    "allergen.fish": "Риба",
    "allergen.shellfish": "Ракообразни",
    "allergen.soy": "Соя",
    "allergen.wheat": "Пшеница",
    "allergen.alcohol": "Алкохол",

    // Wine
    "wine.pairing": "Съчетание",
    "wine.pairsWellWith": "Това вино се съчетава добре с",
    "wine.foodPairings": "Съчетания с Храна",

    // Items - Breakfast (Machine Translated)
    "item.breakfast.continental-kahvalti.name": "Континентална Закуска",
    "item.breakfast.continental-kahvalti.description": "Одринско бяло сирене, обикновен омлет, кашкавал, домат, краставица, чушка, маслини и др..",
    "item.breakfast.serpme-kahvalti.name": "Сервирана Закуска",
    "item.breakfast.serpme-kahvalti.description": "В допълнение към континенталната закуска: палачинка, наденица, салам, бисквита, геврек и др..",
    "item.breakfast.pankek-pastasi.name": "Палачинкова Кула",
    "item.breakfast.pankek-pastasi.description": "3 палачинки и сезонни плодове",
    "item.breakfast.acik-bufe-kahvalti.name": "Закуска на Шведска Маса",
    "item.breakfast.acik-bufe-kahvalti.description": "Между 07:30 - 10:30 часа",
    "item.breakfast.omlet.name": "Омлет",
    "item.breakfast.omlet.description": "Обикновен, със сирене, зеленчуци, кашкавал, суджук, наденица, печено месо",
    "item.breakfast.sahanda-goz-yumurta.name": "Пържени Яйца (на очи)",
    "item.breakfast.sahanda-goz-yumurta.description": "Прясно приготвени пържени яйца",
    "item.breakfast.menemen.name": "Менемен",
    "item.breakfast.menemen.description": "Мείγμα μενεμέν φтιαγμένο με πιπεριές χωριάτικες και καλοκαιριнές ντομάτες, με 2 αυγά..",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.name": "Препечена Филийка с Двоен Кашкавал на Хляб с Квас",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.description": "Квадратен препечен хляб с квас, Тракийски пресен кашкавал, сервиран с домашна доматена паста, смесени маслини, домат, краставица",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.name": "Препечена Филийка с Кашкавал и Суджук на Хляб с Квас",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.description": "Квадратен препечен хляб с квас, Тракийски пресен кашкавал, телешки суджук, сервиран с домашна доматена паста, смесени маслини, домат, краставица",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.name": "Препечена Филийка с 3 Сирена на Хляб с Квас",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.description": "Квадратен препечен хляб с квас, Тракийски пресен кашкавал, Одринско бяло сирене и Тракийски зрял кашкавал, сервиран с домашна доматена паста, смесени маслини, домат, краставица",
    "item.breakfast.akitma.name": "Акътма (Тракийска Палачинка)",
    "item.breakfast.akitma.description": "Тракийска палачинка, сервирана с Одринско бяло сирене, органично сладко от къпини, домат, краставица и маслини",
    "item.breakfast.cicipapa.name": "Джиджипапа (Пържени Филийки)",
    "item.breakfast.cicipapa.description": "4 филийки пържени яйца, Одринско бяло сирене и пресен кашкавал, домашен сос аджука с орехи, домат, краставица, зелена чушка",

    // Items - Starters (Machine Translated)
    "item.starters.trakya-koy-tarhanasi.name": "Тракийска Селска Супа Тарана",
    "item.starters.trakya-koy-tarhanasi.description": "Приготвена с натурални съставки, стоплящ сърцето вкус. Оставя незабравим вкус с Одринско бяло сирене и препечен селски хляб.",
    "item.starters.zeytinyagli-aysekadin-fasulye.name": "Зелен Фасул със Зехтин",
    "item.starters.zeytinyagli-aysekadin-fasulye.description": "Лек и здравословен Егейски вкус, украсен с лимон и копър.",
    "item.starters.caciki.name": "Джаджики (Таратор)",
    "item.starters.caciki.description": "Перфектната хармония на кисело мляко, краставица, чесън - зехтин, приготвени по гръцки стил. Добавя вкус към вашата маса като освежаващо и леко предястие.",
    "item.starters.caciki.review0.comment": "Невероятен джаджики! Съотношението на чесън е точно както трябва, много освежаващо.",
    "item.starters.caciki.review1.comment": "Направен по гръцки, наистина вкусен.",
    "item.starters.caciki.review2.comment": "Много свеж и вкусен, върви чудесно с хляб.",
    "item.starters.saksuka.name": "Шакшука",
    "item.starters.saksuka.description": "Уникалната хармония на пържен патладжан, чушка и доматен сос. Това леко пикантно и ароматно средиземноморско предястие ще добави цвят към вашата маса.",
    "item.starters.trakya-mamzana.name": "Тракийска Мамзана",
    "item.starters.trakya-mamzana.description": "Този уникален вкус, създаден чрез комбиниране на печен патладжан, чушка и лук с чесново кисело мляко, носи автентичния вкус на Тракия на вашата маса.",
    "item.starters.atom-haydari.name": "Атом Хайдари",
    "item.starters.atom-haydari.description": "Това вкусно предястие, приготвено с хрупкави Одрински чушки върху чесново кисело мляко, привлича както очите, така и небцето.",
    "item.starters.guvecte-manda-yogurdu.name": "Биволско Кисело Мляко в Гювеч",
    "item.starters.guvecte-manda-yogurdu.description": "Натурално и вкусно биволско кисело мляко, ферментирало в глинени съдове. Добавя уникален вкус към вашата маса със своята гъста консистенция и богат аромат.",
    "item.starters.karpuz-peynir.name": "Диня и Сирене",
    "item.starters.karpuz-peynir.description": "Освежаващи резени диня се срещат с прясно бяло сирене. Този класически дует, незаменим през лятото, е освежаваща и ароматна закуска.",
    "item.starters.soka-kaymakli-biber-tursusu.name": "Туршия от Чушки Сока с Каймак",
    "item.starters.soka-kaymakli-biber-tursusu.description": "Известната туршия от чушки със сирене и каймак от Тракия и Балканите. Добавя освежаващ щрих към вашата маса със своя уникален вкус.",
    "item.starters.soka-kaymakli-biber-tursusu.review0.comment": "Не мислех, че мога да намеря балканския вкус в Истанбул. Невероятен вкус!",
    "item.starters.soka-kaymakli-biber-tursusu.review1.comment": "Идеално за тези, които им липсва Одрин, хармонията на каймак и туршия е великолепна.",
    "item.starters.tereyagli-kasarli-mantar.name": "Гъби с Масло и Кашкавал",
    "item.starters.tereyagli-kasarli-mantar.description": "Култивирани, стриди и саръкъз гъби, приготвени в собствен сос, със запечен Тракийски пресен кашкавал отгоре.",
    "item.starters.tereyagli-soganli-yaprak-ciger.name": "Дроб по Селски с Масло и Лук",
    "item.starters.tereyagli-soganli-yaprak-ciger.description": "Телешки дроб, нарязан на листа, сотиран с лук и масло. Традиционен вкус с мека текстура и богат аромат.",
    "item.starters.pacanga-boregi.name": "Пачанга Бьорек",
    "item.starters.pacanga-boregi.description": "Приготвен с пастърма, пресен кашкавал, домат и чушка. Горещо и ароматно начало с хармонията на съставките и хрупкавата коричка.",
    "item.starters.pacanga-boregi.review0.comment": "Страхотна закуска с хрупкава коричка и вкусен пълнеж.",
    "item.starters.pacanga-boregi.review1.comment": "Хармонията на пастърма и сирене е перфектна, ще поръчам отново.",
    "item.starters.patates-kizartmasi.name": "Пържени Картофи",
    "item.starters.patates-kizartmasi.description": "Златисти и хрупкави пържени картофи, с опция за сирене. Класически вкус, приятен при всяка хапка.",
    "item.starters.ev-yapimi-patates-kizartmasi.name": "Домашни Пържени Картофи",
    "item.starters.ev-yapimi-patates-kizartmasi.description": "Хрупкави домашни пържени картофи, с опция за сирене. Топъл и засищащ вкус.",
    "item.starters.kizartma-sepeti.name": "Плато с Пържени Храни",
    "item.starters.kizartma-sepeti.description": "Ароматно разнообразие, състоящо се от пържени картофи, халуми, лучени кръгчета, наденица, пилешки пръчици и чийзбургер бьорек.",
    "item.starters.sarkuteri-tahtasi.name": "Плато с Деликатеси",
    "item.starters.sarkuteri-tahtasi.description": "Това изискано плато с деликатеси, приготвено с местни меса, сирена и плодове, предлага различно вкусово изживяване при всяка хапка.",

    // Items - Salads (BG Machine Translated from Corrected EN)
    "item.salads.bruschetta.name": "Брускета",
    "item.salads.bruschetta.description": "се приготвя с препечени филийки хляб с чесън, гарнирани с домати в песто сос, сирене и босилек. Лека и освежаваща италианска класика.",
    "item.salads.yesil-salata.name": "Зелена Салата",
    "item.salads.yesil-salata.description": "е микс от средиземноморски зеленчуци, сервиран със сос от горчица и зехтин. Тази свежа и лека салата е идеална за тези, които търсят здравословна опция.",
    "item.salads.peynirli-yesil-salata.name": "Зелена Салата със Сирене",
    "item.salads.peynirli-yesil-salata.description": "се сервира със сирене, микс от средиземноморски зеленчуци и сос от горчица и зехтин. Тази здравословна и ароматна салата ще зарадва небцето ви.",
    "item.salads.roka-salata.name": "Салата Рукола",
    "item.salads.roka-salata.description": "се приготвя с рукола, сушени домати, балсамов дресинг и настърган Тракийски зрял кашкавал.",
    "item.salads.shopska-salata.name": "Шопска Салата",
    "item.salads.shopska-salata.description": "се приготвя с домати, лук, краставици, чушки, магданоз, маслини и настъргано бяло сирене. Сервира се с препечен хляб с квас.",
    "item.salads.shopska-salata.review0.comment": "Пресни зеленчуци и вкусно сирене, истинска тракийска класика!",
    "item.salads.shopska-salata.review1.comment": "Най-добрата шопска салата, която съм ял някога, силно препоръчвам.",
    "item.salads.istanbul-salata.name": "Истанбулска салата",
    "item.salads.istanbul-salata.description": "Домати, краставици, чушки, лук, магданоз, орехи, галета, нар меласа и зехтин.",
    "item.salads.sezar-salata.name": "Салата Цезар",
    "item.salads.sezar-salata.description": "Айсберг, чери домати, kruton ekmek, parmesan peyniri, sezar sos.",
    "item.salads.ananas-ve-buzlu-badem-salatasi.name": "Салата с Ананас и Ледени Бадеми",
    "item.salads.ananas-ve-buzlu-badem-salatasi.description": "Средиземноморски зеленчуци, ананас, бузлу бадем, мысыр, чери домати, лимонов винегрет.",

    // Main Dishes
    "item.mainDishes.edirne-koftesi.name": "Одрински кюфтета",
    "item.mainDishes.edirne-koftesi.description": "Прочути одрински кюфтета, сервирани с печени чушки, лук и ориз.",
    "item.mainDishes.kesan-satir-kofte.name": "Кешански касапски кюфтета",
    "item.mainDishes.kesan-satir-kofte.description": "Специални касапски кюфтета, приготвени по традиционната кешанска техника със сатър, сервирани с печени чушки, лук и ориз.",
    "item.mainDishes.kesan-satir-kofte.review0.comment": "Техниката със сатър наистина прави разликата, вкусно!",
    "item.mainDishes.kesan-satir-kofte.review1.comment": "Най-добрите кюфтета, които съм ял в Одрин.",
    "item.mainDishes.bosnak-kofte.name": "Boşnak Köfte",
    "item.mainDishes.bosnak-kofte.description": "Geleneksel Boşnak köftesi (pljeskavica), pide, ajvar, soğan ve patates ile servis edilir.",
    "item.mainDishes.bosnak-kofte.review0.comment": "Authentic Balkan taste, just like homemade.",
    "item.mainDishes.bosnak-kofte.review1.comment": "Very generous portion and great flavor.",
    "item.mainDishes.izgara-kasap-sucugu.name": "Izgara Kasap Sucuğu",
    "item.mainDishes.izgara-kasap-sucugu.description": "Lezzetli ızgara kasap sucuğu, közlenmiş biber, soğan ve pilav ile servis edilir.",
    "item.mainDishes.izgara-tavuk-sis.name": "Izgara Tavuk Şiş",
    "item.mainDishes.izgara-tavuk-sis.description": "Yumuşacık ızgara tavuk şiş, közlenmiş biber, soğan ve pilav ile servis edilir.",
    "item.mainDishes.pilic-kulbasti.name": "Piliç Külbastı",
    "item.mainDishes.pilic-kulbasti.description": "Yoğurt ve baharatlarla marine edilmiş ızgara tavuk fileto, közlenmiş biber, soğan ve pilav ile servis edilir.",
    "item.mainDishes.tavuk-schnitzel.name": "Tavuk Şnitzel",
    "item.mainDishes.tavuk-schnitzel.description": "Panelenmiş ve kızartılmış tavuk göğsü, patates kızartması ve limon ile servis edilir.",
    "item.mainDishes.tereyagli-dana-bonfile.name": "Tereyağlı Dana Bonfile",
    "item.mainDishes.tereyagli-dana-bonfile.description": "Tereyağında pişirilmiş sulu dana bonfile, ızgara sebzeler ile servis edilir.",
    "item.mainDishes.antrikot-sis.name": "Antrikot Şiş",
    "item.mainDishes.antrikot-sis.description": "Marine edilmiş antrikot şiş, mükemmel pişirilmiş, közlenmiş biber, soğan ve pilav ile servis edilir.",
    "item.mainDishes.antrikot-sis.review0.comment": "Et inanılmaz yumuşak ve lezzetliydi.",
    "item.mainDishes.antrikot-sis.review1.comment": "Et severler mutlaka denemeli!",
    "item.mainDishes.coban-kavurma.name": "Çoban Kavurma",
    "item.mainDishes.coban-kavurma.description": "Soğan, domates ve biberle kavrulmuş kuşbaşı dana eti, pilav ile servis edilir.",
    "item.mainDishes.kuzu-tandir.name": "Kuzu Tandır",
    "item.mainDishes.kuzu-tandir.description": "Ağır ateşte pişirilmiş kuzu tandır, yumuşacık ve lezzetli, pilav ve ızgara sebzeler ile servis edilir.",

    // Pasta
    "item.pasta.peynirli-edirne-koy-eristesi.name": "Одринска юфка със сирене",
    "item.pasta.peynirli-edirne-koy-eristesi.description": "се готвят в сос от масло, мента, люспи червен пипер и магданоз, след което се гарнират с натрошено сирене и орехи.",
    "item.pasta.peynirli-edirne-koy-eristesi.review0.comment": "Прочутата юфка на Одрин, комбинацията от масло и сирене е перфектна.",
    "item.pasta.peynirli-edirne-koy-eristesi.review1.comment": "Има вкус на домашна юфка, комбинацията от орехи и сирене е страхотна.",
    "item.pasta.kiyma-el-acmasi-makarna.name": "Домашна паста с кайма",
    "item.pasta.kiyma-el-acmasi-makarna.description": "е вкусно ястие, приготвено с печена телешка кайма и прясна домашна паста. Добавя топло, домашно докосване към вашата маса.",
    "item.pasta.penne-alfredo.name": "Пене Алфредо",
    "item.pasta.penne-alfredo.description": "съчетава паста пене със сос Алфредо, приготвен от пилешко месо, сметана, гъби, пармезан и сос песто.",
    "item.pasta.penne-napoliten.name": "Пене Наполитен",
    "item.pasta.penne-napoliten.description": "съчетава паста пене с доматен сос с босилек и чесън, приготвен от летни домати, гарниран със зрял тракийски кашкавал.",

    // Burgers
    "item.burgers.la-strada-burger.name": "La Strada Burger",
    "item.burgers.la-strada-burger.description": "се приготвя от кайма от телешки ребра, сирене чедър, салата айсберг, кисели краставички, домати и хрупкави парченца лук. Този уникален бургер предлага богат и задоволителен вкус с всяка хапка.",
    "item.burgers.la-strada-crispy-burger.name": "La Strada Crispy Burger",
    "item.burgers.la-strada-crispy-burger.description": "има хрупкави пилешки бутчета, кисели краставички, маринован червен лук и домати. Този вкусен бургер предлага хрупкаво и свежо вкусово изживяване с всяка хапка.",
    "item.burgers.balkan-burger.name": "Balkan Burger",
    "item.burgers.balkan-burger.description": "носи вкусовете на Балканите на вашата маса със сос от печена червена чушка, домати, червен лук, хрупкави резени пастърма и кайма от телешки ребра. Този уникален бургер предлага богато и задоволително вкусово изживяване.",
    "item.burgers.balkan-burger.review0.comment": "Великолепен вкус с пастърма и сос от печени чушки.",
    "item.burgers.balkan-burger.review1.comment": "Страхотна идея, съчетаваща балкански вкусове с бургер, много вкусно.",

    // Desserts
    "item.desserts.cup-dondurma.name": "Сладолед в чаша",
    "item.desserts.cup-dondurma.description": "е възхитителна сладоледена феерия с вафла и пресни плодове! Този вкусен сладолед предлага освежаващо и сладко удоволствие.",
    "item.desserts.trilece.name": "Трилече",
    "item.desserts.trilece.description": "е прочутият карамелен тримлечен сладкиш от Балканите. Със своята мека текстура и богат млечен аромат, той предлага сладък взрив от вкус с всяка хапка.",
    "item.desserts.karamelli-affogato.name": "Карамелено Афогато",
    "item.desserts.karamelli-affogato.description": "е великолепен десерт с основа от кекс, сладолед, еспресо, шоколадови стърготини, орехи и карамелен сос.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.name": "Печена одринска сиренева халва",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.description": "се приготвя по традиционна рецепта и се сервира с опция за сладолед. Всяка хапка предлага уникален вкус.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review0.comment": "Страхотно е да намериш прочутата одринска сиренева халва тук, перфектно приготвена.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review1.comment": "Сервирането със сладолед е страхотна идея, перфектна хармония.",
    "item.desserts.brownie.name": "Брауни",
    "item.desserts.brownie.description": "се сервира интензивно шоколадово с опция за сладолед. Насладете се на шоколадова феерия с всяка хапка, отличаваща се с топла и мека текстура.",
    "item.desserts.fistikli-havuc-dilim-baklava.name": "Баклава с шамфъстък",
    "item.desserts.fistikli-havuc-dilim-baklava.description": "ще зарадва небцето ви със своята хрупкава текстура и интензивен вкус на шамфъстък във всяка хапка.",

    // Drinks
    // Coffee
    "item.drinks.turk-kahvesi.name": "Турско Кафе",
    "item.drinks.turk-kahvesi.description": "Традиционно турско кафе, сервирано без захар, средно сладко или сладко по желание.",
    "item.drinks.espresso.name": "Еспресо",
    "item.drinks.espresso.description": "Интензивно италианско еспресо.",
    "item.drinks.double-espresso.name": "Двойно Еспресо",
    "item.drinks.double-espresso.description": "Двойна доза еспресо.",
    "item.drinks.americano.name": "Американо",
    "item.drinks.americano.description": "Приготвено с еспресо и гореща вода.",
    "item.drinks.latte.name": "Лате",
    "item.drinks.latte.description": "Приготвено с еспресо и мляко на пара.",
    "item.drinks.cappuccino.name": "Капучино",
    "item.drinks.cappuccino.description": "Приготвено с еспресо, мляко на пара и млечна пяна.",
    "item.drinks.sicak-cikolata.name": "Горещ Шоколад",
    "item.drinks.sicak-cikolata.description": "Топла напитка с интензивен шоколадов вкус.",
    "item.drinks.salep.name": "Салеп",
    "item.drinks.salep.description": "Традиционна турска напитка, сервирана с канела.",
    "item.drinks.filter-coffee.name": "Филтър Кафе",
    "item.drinks.filter-coffee.description": "Приготвено от ежедневно смлени кафе зърна.",
    "item.drinks.sade-kahve.name": "Черно Кафе",
    "item.drinks.sade-kahve.description": "Турско черно кафе.",
    "item.drinks.sutlu-kahve.name": "Кафе с Мляко",
    "item.drinks.sutlu-kahve.description": "Турско кафе с мляко.",
    "item.drinks.soguk-kahve.name": "Студено Кафе (Cold Brew)",
    "item.drinks.soguk-kahve.description": "Ледено студено кафе.",
    "item.drinks.frappe.name": "Фрапе",
    "item.drinks.frappe.description": "Гръцко пенливо студено кафе.",
    // Soft Drinks
    "item.drinks.cay.name": "Чай",
    "item.drinks.cay.description": "Традиционен турски чай.",
    "item.drinks.bitki-cayi.name": "Билков Чай",
    "item.drinks.bitki-cayi.description": "Различни билкови чайове (Липа, Салвия, Лайка, Зелен чай).",
    "item.drinks.su-small.name": "Вода (Малка)",
    "item.drinks.su-small.description": "Натурална изворна вода.",
    "item.drinks.su-large.name": "Вода (Голяма)",
    "item.drinks.su-large.description": "Натурална изворна вода.",
    "item.drinks.san-pellegrino.name": "Сан Пелегрино",
    "item.drinks.san-pellegrino.description": "Итаианска минерална вода.",
    "item.drinks.soda.name": "Сода (Минерална Вода)",
    "item.drinks.soda.description": "Обикновена или лимонова минерална вода.",
    "item.drinks.kola.name": "Кола",
    "item.drinks.kola.description": "Coca-Cola, Diet Coke, Coca-Cola Zero.",
    "item.drinks.ayran.name": "Айрян",
    "item.drinks.ayran.description": "Традиционна турска напитка от кисело мляко.",
    "item.drinks.meyve-suyu.name": "Сок",
    "item.drinks.meyve-suyu.description": "Портокал, череша, праскова, кайсия, ананас.",
    "item.drinks.limonata.name": "Лимонада",
    "item.drinks.limonata.description": "Домашна прясна лимонада.",
    "item.drinks.tonic.name": "Тоник",
    "item.drinks.tonic.description": "Schweppes Тоник.",
    "item.drinks.red-bull.name": "Ред Бул",
    "item.drinks.red-bull.description": "Енергийна напитка.",
    // Fresh Juices
    "item.drinks.portakal-suyu.name": "Портокалов Сок",
    "item.drinks.portakal-suyu.description": "Прясно изцеден портокалов сок.",
    "item.drinks.nar-suyu.name": "Сок от Нар",
    "item.drinks.nar-suyu.description": "Прясно изцеден сок от нар.",
    "item.drinks.elma-havuc-bal.name": "Ябълка Морков Мед",
    "item.drinks.elma-havuc-bal.description": "Прясно изцеден сок от ябълка и морков, подсладен с мед.",
  },
}

// Create provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("tr") // Default to Turkish

  // Load language preference from localStorage on client side
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "tr", "el", "bg"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext)
