"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

// Define available languages
export type Language = "en" | "tr" | "el" | "bg"

// Define language context type
type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
  isLoaded: boolean
}

// Create context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "tr", // Default to Turkish
  setLanguage: () => {},
  t: (key) => key,
  isLoaded: false
})

// Define translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    "app.name": "La Strada Restaurant",
    "app.hotel": "The Plaza Hotel Edirne",
    "app.selectLanguage": "Select Language",
    "app.search": "Search",
    "app.cart": "Cart",
    "app.menu": "Menu",
    "app.order": "Order",
    "app.processOrder": "Process Order",
    "app.orderSummary": "Order Summary",
    "app.subtotal": "Subtotal",
    "app.total": "Total",
    "app.tax": "Tax",
    "app.roomNumber": "Room Number",
    "app.tableNumber": "Table Number",
    "app.enterRoomOrTable": "Enter Room or Table Number",
    "app.notes": "Notes",
    "app.addNotes": "Add Notes",
    "app.back": "Back",
    "app.continue": "Continue",
    "app.orderConfirmation": "Order Confirmation",
    "app.orderSent": "Your order has been sent!",
    "app.orderNumber": "Order Number",
    "app.orderTime": "Order Time",
    "app.orderTotal": "Order Total",
    "app.newOrder": "New Order",
    "app.emptyCart": "Your cart is empty",
    "app.addItems": "Add Items",
    "app.add": "Add",
    "app.select": "Select",
    "app.addToCart": "Add to Cart",
    "app.details": "Details",
    "app.allergens": "Allergens",
    "app.reviews": "Reviews",
    "app.options": "Options",
    "app.portion": "Portion",
    "app.allergenInfo": "Allergen Information",
    "app.containsAllergens": "This product contains the following allergens",
    "app.allergenWarning": "If you have allergies, please inform the staff before ordering",
    "app.customerReviews": "Customer Reviews",
    "app.bestSeller": "Best Seller",

    // Categories
    "category.all": "All Menu",
    "category.breakfast": "Breakfast",
    "category.starters": "Starters & Appetizers",
    "category.salads": "Salads",
    "category.mainDishes": "Main Dishes",
    "category.pasta": "Pasta",
    "category.burgers": "Burgers",
    "category.desserts": "Desserts",
    "category.drinks": "Drinks",
    "category.spirits": "Spirits",
    "category.cocktails": "Cocktails",
    "category.beers": "Beers",
    "category.wines": "Wines",
    "category.extras": "Extras",

    // Allergens
    "allergen.contains": "Contains",
    "allergen.gluten": "Gluten",
    "allergen.dairy": "Dairy",
    "allergen.nuts": "Nuts",
    "allergen.eggs": "Eggs",
    "allergen.fish": "Fish",
    "allergen.shellfish": "Shellfish",
    "allergen.soy": "Soy",
    "allergen.wheat": "Wheat",
    "allergen.alcohol": "Alcohol",

    // Wine
    "wine.pairing": "Pairing",
    "wine.pairsWellWith": "This wine pairs well with",
    "wine.foodPairings": "Food Pairings",

    //  Breakfast (EN)
    "item.breakfast.continental-kahvalti.name": "Continental Breakfast",
    "item.breakfast.continental-kahvalti.description": "Edirne local white cheese, plain omelette, a kind of yellow cheese made of cow's milk, tomato, cucumber, pepper, olives, etc",
    "item.breakfast.serpme-kahvalti.name": "Mixed Breakfast",
    "item.breakfast.serpme-kahvalti.description": "In addition to continental breakfast, pan cake, sausage, salami, cookie, turkish bagels, etc",
    "item.breakfast.pankek-pastasi.name": "Pan Cake",
    "item.breakfast.pankek-pastasi.description": "3 pan cake and fruits in season",
    "item.breakfast.acik-bufe-kahvalti.name": "Open Buffet Breakfast",
    "item.breakfast.acik-bufe-kahvalti.description": "07:30am - 10:30am",
    "item.breakfast.omlet.name": "Omelette",
    "item.breakfast.omlet.description": "Plain, cheese, vegetable, aged-cheese, garlic sausages, sausage, fried meat",
    "item.breakfast.sahanda-goz-yumurta.name": "Fried Eggs",
    "item.breakfast.sahanda-goz-yumurta.description": "Freshly cooked fried eggs",
    "item.breakfast.menemen.name": "Spicy Turkish Omelette",
    "item.breakfast.menemen.description": "Cooking base prepared with village pepper and summer tomatoes, with 2 eggs..",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.name": "Double Cheese Toast on Sourdough Bread",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.description": "Sourdough toast bread, fresh thracian cheddar and home-made tomato paste with mixed olives, tomatoes and cucumbers",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.name": "Toast with Cheddar and Sausage on Sourdough Bread",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.description": "Sourdough toast bread, fresh thracian cheddar, beef sausage and home-made tomato paste with mixed olives, tomatoes and cucumbers",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.name": "Triple Cheese Toast on Sourdough Bread",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.description": "Sourdough toast, fresh thracian cheddar, edirne local cheese and thrace old cheddar with home-made tomato paste, mixed olives, tomatoes and cucumbers",
    "item.breakfast.akitma.name": "Akıtma (Thracian Style Crepe)",
    "item.breakfast.akitma.description": "Thracian style crepe with edirne white cheese, organic blackberry jam, tomato, cucumber and olives",
    "item.breakfast.cicipapa.name": "Cicipapa",
    "item.breakfast.cicipapa.description": "Four slices of egg bread, served with Edirne white cheese, fresh kashar, homemade walnut acuka sauce, tomato, cucumber, and green pepper",

    // Starters (EN)
    "item.starters.trakya-koy-tarhanasi.name": "Thracian Village Tarhana Soup",
    "item.starters.trakya-koy-tarhanasi.description": "Prepared with natural ingredients, a heartwarming flavor. Leaves an unforgettable taste with Edirne white cheese and toasted village bread.",
    "item.starters.zeytinyagli-aysekadin-fasulye.name": "Green Beans in Olive Oil",
    "item.starters.zeytinyagli-aysekadin-fasulye.description": "A light and healthy Aegean flavor decorated with lemon and dill.",
    "item.starters.caciki.name": "Caciki (Tzatziki)",
    "item.starters.caciki.description": "The perfect harmony of yogurt, cucumber, garlic - olive oil prepared Greek style. Adds flavor to your table as a refreshing and light appetizer.",
    "item.starters.caciki.review0.comment": "Amazing caciki! Garlic ratio is just right, very refreshing.",
    "item.starters.caciki.review1.comment": "Made Greek style, really delicious.",
    "item.starters.caciki.review2.comment": "Very fresh and tasty, goes great with bread.",
    "item.starters.saksuka.name": "Shakshuka",
    "item.starters.saksuka.description": "The unique harmony of fried eggplant, pepper, and tomato sauce. This mildly spicy and flavorful Mediterranean appetizer will add color to your table.",
    "item.starters.trakya-mamzana.name": "Thracian Mamzana",
    "item.starters.trakya-mamzana.description": "This unique flavor, created by combining roasted eggplant, pepper, and onion with garlic yogurt, brings the authentic taste of Thrace to your table.",
    "item.starters.atom-haydari.name": "Atom Haydari",
    "item.starters.atom-haydari.description": "This delicious appetizer, prepared with crispy Edirne peppers on garlic yogurt, appeals to both the eyes and the palate.",
    "item.starters.guvecte-manda-yogurdu.name": "Buffalo Yogurt in Clay Pot",
    "item.starters.guvecte-manda-yogurdu.description": "Natural and delicious buffalo yogurt fermented in clay pots. Adds a unique taste to your table with its thick consistency and rich aroma.",
    "item.starters.karpuz-peynir.name": "Watermelon and Cheese",
    "item.starters.karpuz-peynir.description": "Refreshing watermelon slices meet fresh white cheese. This classic duo, indispensable in summer, is a refreshing and flavorful snack.",
    "item.starters.soka-kaymakli-biber-tursusu.name": "Soka Pickled Peppers with Cream",
    "item.starters.soka-kaymakli-biber-tursusu.description": "The famous pickled peppers with cheese and cream from Thrace and the Balkans. Adds a refreshing touch to your table with its unique flavor.",
    "item.starters.soka-kaymakli-biber-tursusu.review0.comment": "I didn't think I could find the Balkan flavor here. Amazing taste!",
    "item.starters.soka-kaymakli-biber-tursusu.review1.comment": "Perfect for those missing Edirne, the harmony of cream and pickle is magnificent.",
    "item.starters.tereyagli-kasarli-mantar.name": "Mushrooms with Butter and Cheese",
    "item.starters.tereyagli-kasarli-mantar.description": "Cultivated, oyster, and sarıkız mushrooms cooked in their own juice, with gratin Thracian fresh cheddar on top.",
    "item.starters.tereyagli-soganli-yaprak-ciger.name": "Leaf Liver with Butter and Onion",
    "item.starters.tereyagli-soganli-yaprak-ciger.description": "Veal leaf liver sautéed with onion and butter. A traditional flavor with its soft texture and rich aroma.",
    "item.starters.pacanga-boregi.name": "Pacanga Pastry",
    "item.starters.pacanga-boregi.description": "Prepared with pastrami, fresh cheddar, tomato, and pepper. A hot and flavorful start with the harmony of its ingredients and crispy exterior.",
    "item.starters.pacanga-boregi.review0.comment": "A great snack with its crispy exterior and delicious interior.",
    "item.starters.pacanga-boregi.review1.comment": "The harmony of pastrami and cheese is perfect, I will order again.",
    "item.starters.patates-kizartmasi.name": "French Fries",
    "item.starters.patates-kizartmasi.description": "Golden and crispy french fries, with optional cheese. A classic flavor enjoyable in every bite.",
    "item.starters.ev-yapimi-patates-kizartmasi.name": "Homemade French Fries",
    "item.starters.ev-yapimi-patates-kizartmasi.description": "Crispy homemade french fries, with optional cheese. A warm and satisfying flavor.",
    "item.starters.kizartma-sepeti.name": "Fried Platter",
    "item.starters.kizartma-sepeti.description": "A flavorful variety consisting of french fries, halloumi, onion rings, sausage, chicken fingers, and cheeseburger borek.",
    "item.starters.sarkuteri-tahtasi.name": "Charcuterie Board",
    "item.starters.sarkuteri-tahtasi.description": "This exquisite charcuterie board, prepared with local meats, cheeses, and fruits, offers a different taste experience in every bite.",

    // Items - Salads (EN)
    "item.salads.bruschetta.name": "Bruschetta",
    "item.salads.bruschetta.description": "is prepared with garlic-toasted bread slices topped with tomatoes in pesto sauce, cheese, and basil. A light and refreshing Italian classic.",
    "item.salads.yesil-salata.name": "Green Salad",
    "item.salads.yesil-salata.description": "is a mix of Mediterranean greens served with a mustard olive oil dressing. This fresh and light salad is ideal for those seeking a healthy option.",
    "item.salads.peynirli-yesil-salata.name": "Cheese Green Salad",
    "item.salads.peynirli-yesil-salata.description": "is served with cheese, a mix of Mediterranean greens, and mustard olive oil dressing. This healthy, and flavorful salad will delight your palate.",
    "item.salads.roka-salata.name": "Rocket Salad",
    "item.salads.roka-salata.description": "is prepared with rocket, sun-dried tomatoes, balsamic dressing, and grated Trakya aged kashar cheese.",
    "item.salads.shopska-salata.name": "Shopska Salata",
    "item.salads.shopska-salata.description": "is prepared with tomatoes, onions, cucumbers, peppers, parsley, olives, and grated white cheese. Served with toasted sourdough bread.",
    "item.salads.shopska-salata.review0.comment": "A different presentation than the ones I had in Bulgaria, well done",
    "item.salads.shopska-salata.review1.comment": "It was very delicious",
    "item.salads.istanbul-salata.name": "İstanbul Salad",
    "item.salads.istanbul-salata.description": "is prepared with tomatoes, red onions, fresh thyme, and croutons. Crowned with a balsamic tomato dressing.",
    "item.salads.sezar-salata.name": "Caesar Salad",
    "item.salads.sezar-salata.description": "is prepared with crispy iceberg lettuce and marinated chicken, Caesar dressing, garlic croutons, and Parmesan cheese.",
    "item.salads.ananas-ve-buzlu-badem-salatasi.name": "Pineapple And Iced Almond Salad",
    "item.salads.ananas-ve-buzlu-badem-salatasi.description": "is a fresh mix of Mediterranean greens, pineapple slices, almonds, and balsamic dressing, offering a tropical flavour.",

    // Main Dishes
    "item.mainDishes.edirne-koftesi.name": "Edirne Meatballs",
    "item.mainDishes.edirne-koftesi.description": "Regionally famous Edirne meatballs, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.name": "Keşan Butcher's Meatballs",
    "item.mainDishes.kesan-satir-kofte.description": "Special butcher's meatballs made with the traditional Keşan cleaver technique, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.review0.comment": "The cleaver technique really makes a difference, delicious!",
    "item.mainDishes.kesan-satir-kofte.review1.comment": "Best meatballs I've had in Edirne.",
    "item.mainDishes.bosnak-kofte.name": "Bosnian Meatballs",
    "item.mainDishes.bosnak-kofte.description": "Traditional Bosnian meatballs (pljeskavica) served with pita bread, ajvar, onions, and potatoes.",
    "item.mainDishes.bosnak-kofte.review0.comment": "Authentic Balkan taste, just like homemade.",
    "item.mainDishes.bosnak-kofte.review1.comment": "Very generous portion and great flavor.",
    "item.mainDishes.izgara-kasap-sucugu.name": "Grilled Butcher's Sausage",
    "item.mainDishes.izgara-kasap-sucugu.description": "Flavorful grilled butcher's sausage, served with roasted peppers, onions, and rice.",
    "item.mainDishes.izgara-tavuk-sis.name": "Grilled Chicken Skewers",
    "item.mainDishes.izgara-tavuk-sis.description": "Tender grilled chicken skewers, served with roasted peppers, onions, and rice.",
    "item.mainDishes.pilic-kulbasti.name": "Chicken Külbastı",
    "item.mainDishes.pilic-kulbasti.description": "Grilled chicken fillet marinated in yogurt and spices, served with roasted peppers, onions, and rice.",
    "item.mainDishes.tavuk-schnitzel.name": "Chicken Schnitzel",
    "item.mainDishes.tavuk-schnitzel.description": "Breaded and fried chicken cutlet, served with french fries and lemon.",
    "item.mainDishes.tereyagli-dana-bonfile.name": "Butter Beef Tenderloin",
    "item.mainDishes.tereyagli-dana-bonfile.description": "Juicy beef tenderloin cooked in butter, served with grilled vegetables.",
    "item.mainDishes.antrikot-sis.name": "Ribeye Skewers",
    "item.mainDishes.antrikot-sis.description": "Marinated ribeye skewers, grilled to perfection, served with roasted peppers, onions, and rice.",
    "item.mainDishes.antrikot-sis.review0.comment": "The meat was incredibly tender and flavorful.",
    "item.mainDishes.antrikot-sis.review1.comment": "A must-try for meat lovers!",
    "item.mainDishes.coban-kavurma.name": "Shepherd's Sauté",
    "item.mainDishes.coban-kavurma.description": "Diced beef sautéed with onions, tomatoes, and peppers, served with rice.",
    "item.mainDishes.kuzu-tandir.name": "Lamb Tandoori",
    "item.mainDishes.kuzu-tandir.description": "Slow-cooked lamb tandoori, tender and flavorful, served with rice and grilled vegetables.",

    // Pasta
    "item.pasta.peynirli-edirne-koy-eristesi.name": "Edirne Noodles",
    "item.pasta.peynirli-edirne-koy-eristesi.description": "are cooked in a sauce of butter, mint, red pepper flakes, and parsley, then crowned with crumbled cheese and walnuts.",
    "item.pasta.peynirli-edirne-koy-eristesi.review0.comment": "Edirne's famous noodles, the combination of butter and cheese is perfect.",
    "item.pasta.peynirli-edirne-koy-eristesi.review1.comment": "Tastes like homemade noodles, the walnut and cheese combination is great.",
    "item.pasta.kiyma-el-acmasi-makarna.name": "Homemade Minced Meat Pasta",
    "item.pasta.kiyma-el-acmasi-makarna.description": "is a delicious dish made with roasted ground beef and fresh homemade pasta. It adds a warm, homemade touch to your table.",
    "item.pasta.penne-alfredo.name": "Penne Alfredo",
    "item.pasta.penne-alfredo.description": "brings together penne pasta with Alfredo sauce made from chicken, cream, mushrooms, Parmesan, and pesto sauce.",
    "item.pasta.penne-napoliten.name": "Penne Napoliten",
    "item.pasta.penne-napoliten.description": "combines penne pasta with a basil and garlic tomato sauce made from summer tomatoes, topped with Thrace aged kashar cheese.",

    // Burgers
    "item.burgers.la-strada-burger.name": "La Strada Burger",
    "item.burgers.la-strada-burger.description": "is made of ground beef ribs, cheddar cheese, iceberg lettuce, pickles, tomatoes, and crispy onion pieces. This unique burger offers a rich and satisfying flavour with every bite.",
    "item.burgers.la-strada-crispy-burger.name": "La Strada Crispy Burger",
    "item.burgers.la-strada-crispy-burger.description": "has crispy chicken thighs, pickles, pickled red onions, and tomatoes. This delicious burger offers a crispy and fresh flavour experience with every bite.",
    "item.burgers.balkan-burger.name": "Balkan Burger",
    "item.burgers.balkan-burger.description": "brings the flavours of the Balkans to your table with roasted red pepper sauce, tomatoes, red onions, crispy pastrami slices, and ground beef ribs. This unique burger offers a rich and satisfying taste experience.",
    "item.burgers.balkan-burger.review0.comment": "A magnificent flavor with pastrami and roasted pepper sauce.",
    "item.burgers.balkan-burger.review1.comment": "A great idea combining Balkan flavors with a burger, very tasty.",

    // Desserts
    "item.desserts.cup-dondurma.name": "Cup Dondurma",
    "item.desserts.cup-dondurma.description": "is a delightful ice cream extravaganza with wafer and fresh fruits! This delicious ice cream offers a refreshing and sweet treat.",
    "item.desserts.trilece.name": "Trileçe",
    "item.desserts.trilece.description": "is the famous caramel three-milk cake from the Balkans. With its soft texture and rich milk aroma, it offers a sweet explosion of flavor with every bite.",
    "item.desserts.karamelli-affogato.name": "Caramel Affogato",
    "item.desserts.karamelli-affogato.description": "is a magnificent dessert with a cake base, ice cream, espresso, chocolate chips, walnuts, and caramel sauce.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.name": "Baked Edirne Cheese Halva",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.description": "is prepared with a traditional recipe and served with an option of ice cream. Each bite offers a unique flavour.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review0.comment": "It's great to find Edirne's famous cheese halva here, perfectly cooked.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review1.comment": "Serving it with ice cream is a great idea, perfect harmony.",
    "item.desserts.brownie.name": "Brownie",
    "item.desserts.brownie.description": "is served intensely chocolatey with an option of ice cream. Enjoy a chocolate extravaganza with every bite, featuring a warm and soft texture.",
    "item.desserts.fistikli-havuc-dilim-baklava.name": "Baklava with Pistachio",
    "item.desserts.fistikli-havuc-dilim-baklava.description": "will delight your palate with its crispy texture and intense pistachio flavour in every bite.",

    // Drinks
    // Coffee
    "item.drinks.turk-kahvesi.name": "Turkish Coffee",
    "item.drinks.turk-kahvesi.description": "Traditional Turkish coffee, served plain, medium, or sweet upon request.",
    "item.drinks.espresso.name": "Espresso",
    "item.drinks.espresso.description": "Intense Italian espresso.",
    "item.drinks.double-espresso.name": "Double Espresso",
    "item.drinks.double-espresso.description": "Double shot of espresso.",
    "item.drinks.americano.name": "Americano",
    "item.drinks.americano.description": "Prepared with espresso and hot water.",
    "item.drinks.latte.name": "Latte",
    "item.drinks.latte.description": "Prepared with espresso and steamed milk.",
    "item.drinks.cappuccino.name": "Cappuccino",
    "item.drinks.cappuccino.description": "Prepared with espresso, steamed milk, and milk foam.",
    "item.drinks.sicak-cikolata.name": "Hot Chocolate",
    "item.drinks.sicak-cikolata.description": "Hot beverage with intense chocolate flavor.",
    "item.drinks.salep.name": "Salep",
    "item.drinks.salep.description": "Traditional Turkish drink, served with cinnamon.",
    "item.drinks.filter-coffee.name": "Filter Coffee",
    "item.drinks.filter-coffee.description": "Prepared from daily ground coffee beans.",
    "item.drinks.sade-kahve.name": "Black Coffee",
    "item.drinks.sade-kahve.description": "Turkish style black coffee.",
    "item.drinks.sutlu-kahve.name": "Coffee with Milk",
    "item.drinks.sutlu-kahve.description": "Turkish style coffee with milk.",
    "item.drinks.soguk-kahve.name": "Cold Brew",
    "item.drinks.soguk-kahve.description": "Iced cold coffee.",
    "item.drinks.frappe.name": "Frappe",
    "item.drinks.frappe.description": "Greek style foamy cold coffee.",
    // Soft Drinks
    "item.drinks.cay.name": "Tea",
    "item.drinks.cay.description": "Traditional Turkish tea.",
    "item.drinks.bitki-cayi.name": "Herbal Tea",
    "item.drinks.bitki-cayi.description": "Various herbal teas (Linden, Sage, Chamomile, Green Tea).",
    "item.drinks.su-small.name": "Water (Small)",
    "item.drinks.su-small.description": "Natural spring water.",
    "item.drinks.su-large.name": "Water (Large)",
    "item.drinks.su-large.description": "Natural spring water.",
    "item.drinks.san-pellegrino.name": "San Pellegrino",
    "item.drinks.san-pellegrino.description": "Italian mineral water.",
    "item.drinks.soda.name": "Mineral Water",
    "item.drinks.soda.description": "Plain or lemon mineral water.",
    "item.drinks.kola.name": "Coke",
    "item.drinks.kola.description": "Coca-Cola, Diet Coke, Coca-Cola Zero.",
    "item.drinks.ayran.name": "Ayran",
    "item.drinks.ayran.description": "Traditional Turkish yogurt drink.",
    "item.drinks.meyve-suyu.name": "Juice",
    "item.drinks.meyve-suyu.description": "Orange, cherry, peach, apricot, pineapple.",
    "item.drinks.limonata.name": "Lemonade",
    "item.drinks.limonata.description": "Homemade fresh lemonade.",
    "item.drinks.tonic.name": "Tonic",
    "item.drinks.tonic.description": "Schweppes Tonic Water.",
    "item.drinks.red-bull.name": "Red Bull",
    "item.drinks.red-bull.description": "Energy drink.",
    // Fresh Juices
    "item.drinks.portakal-suyu.name": "Orange Juice",
    "item.drinks.portakal-suyu.description": "Freshly squeezed orange juice.",
    "item.drinks.nar-suyu.name": "Pomegranate Juice",
    "item.drinks.nar-suyu.description": "Freshly squeezed pomegranate juice.",
    "item.drinks.elma-havuc-bal.name": "Apple Carrot Honey",
    "item.drinks.elma-havuc-bal.description": "Freshly squeezed apple and carrot juice, sweetened with honey.",
  },
  tr: {
    // Common
    "app.name": "La Strada Restaurant",
    "app.hotel": "The Plaza Hotel Edirne",
    "app.selectLanguage": "Dil Seçin",
    "app.search": "Ara",
    "app.cart": "Sepet",
    "app.menu": "Menü",
    "app.order": "Sipariş",
    "app.processOrder": "Siparişi Tamamla",
    "app.orderSummary": "Sipariş Özeti",
    "app.subtotal": "Ara Toplam",
    "app.total": "Toplam",
    "app.tax": "Vergi",
    "app.roomNumber": "Oda Numarası",
    "app.tableNumber": "Masa Numarası",
    "app.enterRoomOrTable": "Oda veya Masa Numarası Girin",
    "app.notes": "Notlar",
    "app.addNotes": "Not Ekle",
    "app.back": "Geri",
    "app.continue": "Devam",
    "app.orderConfirmation": "Sipariş Onayı",
    "app.orderSent": "Siparişiniz gönderildi!",
    "app.orderNumber": "Sipariş Numarası",
    "app.orderTime": "Sipariş Zamanı",
    "app.orderTotal": "Sipariş Toplamı",
    "app.newOrder": "Yeni Sipariş",
    "app.emptyCart": "Sepetiniz boş",
    "app.addItems": "Ürün Ekle",
    "app.add": "Ekle",
    "app.select": "Seç",
    "app.addToCart": "Sepete Ekle",
    "app.details": "Detaylar",
    "app.allergens": "Alerjenler",
    "app.reviews": "Yorumlar",
    "app.options": "Seçenekler",
    "app.portion": "Porsiyon",
    "app.allergenInfo": "Alerjen Bilgisi",
    "app.containsAllergens": "Bu üründe aşağıdaki alerjenler bulunmaktadır",
    "app.allergenWarning": "Alerjiniz varsa lütfen sipariş vermeden önce personele bildiriniz",
    "app.customerReviews": "Müşteri Yorumları",
    "app.bestSeller": "En Çok Satan",

    // Categories
    "category.all": "Tüm Menü",
    "category.breakfast": "Kahvaltı",
    "category.starters": "Başlangıçlar ve Mezeler",
    "category.salads": "Salatalar",
    "category.mainDishes": "Ana Yemekler",
    "category.pasta": "Makarnalar",
    "category.burgers": "Hamburgerler",
    "category.desserts": "Tatlılar",
    "category.drinks": "İçecekler",
    "category.spirits": "Yüksek Alkollü İçecekler",
    "category.cocktails": "Kokteyller",
    "category.beers": "Biralar",
    "category.wines": "Şaraplar",
    "category.extras": "Ekstralar",

    // Allergens
    "allergen.contains": "İçerir",
    "allergen.gluten": "Gluten",
    "allergen.dairy": "Süt Ürünleri",
    "allergen.nuts": "Kuruyemiş",
    "allergen.eggs": "Yumurta",
    "allergen.fish": "Balık",
    "allergen.shellfish": "Kabuklu Deniz Ürünleri",
    "allergen.soy": "Soya",
    "allergen.wheat": "Buğday",
    "allergen.alcohol": "Alkol",

    // Wine
    "wine.pairing": "Eşleşme",
    "wine.pairsWellWith": "Bu şarap şu yemeklerle iyi eşleşir",
    "wine.foodPairings": "Yemek Eşleşmeleri",

    //  Breakfast (TR)
    "item.breakfast.continental-kahvalti.name": "Continental Kahvaltı",
    "item.breakfast.continental-kahvalti.description": "Edirne beyaz peyniri, sade omlet, kaşar, domates, salatalık, biber, zeytin, vs..",
    "item.breakfast.serpme-kahvalti.name": "Serpme Kahvaltı",
    "item.breakfast.serpme-kahvalti.description": "Continental kahvaltıya ek olarak pankek, sosis, salam, kurabiye, simit, vs..",
    "item.breakfast.pankek-pastasi.name": "Pankek Pastası",
    "item.breakfast.pankek-pastasi.description": "3 adet pankek ve mevsim meyveleri",
    "item.breakfast.acik-bufe-kahvalti.name": "Açık Büfe Kahvaltı",
    "item.breakfast.acik-bufe-kahvalti.description": "07:30 - 10:30 saatleri arası",
    "item.breakfast.omlet.name": "Omlet",
    "item.breakfast.omlet.description": "Sade, peynirli, sebzeli, kaşarlı, sucuklu, sosisli, kavurmalı",
    "item.breakfast.sahanda-goz-yumurta.name": "Sahanda Göz Yumurta",
    "item.breakfast.sahanda-goz-yumurta.description": "Taze pişirilmiş göz yumurta",
    "item.breakfast.menemen.name": "Menemen",
    "item.breakfast.menemen.description": "Köy biberi ve yaz domatesiyle hazırlanmış menemen harcı, 2 yumurta ile..",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.name": "Ekşi Mayalı Ekmeğe Çift Kaşarlı Tost",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.description": "Ekşi mayalı kare tost ekmeği, trakya taze kaşarı ve yanında ev salçası, karışık zeytin, domates salatalık ile",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.name": "Ekşi Mayalı Ekmeğe Kaşarlı Sucuklu Tost",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.description": "Ekşi mayalı kare tost ekmeği, trakya taze kaşarı, dana sucuğu ve yanında ev salçası, karışık zeytin, domates salatalık ile",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.name": "Ekşi Mayalı Ekmeğe 3 Peynirli Tost",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.description": "Ekşi mayalı kare tost ekmeği, trakya taze kaşarı, edirne beyaz peyniri ve trakya eski kaşarı yanında ev salçası, karışık zeytin, domates salatalık ile",
    "item.breakfast.akitma.name": "Akıtma (Trakya Usulü Krep)",
    "item.breakfast.akitma.description": "Trakya usulü krep, yanında edirne beyaz peyniri, organik böğürtlen reçeli, domates salatalık ve zeytin ile",
    "item.breakfast.cicipapa.name": "Cicipapa",
    "item.breakfast.cicipapa.description": "4 dilim yumurtalı ekmek, edirne beyaz peynir ve taze kaşarı, ev yapımı cevizli acuka sos, domates, salatalık sivri biber",

    // Starters (TR)
    "item.starters.trakya-koy-tarhanasi.name": "Trakya Köy Tarhanası",
    "item.starters.trakya-koy-tarhanasi.description": "Doğal malzemelerle hazırlanmış, iç ısıtan bir lezzet. Edirne beyaz peyniri ve kızarmış köy ekmeği ile damaklarda unutulmaz bir tat bırakır.",
    "item.starters.zeytinyagli-aysekadin-fasulye.name": "Zeytinyağlı Ayşekadın Fasulye",
    "item.starters.zeytinyagli-aysekadin-fasulye.description": "Limon ve dereotu ile süslenen hafif ve sağlıklı bir Ege lezzeti.",
    "item.starters.caciki.name": "Caciki (Tzatziki)",
    "item.starters.caciki.description": "Yoğurt, salatalık, sarımsak - zeytinyağının mükemmel uyumu, Yunan tarzında hazırlanmış. Ferahlatıcı ve hafif bir aperatif olarak masanıza lezzet katar.",
    "item.starters.caciki.review0.comment": "Harika bir cacıki! Sarımsak oranı tam kıvamında, çok ferahlatıcı.",
    "item.starters.caciki.review1.comment": "Yunan usulü yapılmış, gerçekten çok lezzetli.",
    "item.starters.caciki.review2.comment": "Çok taze ve lezzetli, yanında ekmekle harika gidiyor.",
    "item.starters.saksuka.name": "Şakşuka",
    "item.starters.saksuka.description": "Kızartılmış patlıcan, biber ve domates sosunun eşsiz uyumu. Hafif acı ve lezzet dolu bu Akdeniz mezesi, sofralarınıza renk katacak.",
    "item.starters.trakya-mamzana.name": "Trakya Mamzana",
    "item.starters.trakya-mamzana.description": "Közlenmiş patlıcan, biber ve soğan, sarımsaklı yoğurt ile birleşerek oluşturulan bu eşsiz lezzet, Trakya'nın otantik tadını sofralarınıza getiriyor.",
    "item.starters.atom-haydari.name": "Atom Haydari",
    "item.starters.atom-haydari.description": "Sarımsaklı yoğurt üzerine çıtır Edirne biberleriyle hazırlanan bu lezzetli meze, hem gözlere hem de damaklara hitap eder.",
    "item.starters.guvecte-manda-yogurdu.name": "Güveçte Manda Yoğurdu",
    "item.starters.guvecte-manda-yogurdu.description": "Toprak güveçlerde mayalandırılmış, doğal ve lezzetli manda yoğurdu. Yoğun kıvamı ve zengin aromasıyla sofralarınıza eşsiz bir tat katıyor.",
    "item.starters.karpuz-peynir.name": "Karpuz Peynir",
    "item.starters.karpuz-peynir.description": "Serinletici karpuz dilimleri, taze beyaz peynirle buluşuyor. Yazın vazgeçilmezi olan bu klasik ikili, ferahlatıcı ve lezzet dolu bir atıştırmalık.",
    "item.starters.soka-kaymakli-biber-tursusu.name": "Soka Kaymaklı Biber Turşusu",
    "item.starters.soka-kaymakli-biber-tursusu.description": "Trakya ve Balkanların meşhur peynirli ve kaymaklı biber turşusu. Eşsiz lezzetiyle sofralarınıza ferahlatıcı bir dokunuş katıyor.",
    "item.starters.soka-kaymakli-biber-tursusu.review0.comment": "Balkan lezzetini burada bulabileceğimi düşünmemiştim. Harika bir tat!",
    "item.starters.soka-kaymakli-biber-tursusu.review1.comment": "Edirne'yi özleyenler için mükemmel, kaymak ve turşunun uyumu harika.",
    "item.starters.tereyagli-kasarli-mantar.name": "Tereyağlı Kaşarlı Mantar",
    "item.starters.tereyagli-kasarli-mantar.description": "Kendi suyunda pişmiş kültür, istiridye ve sarıkız mantarları, üzerinde graten Trakya taze kaşarı ile.",
    "item.starters.tereyagli-soganli-yaprak-ciger.name": "Tereyağlı Soğanlı Yaprak Ciğer",
    "item.starters.tereyagli-soganli-yaprak-ciger.description": "Soğan ve tereyağ ile sotelenmiş dana yaprak ciğer. Yumuşak dokusu ve zengin aromasıyla, geleneksel bir lezzet.",
    "item.starters.pacanga-boregi.name": "Paçanga Böreği",
    "item.starters.pacanga-boregi.description": "Pastırma, taze kaşar, domates ve biber ile hazırlanır. İçindeki malzemelerin uyumu ve çıtır dışıyla, sıcak ve lezzet dolu bir başlangıç.",
    "item.starters.pacanga-boregi.review0.comment": "A great snack with its crispy exterior and delicious interior.",
    "item.starters.pacanga-boregi.review1.comment": "The harmony of pastrami and cheese is perfect, I will order again.",
    "item.starters.patates-kizartmasi.name": "Patates Kızartması",
    "item.starters.patates-kizartmasi.description": "Altın sarısı ve çıtır patates kızartmaları, isteğe bağlı peynir seçeneği ile. Her lokmada keyif veren klasik bir lezzet.",
    "item.starters.ev-yapimi-patates-kizartmasi.name": "Ev Yapımı Patates Kızartması",
    "item.starters.ev-yapimi-patates-kizartmasi.description": "Çıtır çıtır ev yapımı patates kızartması, isteğe bağlı peynir seçeneği ile. Sıcacık ve doyurucu bir lezzet.",
    "item.starters.kizartma-sepeti.name": "Kızartma Sepeti",
    "item.starters.kizartma-sepeti.description": "Patates kızartması, hellim, soğan halkası, sosis, finger tavuk ve cheeseburger börekten oluşan lezzet dolu bir çeşitlilik.",
    "item.starters.sarkuteri-tahtasi.name": "Şarküteri Tahtası",
    "item.starters.sarkuteri-tahtasi.description": "Yöresel et, peynir ve meyveler ile hazırlanan bu enfes şarküteri tahtası, her lokmada farklı bir lezzet deneyimi sunar.",

    // Items - Salads (TR)
    "item.salads.bruschetta.name": "Bruschetta",
    "item.salads.bruschetta.description": "sarımsaklı kızarmış ekmek dilimleri, üzerinde pesto soslu domates, peynir ve fesleğen ile hazırlanır. Hafif ve ferahlatıcı bir İtalyan klasiği.",
    "item.salads.yesil-salata.name": "Yeşil Salata",
    "item.salads.yesil-salata.description": "karışık Akdeniz yeşillikleri, hardallı zeytinyağı sos ile servis edilir. Taze ve hafif bu salata, sağlıklı bir seçenek arayanlar için idealdir.",
    "item.salads.peynirli-yesil-salata.name": "Peynirli Yeşil Salata",
    "item.salads.peynirli-yesil-salata.description": "edirne peyniri, karışık Akdeniz yeşillikleri ve hardallı zeytinyağı sos ile servis edilir. Sağlıklı ve lezzet dolu bu salata, damaklarınızı şenlendirecek.",
    "item.salads.roka-salata.name": "Roka Salata",
    "item.salads.roka-salata.description": "roka, kuru domates, balzamik sos ve traşlanmış Trakya Eski Kaşarı ile hazırlanır.",
    "item.salads.shopska-salata.name": "Shopska Salata",
    "item.salads.shopska-salata.description": "domates, soğan, salatalık, biber, maydanoz, zeytin ve rende beyaz peynir ile hazırlanır. Kızarmış ekşi maya ekmeği, yağı ve limon sos ile..",
    "item.salads.shopska-salata.review0.comment": "Bulgaristan'da yediklerimden daha farklı bir sunum, tebrikler",
    "item.salads.shopska-salata.review1.comment": "Çok lezizdi",
    "item.salads.istanbul-salata.name": "İstanbul Salata",
    "item.salads.istanbul-salata.description": "domates, kırmızı soğan, taze kekik ve kroton ile hazırlanır. Balzamikli domates sos ile taçlandırılan bu salata, taze lezzetleri sofranıza getirir.",
    "item.salads.sezar-salata.name": "Sezar Salata",
    "item.salads.sezar-salata.description": "çıtır iceberg marulu ve marine edilmiş tavuk etleri, sezar sos, sarımsaklı kıtır ekmek ve parmesan peyniri ile hazırlanır.",
    "item.salads.ananas-ve-buzlu-badem-salatasi.name": "Ananas ve Buzlu Badem Salatası",
    "item.salads.ananas-ve-buzlu-badem-salatasi.description": "karışık Akdeniz yeşiliği, ananas dilimleri, badem ve balzamikli sos ile hazırlanan bu taptaze salata, tropikal bir lezzet sunuyor.",

    // Main Dishes
    "item.mainDishes.edirne-koftesi.name": "Edirne Meatballs",
    "item.mainDishes.edirne-koftesi.description": "Regionally famous Edirne meatballs, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.name": "Keşan Butcher's Meatballs",
    "item.mainDishes.kesan-satir-kofte.description": "Special butcher's meatballs made with the traditional Keşan cleaver technique, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.review0.comment": "The cleaver technique really makes a difference, delicious!",
    "item.mainDishes.kesan-satir-kofte.review1.comment": "Best meatballs I've had in Edirne.",
    "item.mainDishes.bosnak-kofte.name": "Bosnian Meatballs",
    "item.mainDishes.bosnak-kofte.description": "Traditional Bosnian meatballs (pljeskavica) served with pita bread, ajvar, onions, and potatoes.",
    "item.mainDishes.bosnak-kofte.review0.comment": "Authentic Balkan taste, just like homemade.",
    "item.mainDishes.bosnak-kofte.review1.comment": "Very generous portion and great flavor.",
    "item.mainDishes.izgara-kasap-sucugu.name": "Grilled Butcher's Sausage",
    "item.mainDishes.izgara-kasap-sucugu.description": "Flavorful grilled butcher's sausage, served with roasted peppers, onions, and rice.",
    "item.mainDishes.izgara-tavuk-sis.name": "Grilled Chicken Skewers",
    "item.mainDishes.izgara-tavuk-sis.description": "Tender grilled chicken skewers, served with roasted peppers, onions, and rice.",
    "item.mainDishes.pilic-kulbasti.name": "Chicken Külbastı",
    "item.mainDishes.pilic-kulbasti.description": "Grilled chicken fillet marinated in yogurt and spices, served with roasted peppers, onions, and rice.",
    "item.mainDishes.tavuk-schnitzel.name": "Chicken Schnitzel",
    "item.mainDishes.tavuk-schnitzel.description": "Breaded and fried chicken cutlet, served with french fries and lemon.",
    "item.mainDishes.tereyagli-dana-bonfile.name": "Butter Beef Tenderloin",
    "item.mainDishes.tereyagli-dana-bonfile.description": "Juicy beef tenderloin cooked in butter, served with grilled vegetables.",
    "item.mainDishes.antrikot-sis.name": "Ribeye Skewers",
    "item.mainDishes.antrikot-sis.description": "Marinated ribeye skewers, grilled to perfection, served with roasted peppers, onions, and rice.",
    "item.mainDishes.antrikot-sis.review0.comment": "The meat was incredibly tender and flavorful.",
    "item.mainDishes.antrikot-sis.review1.comment": "A must-try for meat lovers!",
    "item.mainDishes.coban-kavurma.name": "Shepherd's Sauté",
    "item.mainDishes.coban-kavurma.description": "Diced beef sautéed with onions, tomatoes, and peppers, served with rice.",
    "item.mainDishes.kuzu-tandir.name": "Lamb Tandoori",
    "item.mainDishes.kuzu-tandir.description": "Slow-cooked lamb tandoori, tender and flavorful, served with rice and grilled vegetables.",

    // Pasta
    "item.pasta.peynirli-edirne-koy-eristesi.name": "Edirne Noodles",
    "item.pasta.peynirli-edirne-koy-eristesi.description": "are cooked in a sauce of butter, mint, red pepper flakes, and parsley, then crowned with crumbled cheese and walnuts.",
    "item.pasta.peynirli-edirne-koy-eristesi.review0.comment": "Edirne's famous noodles, the combination of butter and cheese is perfect.",
    "item.pasta.peynirli-edirne-koy-eristesi.review1.comment": "Tastes like homemade noodles, the walnut and cheese combination is great.",
    "item.pasta.kiyma-el-acmasi-makarna.name": "Homemade Minced Meat Pasta",
    "item.pasta.kiyma-el-acmasi-makarna.description": "is a delicious dish made with roasted ground beef and fresh homemade pasta. It adds a warm, homemade touch to your table.",
    "item.pasta.penne-alfredo.name": "Penne Alfredo",
    "item.pasta.penne-alfredo.description": "brings together penne pasta with Alfredo sauce made from chicken, cream, mushrooms, Parmesan, and pesto sauce.",
    "item.pasta.penne-napoliten.name": "Penne Napoliten",
    "item.pasta.penne-napoliten.description": "combines penne pasta with a basil and garlic tomato sauce made from summer tomatoes, topped with Thrace aged kashar cheese.",

    // Burgers
    "item.burgers.la-strada-burger.name": "La Strada Burger",
    "item.burgers.la-strada-burger.description": "is made of ground beef ribs, cheddar cheese, iceberg lettuce, pickles, tomatoes, and crispy onion pieces. This unique burger offers a rich and satisfying flavour with every bite.",
    "item.burgers.la-strada-crispy-burger.name": "La Strada Crispy Burger",
    "item.burgers.la-strada-crispy-burger.description": "has crispy chicken thighs, pickles, pickled red onions, and tomatoes. This delicious burger offers a crispy and fresh flavour experience with every bite.",
    "item.burgers.balkan-burger.name": "Balkan Burger",
    "item.burgers.balkan-burger.description": "brings the flavours of the Balkans to your table with roasted red pepper sauce, tomatoes, red onions, crispy pastrami slices, and ground beef ribs. This unique burger offers a rich and satisfying taste experience.",
    "item.burgers.balkan-burger.review0.comment": "A magnificent flavor with pastrami and roasted pepper sauce.",
    "item.burgers.balkan-burger.review1.comment": "A great idea combining Balkan flavors with a burger, very tasty.",

    // Desserts
    "item.desserts.cup-dondurma.name": "Cup Dondurma",
    "item.desserts.cup-dondurma.description": "is a delightful ice cream extravaganza with wafer and fresh fruits! This delicious ice cream offers a refreshing and sweet treat.",
    "item.desserts.trilece.name": "Trileçe",
    "item.desserts.trilece.description": "is the famous caramel three-milk cake from the Balkans. With its soft texture and rich milk aroma, it offers a sweet explosion of flavor with every bite.",
    "item.desserts.karamelli-affogato.name": "Caramel Affogato",
    "item.desserts.karamelli-affogato.description": "is a magnificent dessert with a cake base, ice cream, espresso, chocolate chips, walnuts, and caramel sauce.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.name": "Baked Edirne Cheese Halva",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.description": "is prepared with a traditional recipe and served with an option of ice cream. Each bite offers a unique flavour.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review0.comment": "It's great to find Edirne's famous cheese halva here, perfectly cooked.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review1.comment": "Serving it with ice cream is a great idea, perfect harmony.",
    "item.desserts.brownie.name": "Brownie",
    "item.desserts.brownie.description": "is served intensely chocolatey with an option of ice cream. Enjoy a chocolate extravaganza with every bite, featuring a warm and soft texture.",
    "item.desserts.fistikli-havuc-dilim-baklava.name": "Baklava with Pistachio",
    "item.desserts.fistikli-havuc-dilim-baklava.description": "will delight your palate with its crispy texture and intense pistachio flavour in every bite.",

    // Drinks
    // Coffee
    "item.drinks.turk-kahvesi.name": "Turkish Coffee",
    "item.drinks.turk-kahvesi.description": "Traditional Turkish coffee, served plain, medium, or sweet upon request.",
    "item.drinks.espresso.name": "Espresso",
    "item.drinks.espresso.description": "Intense Italian espresso.",
    "item.drinks.double-espresso.name": "Double Espresso",
    "item.drinks.double-espresso.description": "Double shot of espresso.",
    "item.drinks.americano.name": "Americano",
    "item.drinks.americano.description": "Prepared with espresso and hot water.",
    "item.drinks.latte.name": "Latte",
    "item.drinks.latte.description": "Prepared with espresso and steamed milk.",
    "item.drinks.cappuccino.name": "Cappuccino",
    "item.drinks.cappuccino.description": "Prepared with espresso, steamed milk, and milk foam.",
    "item.drinks.sicak-cikolata.name": "Hot Chocolate",
    "item.drinks.sicak-cikolata.description": "Hot beverage with intense chocolate flavor.",
    "item.drinks.salep.name": "Salep",
    "item.drinks.salep.description": "Traditional Turkish drink, served with cinnamon.",
    "item.drinks.filter-coffee.name": "Filter Coffee",
    "item.drinks.filter-coffee.description": "Prepared from daily ground coffee beans.",
    "item.drinks.sade-kahve.name": "Black Coffee",
    "item.drinks.sade-kahve.description": "Turkish style black coffee.",
    "item.drinks.sutlu-kahve.name": "Coffee with Milk",
    "item.drinks.sutlu-kahve.description": "Turkish style coffee with milk.",
    "item.drinks.soguk-kahve.name": "Cold Brew",
    "item.drinks.soguk-kahve.description": "Iced cold coffee.",
    "item.drinks.frappe.name": "Frappe",
    "item.drinks.frappe.description": "Greek style foamy cold coffee.",
    // Soft Drinks
    "item.drinks.cay.name": "Tea",
    "item.drinks.cay.description": "Traditional Turkish tea.",
    "item.drinks.bitki-cayi.name": "Herbal Tea",
    "item.drinks.bitki-cayi.description": "Various herbal teas (Linden, Sage, Chamomile, Green Tea).",
    "item.drinks.su-small.name": "Water (Small)",
    "item.drinks.su-small.description": "Natural spring water.",
    "item.drinks.su-large.name": "Water (Large)",
    "item.drinks.su-large.description": "Natural spring water.",
    "item.drinks.san-pellegrino.name": "San Pellegrino",
    "item.drinks.san-pellegrino.description": "Italian mineral water.",
    "item.drinks.soda.name": "Mineral Water",
    "item.drinks.soda.description": "Plain or lemon mineral water.",
    "item.drinks.kola.name": "Coke",
    "item.drinks.kola.description": "Coca-Cola, Diet Coke, Coca-Cola Zero.",
    "item.drinks.ayran.name": "Ayran",
    "item.drinks.ayran.description": "Traditional Turkish yogurt drink.",
    "item.drinks.meyve-suyu.name": "Juice",
    "item.drinks.meyve-suyu.description": "Orange, cherry, peach, apricot, pineapple.",
    "item.drinks.limonata.name": "Lemonade",
    "item.drinks.limonata.description": "Homemade fresh lemonade.",
    "item.drinks.tonic.name": "Tonic",
    "item.drinks.tonic.description": "Schweppes Tonic Water.",
    "item.drinks.red-bull.name": "Red Bull",
    "item.drinks.red-bull.description": "Energy drink.",
    // Fresh Juices
    "item.drinks.portakal-suyu.name": "Orange Juice",
    "item.drinks.portakal-suyu.description": "Freshly squeezed orange juice.",
    "item.drinks.nar-suyu.name": "Pomegranate Juice",
    "item.drinks.nar-suyu.description": "Freshly squeezed pomegranate juice.",
    "item.drinks.elma-havuc-bal.name": "Apple Carrot Honey",
    "item.drinks.elma-havuc-bal.description": "Freshly squeezed apple and carrot juice, sweetened with honey.",
  },
  el: {
    // Common
    "app.name": "La Strada Restaurant",
    "app.hotel": "The Plaza Hotel Edirne",
    "app.selectLanguage": "Επιλέξτε Γλώσσα",
    "app.search": "Αναζήτηση",
    "app.cart": "Καλάθι",
    "app.menu": "Μενού",
    "app.order": "Παραγγελία",
    "app.processOrder": "Ολοκλήρωση Παραγγελίας",
    "app.orderSummary": "Σύνοψη Παραγγελίας",
    "app.subtotal": "Μερικό Σύνολο",
    "app.total": "Σύνολο",
    "app.tax": "Φόρος",
    "app.roomNumber": "Αριθμός Δωματίου",
    "app.tableNumber": "Αριθμός Τραπεζιού",
    "app.enterRoomOrTable": "Εισάγετε Αριθμό Δωματίου ή Τραπεζιού",
    "app.notes": "Σημειώσεις",
    "app.addNotes": "Προσθήκη Σημειώσεων",
    "app.back": "Πίσω",
    "app.continue": "Συνέχεια",
    "app.orderConfirmation": "Επιβεβαίωση Παραγγελίας",
    "app.orderSent": "Η παραγγελία σας έχει σταλεί!",
    "app.orderNumber": "Αριθμός Παραγγελίας",
    "app.orderTime": "Ώρα Παραγγελίας",
    "app.orderTotal": "Σύνολο Παραγγελίας",
    "app.newOrder": "Νέα Παραγγελία",
    "app.emptyCart": "Το καλάθι σας είναι άδειο",
    "app.addItems": "Προσθήκη Προϊόντων",
    "app.add": "Προσθήκη",
    "app.select": "Επιλογή",
    "app.addToCart": "Προσθήκη στο Καλάθι",
    "app.details": "Λεπτομέρειες",
    "app.allergens": "Αλλεργιογόνα",
    "app.reviews": "Κριτικές",
    "app.options": "Επιλογές",
    "app.portion": "Μερίδα",
    "app.allergenInfo": "Πληροφορίες Αλλεργιογόνων",
    "app.containsAllergens": "Αυτό το προϊόν περιέχει τα ακόλουθα αλλεργιογόνα",
    "app.allergenWarning": "Εάν έχετε αλλεργίες, παρακαλούμε ενημερώστε το προσωπικό πριν παραγγείλετε",
    "app.customerReviews": "Κριτικές Πελατών",
    "app.bestSeller": "Δημοφιλές",

    // Categories
    "category.all": "Όλο το Μενού",
    "category.breakfast": "Πρωινό",
    "category.starters": "Ορεκτικά και Μεζέδες",
    "category.salads": "Σαλάτες",
    "category.mainDishes": "Κυρίως Πιάτα",
    "category.pasta": "Ζυμαρικά",
    "category.burgers": "Μπέργκερ",
    "category.desserts": "Επιδόρπια",
    "category.drinks": "Ποτά",
    "category.spirits": "Οινοπνευματώδη Ποτά",
    "category.cocktails": "Κοκτέιλ",
    "category.beers": "Biralar",
    "category.wines": "Κρασιά",
    "category.extras": "Έξτρα",

    // Allergens
    "allergen.contains": "Περιέχει",
    "allergen.gluten": "Γλουτένη",
    "allergen.dairy": "Γαλακτοκομικά",
    "allergen.nuts": "Ξηροί Καρποί",
    "allergen.eggs": "Αυγά",
    "allergen.fish": "Ψάρι",
    "allergen.shellfish": "Οστρακοειδή",
    "allergen.soy": "Σόγια",
    "allergen.wheat": "Σιτάρι",
    "allergen.alcohol": "Αλκοόλ",

    // Wine
    "wine.pairing": "Συνδυασμός",
    "wine.pairsWellWith": "Αυτό το κρασί ταιριάζει καλά με",
    "wine.foodPairings": "Συνδυασμοί Φαγητού",

    //  Breakfast (Machine Translated) (EL)
    "item.breakfast.continental-kahvalti.name": "Ηπειρωτικό Πρωινό",
    "item.breakfast.continental-kahvalti.description": "Τοπικό λευκό τυρί Αδριανούπολης, απλή ομελέτα, είδος κίτρινου τυριού από αγελαδινό γάλα, ντομάτα, αγγούρι, πιπεριά, ελιές, κλπ",
    "item.breakfast.serpme-kahvalti.name": "Ανάμεικτο Πρωινό",
    "item.breakfast.serpme-kahvalti.description": "Επιπλέον του ηπειρωτικού πρωινού, τηγανίτες, λουκάνικο, σαλάμι, μπισκότο, τουρκικά κουλούρια, κλπ",
    "item.breakfast.pankek-pastasi.name": "Τηγανίτες",
    "item.breakfast.pankek-pastasi.description": "3 τηγανίτες και φρούτα εποχής",
    "item.breakfast.acik-bufe-kahvalti.name": "Πρωινό σε Μπουφέ",
    "item.breakfast.acik-bufe-kahvalti.description": "07:30πμ - 10:30πμ",
    "item.breakfast.omlet.name": "Ομελέτα",
    "item.breakfast.omlet.description": "Σκέτη, με τυρί, λαχανικά, παλαιωμένο τυρί, σκορδάτα λουκάνικα, λουκάνικο, τηγανητό κρέας",
    "item.breakfast.sahanda-goz-yumurta.name": "Τηγανητά Αυγά",
    "item.breakfast.sahanda-goz-yumurta.description": "Φρεσκομαγειρεμένα τηγανητά αυγά",
    "item.breakfast.menemen.name": "Πικάντικη Τουρκική Ομελέτα",
    "item.breakfast.menemen.description": "Βάση μαγειρέματος παρασκευασμένη με χωριάτικη πιπεριά και καλοκαιρινές ντομάτες, με 2 αυγά..",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.name": "Τοστ Διπλού Τυριού σε Προζυμένιο Ψωμί",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.description": "Προζυμένιο ψωμί για τοστ, φρέσκο θρακιώτικο τσένταρ και σπιτική ντοματοπελτέ με ανάμεικτες ελιές, ντομάτες και αγγούρια",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.name": "Τοστ με Τσένταρ και Λουκάνικο σε Προζυμένιο Ψωμί",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.description": "Προζυμένιο ψωμί για τοστ, φρέσκο θρακιώτικο τσένταρ, μοσχαρίσιο λουκάνικο και σπιτική ντοματοπελτέ με ανάμεικτες ελιές, ντομάτες και αγγούρια",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.name": "Τοστ Τριπλού Τυριού σε Προζυμένιο Ψωμί",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.description": "Προζυμένιο τοστ, φρέσκο θρακιώτικο τσένταρ, τοπικό τυρί Αδριανούπολης και παλαιωμένο θρακιώτικο τσένταρ με σπιτική ντοματοπελτέ, ανάμεικτες ελιές, ντομάτες και αγγούρια",
    "item.breakfast.akitma.name": "Ακίτμα (Θρακιώτικη Κρέπα)",
    "item.breakfast.akitma.description": "Θρακιώτικη κρέπα με λευκό τυρί Αδριανούπολης, βιολογική μαρμελάδα βατόμουρο, ντομάτα, αγγούρι και ελιές",
    "item.breakfast.cicipapa.name": "Τσιτσίπαπα",
    "item.breakfast.cicipapa.description": "Τέσσερις φέτες αυγόψωμο, σερβιρισμένο με λευκό τυρί Αδριανούπολης, φρέσκο κασέρι, σπιτική σάλτσα ατζούκα με καρύδια, ντομάτα, αγγούρι και πράσινη πιπεριά",

    // Starters (Machine Translated) (EL)
    "item.starters.trakya-koy-tarhanasi.name": "Θρακιώτικη χωριάτικη σούπα ταρχανά",
    "item.starters.trakya-koy-tarhanasi.description": "είναι μια ζεστή απόλαυση παρασκευασμένη με φυσικά συστατικά. Σερβίρεται με λευκό τυρί Αδριανούπολης και φρυγανισμένο χωριάτικο ψωμί.",
    "item.starters.zeytinyagli-aysekadin-fasulye.name": "Φασολάκια Αϊσέ Καντίν με ελαιόλαδο",
    "item.starters.zeytinyagli-aysekadin-fasulye.description": "είναι μια ελαφριά και υγιεινή απόλαυση του Αιγαίου, γαρνιρισμένη με λεμόνι και άνηθο.",
    "item.starters.caciki.name": "Τζατζίκι",
    "item.starters.caciki.description": "είναι μια τέλεια αρμονία γιαουρτιού, αγγουριού, σκόρδου και ελαιόλαδου παρασκευασμένο με τον ελληνικό τρόπο. Ως δροσιστικό και ελαφρύ μεζέ, θα προσθέσει γεύση στο τραπέζι σας.",
    "item.starters.caciki.review0.comment": "Καταπληκτικό τζατζίκι! Η αναλογία σκόρδου είναι ακριβώς σωστή, πολύ δροσιστικό.",
    "item.starters.caciki.review1.comment": "Φτιαγμένο με ελληνικό τρόπο, πραγματικά νόστιμο.",
    "item.starters.caciki.review2.comment": "Πολύ φρέσκο και νόστιμο, ταιριάζει τέλεια με ψωμί.",
    "item.starters.saksuka.name": "Σακσούκα",
    "item.starters.saksuka.description": "είναι μια μοναδική αρμονία τηγανητής μελιτζάνας, πιπεριών και σάλτσας ντομάτας. Αυτός ο ελαφρώς πικάντικος και γευστικός μεσογειακός μεζές θα προσθέσει χρώμα στο τραπέζι σας.",
    "item.starters.trakya-mamzana.name": "Θρακιώτικη μαμζάνα",
    "item.starters.trakya-mamzana.description": "είναι μια μοναδική απόλαυση από ψητή μελιτζάνα, πιπεριές και κρεμμύδια συνδυασμένα με σκορδάτο γιαούρτι, η αυθεντική γεύση της Θράκης.",
    "item.starters.atom-haydari.name": "Άτομ χαϊντάρι",
    "item.starters.atom-haydari.description": "είναι ένας νόστιμος μεζές παρασκευασμένος με τραγανές πιπεριές Αδριανούπολης πάνω σε στρώμα σκορδάτου γιαουρτιού, που απευθύνεται τόσο στα μάτια όσο και στον ουρανίσκο.",
    "item.starters.guvecte-manda-yogurdu.name": "Γιαούρτι βουβαλίσιο σε πήλινο",
    "item.starters.guvecte-manda-yogurdu.description": "είναι ένα φυσικό και νόστιμο γιαούρτι που έχει υποστεί ζύμωση σε πήλινα δοχεία. Με την πηχτή υφή και το πλούσιο άρωμά του, προσθέτει μια μοναδική γεύση στο τραπέζι σας.",
    "item.starters.karpuz-peynir.name": "Καρπούζι και τυρί",
    "item.starters.karpuz-peynir.description": "φέρνει κοντά δροσιστικές φέτες καρπουζιού με φρέσκο λευκό τυρί. Αυτό το κλασικό δίδυμο, απαραίτητο το καλοκαίρι, είναι ένα δροσιστικό και γευστικό σνακ.",
    "item.starters.soka-kaymakli-biber-tursusu.name": "Πιπεριές τουρσί Σόκα με καϊμάκι",
    "item.starters.soka-kaymakli-biber-tursusu.description": "είναι οι διάσημες πιπεριές τουρσί με τυρί και κρέμα από την Θράκη και τα Βαλκάνια. Με τη μοναδική γεύση της, μια αναζωογονητική πινελιά.",
    "item.starters.soka-kaymakli-biber-tursusu.review0.comment": "Δεν πίστευα ότι θα μπορούσα να βρω τη βαλκανική γεύση εδώ. Καταπληκτική γεύση!",
    "item.starters.soka-kaymakli-biber-tursusu.review1.comment": "Ιδανικό για όσους τους λείπει η Αδριανούπολη, η αρμονία καϊμακιού και τουρσί είναι υπέροχη.",
    "item.starters.tereyagli-kasarli-mantar.name": "Βουτυράτα μανιτάρια με τυρί",
    "item.starters.tereyagli-kasarli-mantar.description": "μαγειρεύονται στους δικούς τους χυμούς, με καλλιεργημένα, στρειδομανίταρα και μανιτάρια Chanterelle, καλυμμένα με φρέσκο τυρί κασέρι Θράκης.",
    "item.starters.tereyagli-soganli-yaprak-ciger.name": "Συκώτι μοσχαρίσιο φύλλο με βούτυρο και κρεμμύδια",
    "item.starters.tereyagli-soganli-yaprak-ciger.description": "είναι μοσχαρίσιο συκώτι φύλλο σοταρισμένο με κρεμμύδια και βούτυρο. Με την τρυφερή υφή και το πλούσιο άρωμά του, προσφέρει μια παραδοσιακή γεύση.",
    "item.starters.pacanga-boregi.name": "Πατσάνγκα μπουρέκι",
    "item.starters.pacanga-boregi.description": "παρασκευάζεται με παστουρμά, φρέσκο τυρί κασέρι, ντομάτες και πιπεριές. Η τραγανή εξωτερική επιφάνεια το κάνει ζεστό και γευστικό.",
    "item.starters.pacanga-boregi.review0.comment": "Ένα υπέροχο σνακ με τραγανό εξωτερικό και νόστιμο εσωτερικό.",
    "item.starters.pacanga-boregi.review1.comment": "Η αρμονία παστουρμά και τυριού είναι τέλεια, θα παραγγείλω ξανά.",
    "item.starters.patates-kizartmasi.name": "Τηγανητές πατάτες",
    "item.starters.patates-kizartmasi.description": "είναι χρυσαφένιες και τραγανές, με προαιρετική επικάλυψη τυριού. Μια κλασική απόλαυση που φέρνει χαρά με κάθε μπουκιά.",
    "item.starters.ev-yapimi-patates-kizartmasi.name": "Σπιτικές τηγανητές πατάτες",
    "item.starters.ev-yapimi-patates-kizartmasi.description": "είναι τραγανές σπιτικές πατάτες με προαιρετική επικάλυψη τυριού. Μια ζεστή και ικανοποιητική απόλαυση.",
    "item.starters.kizartma-sepeti.name": "Καλάθι τηγανητών",
    "item.starters.kizartma-sepeti.description": "είναι μια νόστιμη ποικιλία από τηγανητές πατάτες, χαλούμι, ροδέλες κρεμμυδιών, λουκάνικα, κοτόπουλο πανέ, και ρολά τσίζμπεργκερ. Δεν θα θέλετε να μοιραστείτε!",
    "item.starters.sarkuteri-tahtasi.name": "Πιάτο αλλαντικών",
    "item.starters.sarkuteri-tahtasi.description": "παρασκευάζεται με τοπικά κρέατα, τυριά και φρούτα, προσφέροντας μια διαφορετική γευστική εμπειρία με κάθε μπουκιά.",

    // Items - Salads (Translated from English) (EL)
    "item.salads.bruschetta.name": "Μπρουσκέτα",
    "item.salads.bruschetta.description": "ετοιμάζεται με φρυγανισμένες φέτες ψωμιού με σκόρδο, γαρνιρισμένες με ντομάτες σε σάλτσα πέστο, τυρί και βασιλικό. Ένα ελαφρύ και δροσιστικό ιταλικό κλασικό.",
    "item.salads.yesil-salata.name": "Πράσινη Σαλάτα",
    "item.salads.yesil-salata.description": "είναι ένα μείγμα μεσογειακών χόρτων που σερβίρεται με σάλτσα μουστάρδας ελαιόλαδου. Αυτή η φρέσκια και ελαφριά σαλάτα είναι ιδανική για όσους αναζητούν μια υγιεινή επιλογή.",
    "item.salads.peynirli-yesil-salata.name": "Πράσινη Σαλάτα με Τυρί",
    "item.salads.peynirli-yesil-salata.description": "σερβίρεται με τυρί, μείγμα μεσογειακών χόρτων και σάλτσα μουστάρδας ελαιόλαδου. Αυτή η υγιεινή και γευστική σαλάτα θα ενθουσιάσει τον ουρανίσκο σας.",
    "item.salads.roka-salata.name": "Σαλάτα Ρόκα",
    "item.salads.roka-salata.description": "ετοιμάζεται με ρόκα, λιαστές ντομάτες, βαλσάμικο ξύδι και τριμμένο παλαιωμένο κασέρι Θράκης.",
    "item.salads.shopska-salata.name": "Σαλάτα Σόπσκα",
    "item.salads.shopska-salata.description": "ετοιμάζεται με ντομάτες, κρεμμύδια, αγγούρια, πιπεριές, μαϊντανό, ελιές και τριμμένο λευκό τυρί. Σερβίρεται με φρυγανισμένο προζυμένιο ψωμί.",
    "item.salads.shopska-salata.review0.comment": "Μια διαφορετική παρουσίαση από αυτές που είχα στη Βουλγαρία, συγχαρητήρια",
    "item.salads.shopska-salata.review1.comment": "Ήταν πολύ νόστιμο",
    "item.salads.istanbul-salata.name": "Σαλάτα Κωνσταντινούπολης",
    "item.salads.istanbul-salata.description": "ετοιμάζεται με ντομάτες, κόκκινα κρεμμύδια, φρέσκο θυμάρι και κρουτόν. Στεφανώνεται με σάλτσα ντομάτας βαλσάμικο.",
    "item.salads.sezar-salata.name": "Σαλάτα του Καίσαρα",
    "item.salads.sezar-salata.description": "ετοιμάζεται με τραγανό μαρούλι iceberg και μαριναρισμένο κοτόπουλο, σάλτσα Καίσαρα, σκορδάτα κρουτόν και τυρί παρμεζάνα.",
    "item.salads.ananas-ve-buzlu-badem-salatasi.name": "Σαλάτα με Ανανά και Παγωμένα Αμύγδαла",
    "item.salads.ananas-ve-buzlu-badem-salatasi.description": "είναι ένα φρέσκο μείγμα μεσογειακών χόρτων, φέτες ανανά, αμύγδαλα και σάλτσα βαλσάμικο, προσφέροντας μια τροπική γεύση.",

    // Main Dishes
    "item.mainDishes.edirne-koftesi.name": "Edirne Meatballs",
    "item.mainDishes.edirne-koftesi.description": "Regionally famous Edirne meatballs, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.name": "Keşan Butcher's Meatballs",
    "item.mainDishes.kesan-satir-kofte.description": "Special butcher's meatballs made with the traditional Keşan cleaver technique, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.review0.comment": "The cleaver technique really makes a difference, delicious!",
    "item.mainDishes.kesan-satir-kofte.review1.comment": "Best meatballs I've had in Edirne.",
    "item.mainDishes.bosnak-kofte.name": "Bosnian Meatballs",
    "item.mainDishes.bosnak-kofte.description": "Traditional Bosnian meatballs (pljeskavica) served with pita bread, ajvar, onions, and potatoes.",
    "item.mainDishes.bosnak-kofte.review0.comment": "Authentic Balkan taste, just like homemade.",
    "item.mainDishes.bosnak-kofte.review1.comment": "Very generous portion and great flavor.",
    "item.mainDishes.izgara-kasap-sucugu.name": "Grilled Butcher's Sausage",
    "item.mainDishes.izgara-kasap-sucugu.description": "Flavorful grilled butcher's sausage, served with roasted peppers, onions, and rice.",
    "item.mainDishes.izgara-tavuk-sis.name": "Grilled Chicken Skewers",
    "item.mainDishes.izgara-tavuk-sis.description": "Tender grilled chicken skewers, served with roasted peppers, onions, and rice.",
    "item.mainDishes.pilic-kulbasti.name": "Chicken Külbastı",
    "item.mainDishes.pilic-kulbasti.description": "Grilled chicken fillet marinated in yogurt and spices, served with roasted peppers, onions, and rice.",
    "item.mainDishes.tavuk-schnitzel.name": "Chicken Schnitzel",
    "item.mainDishes.tavuk-schnitzel.description": "Breaded and fried chicken cutlet, served with french fries and lemon.",
    "item.mainDishes.tereyagli-dana-bonfile.name": "Butter Beef Tenderloin",
    "item.mainDishes.tereyagli-dana-bonfile.description": "Juicy beef tenderloin cooked in butter, served with grilled vegetables.",
    "item.mainDishes.antrikot-sis.name": "Ribeye Skewers",
    "item.mainDishes.antrikot-sis.description": "Marinated ribeye skewers, grilled to perfection, served with roasted peppers, onions, and rice.",
    "item.mainDishes.antrikot-sis.review0.comment": "The meat was incredibly tender and flavorful.",
    "item.mainDishes.antrikot-sis.review1.comment": "A must-try for meat lovers!",
    "item.mainDishes.coban-kavurma.name": "Shepherd's Sauté",
    "item.mainDishes.coban-kavurma.description": "Diced beef sautéed with onions, tomatoes, and peppers, served with rice.",
    "item.mainDishes.kuzu-tandir.name": "Lamb Tandoori",
    "item.mainDishes.kuzu-tandir.description": "Slow-cooked lamb tandoori, tender and flavorful, served with rice and grilled vegetables.",

    // Pasta
    "item.pasta.peynirli-edirne-koy-eristesi.name": "Edirne Noodles",
    "item.pasta.peynirli-edirne-koy-eristesi.description": "are cooked in a sauce of butter, mint, red pepper flakes, and parsley, then crowned with crumbled cheese and walnuts.",
    "item.pasta.peynirli-edirne-koy-eristesi.review0.comment": "Edirne's famous noodles, the combination of butter and cheese is perfect.",
    "item.pasta.peynirli-edirne-koy-eristesi.review1.comment": "Tastes like homemade noodles, the walnut and cheese combination is great.",
    "item.pasta.kiyma-el-acmasi-makarna.name": "Homemade Minced Meat Pasta",
    "item.pasta.kiyma-el-acmasi-makarna.description": "is a delicious dish made with roasted ground beef and fresh homemade pasta. It adds a warm, homemade touch to your table.",
    "item.pasta.penne-alfredo.name": "Penne Alfredo",
    "item.pasta.penne-alfredo.description": "brings together penne pasta with Alfredo sauce made from chicken, cream, mushrooms, Parmesan, and pesto sauce.",
    "item.pasta.penne-napoliten.name": "Penne Napoliten",
    "item.pasta.penne-napoliten.description": "combines penne pasta with a basil and garlic tomato sauce made from summer tomatoes, topped with Thrace aged kashar cheese.",

    // Burgers
    "item.burgers.la-strada-burger.name": "La Strada Burger",
    "item.burgers.la-strada-burger.description": "is made of ground beef ribs, cheddar cheese, iceberg lettuce, pickles, tomatoes, and crispy onion pieces. This unique burger offers a rich and satisfying flavour with every bite.",
    "item.burgers.la-strada-crispy-burger.name": "La Strada Crispy Burger",
    "item.burgers.la-strada-crispy-burger.description": "has crispy chicken thighs, pickles, pickled red onions, and tomatoes. This delicious burger offers a crispy and fresh flavour experience with every bite.",
    "item.burgers.balkan-burger.name": "Balkan Burger",
    "item.burgers.balkan-burger.description": "brings the flavours of the Balkans to your table with roasted red pepper sauce, tomatoes, red onions, crispy pastrami slices, and ground beef ribs. This unique burger offers a rich and satisfying taste experience.",
    "item.burgers.balkan-burger.review0.comment": "A magnificent flavor with pastrami and roasted pepper sauce.",
    "item.burgers.balkan-burger.review1.comment": "A great idea combining Balkan flavors with a burger, very tasty.",

    // Desserts
    "item.desserts.cup-dondurma.name": "Cup Dondurma",
    "item.desserts.cup-dondurma.description": "is a delightful ice cream extravaganza with wafer and fresh fruits! This delicious ice cream offers a refreshing and sweet treat.",
    "item.desserts.trilece.name": "Trileçe",
    "item.desserts.trilece.description": "is the famous caramel three-milk cake from the Balkans. With its soft texture and rich milk aroma, it offers a sweet explosion of flavor with every bite.",
    "item.desserts.karamelli-affogato.name": "Caramel Affogato",
    "item.desserts.karamelli-affogato.description": "is a magnificent dessert with a cake base, ice cream, espresso, chocolate chips, walnuts, and caramel sauce.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.name": "Baked Edirne Cheese Halva",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.description": "is prepared with a traditional recipe and served with an option of ice cream. Each bite offers a unique flavour.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review0.comment": "It's great to find Edirne's famous cheese halva here, perfectly cooked.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review1.comment": "Serving it with ice cream is a great idea, perfect harmony.",
    "item.desserts.brownie.name": "Brownie",
    "item.desserts.brownie.description": "is served intensely chocolatey with an option of ice cream. Enjoy a chocolate extravaganza with every bite, featuring a warm and soft texture.",
    "item.desserts.fistikli-havuc-dilim-baklava.name": "Baklava with Pistachio",
    "item.desserts.fistikli-havuc-dilim-baklava.description": "will delight your palate with its crispy texture and intense pistachio flavour in every bite.",

    // Drinks
    // Coffee
    "item.drinks.turk-kahvesi.name": "Τούρκικος Καφές",
    "item.drinks.turk-kahvesi.description": "Παραδοσιακός τούρκικος καφές, σερβίρεται σκέτος, μέτριος ή γλυκός κατόπιν αιτήματος.",
    "item.drinks.espresso.name": "Εσπρέσο",
    "item.drinks.espresso.description": "Έντονος ιταλικός εσπρέσο.",
    "item.drinks.double-espresso.name": "Διπλός Εσπρέσο",
    "item.drinks.double-espresso.description": "Διπλή δόση εσπρέσο.",
    "item.drinks.americano.name": "Αμερικάνο",
    "item.drinks.americano.description": "Παρασκευάζεται με εσπρέσο και ζεστό νερό.",
    "item.drinks.latte.name": "Λάτε",
    "item.drinks.latte.description": "Παρασκευάζεται με εσπρέσο και γάλα στον ατμό.",
    "item.drinks.cappuccino.name": "Καπουτσίνο",
    "item.drinks.cappuccino.description": "Παρασκευάζεται με εσπρέσο, γάλα στον ατμό και αφρόγαλα.",
    "item.drinks.sicak-cikolata.name": "Ζεστή Σοκολάτα",
    "item.drinks.sicak-cikolata.description": "Ζεστό ρόφημα με έντονη γεύση σοκολάτας.",
    "item.drinks.salep.name": "Σαλέπι",
    "item.drinks.salep.description": "Παραδοσιακό τούρκικο ρόφημα, σερβίρεται με κανέλα.",
    "item.drinks.filter-coffee.name": "Καφές Φίλτρου",
    "item.drinks.filter-coffee.description": "Παρασκευάζεται από καθημερινά αλεσμένους κόκκους καφέ.",
    "item.drinks.sade-kahve.name": "Σκέτος Καφές",
    "item.drinks.sade-kahve.description": "Τούρκικος σκέτος καφές.",
    "item.drinks.sutlu-kahve.name": "Καφές με Γάλα",
    "item.drinks.sutlu-kahve.description": "Τούρκικος καφές με γάλα.",
    "item.drinks.soguk-kahve.name": "Κρύος Καφές (Cold Brew)",
    "item.drinks.soguk-kahve.description": "Παγωμένος κρύος καφές.",
    "item.drinks.frappe.name": "Φραπέ",
    "item.drinks.frappe.description": "Ελληνικός αφρώδης κρύος καφές.",
    // Soft Drinks
    "item.drinks.cay.name": "Τσάι",
    "item.drinks.cay.description": "Παραδοσιακό τούρκικο τσάι.",
    "item.drinks.bitki-cayi.name": "Τσάι Βοτάνων",
    "item.drinks.bitki-cayi.description": "Διάφορα τσάγια βοτάνων (Τίλιο, Φασκόμηλο, Χαμομήλι, Πράσινο Τσάι).",
    "item.drinks.su-small.name": "Νερό (Μικρό)",
    "item.drinks.su-small.description": "Φυσικό μεταλλικό νερό.",
    "item.drinks.su-large.name": "Νερό (Μεγάλο)",
    "item.drinks.su-large.description": "Φυσικό μεταλλικό νερό.",
    "item.drinks.san-pellegrino.name": "San Pellegrino",
    "item.drinks.san-pellegrino.description": "Ιταλικό μεταλλικό νερό.",
    "item.drinks.soda.name": "Σόδα (Ανθρακούχο Νερό)",
    "item.drinks.soda.description": "Απλό ή με λεμόνι ανθρακούχο νερό.",
    "item.drinks.kola.name": "Κόλα",
    "item.drinks.kola.description": "Coca-Cola, Diet Coke, Coca-Cola Zero.",
    "item.drinks.ayran.name": "Αριάνι",
    "item.drinks.ayran.description": "Παραδοσιακό τούρκικο ρόφημα γιαουρτιού.",
    "item.drinks.meyve-suyu.name": "Χυμός",
    "item.drinks.meyve-suyu.description": "Πορτοκάλι, βύσσινο, ροδάκινο, βερίκοκο, ανανάς.",
    "item.drinks.limonata.name": "Λεμονάδα",
    "item.drinks.limonata.description": "Σπιτική φρέσκια λεμονάδα.",
    "item.drinks.tonic.name": "Tonic",
    "item.drinks.tonic.description": "Schweppes Tonik.",
    "item.drinks.red-bull.name": "Red Bull",
    "item.drinks.red-bull.description": "Energy drink.",
    // Fresh Juices
    "item.drinks.portakal-suyu.name": "Χυμός Πορτοκάλι",
    "item.drinks.portakal-suyu.description": "Φρεσκοστυμμένος χυμός πορτοκάλι.",
    "item.drinks.nar-suyu.name": "Χυμός Ρόδι",
    "item.drinks.nar-suyu.description": "Φρεσκοστυμμένος χυμός ρόδι.",
    "item.drinks.elma-havuc-bal.name": "Μήλο Καρότο Μέλι",
    "item.drinks.elma-havuc-bal.description": "Φρεσκοστυμμένος χυμός μήλου και καρότου, γλυκαμένος με μέλι.",
  },
  bg: {
    // Common
    "app.name": "Ресторант Ла Страда",
    "app.hotel": "Хотел Плаза Одрин",
    "app.selectLanguage": "Изберете Език",
    "app.search": "Търсене",
    "app.cart": "Кошница",
    "app.menu": "Меню",
    "app.order": "Поръчка",
    "app.processOrder": "Завършване на Поръчката",
    "app.orderSummary": "Резюме на Поръчката",
    "app.subtotal": "Междинна Сума",
    "app.total": "Общо",
    "app.tax": "Данък",
    "app.roomNumber": "Номер на Стая",
    "app.tableNumber": "Номер на Маса",
    "app.enterRoomOrTable": "Въведете Номер на Стая или Маса",
    "app.notes": "Бележки",
    "app.addNotes": "Добавяне на Бележки",
    "app.back": "Назад",
    "app.continue": "Продължи",
    "app.orderConfirmation": "Потвърждение на Поръчката",
    "app.orderSent": "Вашата поръчка е изпратена!",
    "app.orderNumber": "Номер на Поръчка",
    "app.orderTime": "Време на Поръчка",
    "app.orderTotal": "Обща Сума",
    "app.newOrder": "Нова Поръчка",
    "app.emptyCart": "Вашата кошница е празна",
    "app.addItems": "Добавяне на Продукти",
    "app.add": "Добави",
    "app.select": "Избери",
    "app.addToCart": "Добави в Кошницата",
    "app.details": "Детайли",
    "app.allergens": "Алергени",
    "app.reviews": "Отзиви",
    "app.options": "Опции",
    "app.portion": "Порция",
    "app.allergenInfo": "Информация за Алергени",
    "app.containsAllergens": "Този продукт съдържа следните алергени",
    "app.allergenWarning": "Ако имате алергии, моля информирайте персонала преди да поръчате",
    "app.customerReviews": "Отзиви от Клиенти",
    "app.bestSeller": "Най-Продаван",

    // Categories
    "category.all": "Цялото Меню",
    "category.breakfast": "Закуска",
    "category.starters": "Предястия и Мезета",
    "category.salads": "Салати",
    "category.mainDishes": "Основни Ястия",
    "category.pasta": "Паста",
    "category.burgers": "Бургери",
    "category.desserts": "Десерти",
    "category.drinks": "Напитки",
    "category.spirits": "Високоалкохолни Напитки",
    "category.cocktails": "Коктейли",
    "category.beers": "Бира",
    "category.wines": "Вино",
    "category.extras": "Екстри",

    // Allergens
    "allergen.contains": "Съдържа",
    "allergen.gluten": "Глутен",
    "allergen.dairy": "Млечни Продукти",
    "allergen.nuts": "Ядки",
    "allergen.eggs": "Яйца",
    "allergen.fish": "Риба",
    "allergen.shellfish": "Ракообразни",
    "allergen.soy": "Соя",
    "allergen.wheat": "Пшеница",
    "allergen.alcohol": "Алкохол",

    // Wine
    "wine.pairing": "Съчетание",
    "wine.pairsWellWith": "Това вино се съчетава добре с",
    "wine.foodPairings": "Съчетания с Храна",

    // Breakfast (Machine Translated) (BG)
    "item.breakfast.continental-kahvalti.name": "Континентална Закуска",
    "item.breakfast.continental-kahvalti.description": "Одринско бяло сирене, обикновен омлет, кашкавал, домат, краставица, чушка, маслини и др..",
    "item.breakfast.serpme-kahvalti.name": "Сервирана Закуска",
    "item.breakfast.serpme-kahvalti.description": "В допълнение към континенталната закуска: палачинка, наденица, салам, бисквита, simit, vs..",
    "item.breakfast.pankek-pastasi.name": "Палачинкова Кула",
    "item.breakfast.pankek-pastasi.description": "3 палачинки и сезонни плодове",
    "item.breakfast.acik-bufe-kahvalti.name": "Закуска на Шведска Маса",
    "item.breakfast.acik-bufe-kahvalti.description": "Между 07:30 - 10:30 часа",
    "item.breakfast.omlet.name": "Омлет",
    "item.breakfast.omlet.description": "Обикновен, със сирене, зеленчуци, кашкавал, суджук, наденица, печено месо",
    "item.breakfast.sahanda-goz-yumurta.name": "Пържени Яйца",
    "item.breakfast.sahanda-goz-yumurta.description": "Прясно приготвени пържени яйца",
    "item.breakfast.menemen.name": "Пикантен Турски Омлет",
    "item.breakfast.menemen.description": "Основа за готвене, приготвена със селска чушка и летни домати, с 2 яйца..",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.name": "Тост с Двойно Сирене на Квасен Хляб",
    "item.breakfast.eksi-mayali-ekmege-cift-kasarli-tost.description": "Квасен тост хляб, прясно тракийско чедър и домашно приготвен доматен сос със смесени маслини, домати и краставици",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.name": "Тост с Чедър и Наденица на Квасен Хляб",
    "item.breakfast.eksi-mayali-ekmege-kasarli-sucuklu-tost.description": "Квасен тост хляб, прясно тракийско чедър, телешка наденица и домашно приготвен доматен сос със смесени маслини, домати и краставици",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.name": "Тост с Тройно Сирене на Квасен Хляб",
    "item.breakfast.eksi-mayali-ekmege-3-peynirli-tost.description": "Квасен тост, прясно тракийско чедър, местно сирене от Одрин и отлежало тракийско чедър с домашно приготвен доматен сос, смесени маслини, домати и краставици",
    "item.breakfast.akitma.name": "Акътма (Тракийска Палачинка)",
    "item.breakfast.akitma.description": "Тракийска палачинка с бяло сирене от Одрин, био сладко от къпини, домат, краставица и маслини",
    "item.breakfast.cicipapa.name": "Джиджипапа",
    "item.breakfast.cicipapa.description": "Четири филийки яйчен хляб, сервирани с бяло сирене от Одрин, пресен кашкавал, домашен орехов сос аджука, домат, краставица и зелена чушка",

    // Starters (Machine Translated) (BG)
    "item.starters.trakya-koy-tarhanasi.name": "Тракийска селска таркана",
    "item.starters.trakya-koy-tarhanasi.description": "Приготвена с натурални съставки, затопляща сърцето вкусотия. Оставя незабравим вкус с бяло сирене от Одрин и препечен селски хляб.",
    "item.starters.zeytinyagli-aysekadin-fasulye.name": "Зелен фасул със зехтин",
    "item.starters.zeytinyagli-aysekadin-fasulye.description": "Лек и здравословен егейски вкус, украсен с лимон и копър.",
    "item.starters.caciki.name": "Цацики",
    "item.starters.caciki.description": "Перфектната хармония от кисело мляко, краставица, чесън и зехтин, приготвена по гръцки начин. Добавя вкус към вашата трапеза като освежаващо и леко предястие.",
    "item.starters.caciki.review0.comment": "Невероятен цацики! Пропорцията на чесъна е точно правилната, много освежаващ.",
    "item.starters.caciki.review1.comment": "Направен по гръцки начин, наистина вкусен.",
    "item.starters.caciki.review2.comment": "Много свеж и вкусен, перфектно съчетание с хляб.",
    "item.starters.saksuka.name": "Шакшука",
    "item.starters.saksuka.description": "Уникалната хармония от пържен патладжан, чушка и доматен сос. Това леко пикантно и ароматно средиземноморско предястие ще добави цвят към вашата трапеза.",
    "item.starters.trakya-mamzana.name": "Тракийска мамзана",
    "item.starters.trakya-mamzana.description": "Този уникален вкус, създаден чрез комбиниране на печен патладжан, чушка и лук с чеснов йогурт, носи автентичния вкус на Тракия на вашата маса.",
    "item.starters.atom-haydari.name": "Атом хайдари",
    "item.starters.atom-haydari.description": "Това вкусно предястие, приготвено с хрупкави чушки от Одрин върху чеснов йогурт, привлича както очите, така и небцето.",
    "item.starters.guvecte-manda-yogurdu.name": "Биволско кисело мляко в глинен съд",
    "item.starters.guvecte-manda-yogurdu.description": "Натурално и вкусно биволско кисело мляко, ферментирало в глинени съдове. Добавя уникален вкус към вашата маса със своята гъста консистенция и богат аромат.",
    "item.starters.karpuz-peynir.name": "Диня и сирене",
    "item.starters.karpuz-peynir.description": "Освежаващи резени диня се срещат с прясно бяло сирене. Този класически летен дует е освежаваща и вкусна закуска.",
    "item.starters.soka-kaymakli-biber-tursusu.name": "Туршия от чушки Шока със сметана",
    "item.starters.soka-kaymakli-biber-tursusu.description": "Известна туршия от чушки със сирене и сметана от Тракия и Балканите. Добавя освежаващ щрих към вашата трапеза със своя уникален вкус.",
    "item.starters.soka-kaymakli-biber-tursusu.review0.comment": "Не вярвах, че мога да намеря балканския вкус тук. Καταπληκτική γεύση!",
    "item.starters.soka-kaymakli-biber-tursusu.review1.comment": "Идеално за тези, които копнеят за Одрин, хармонията на сметаната и туршията е прекрасна.",
    "item.starters.tereyagli-kasarli-mantar.name": "Гъби с масло и кашкавал",
    "item.starters.tereyagli-kasarli-mantar.description": "Култивирани, стриди и сарикиз гъби, готвени в собствения си сок, с гратен от пресен тракийски кашкавал отгоре.",
    "item.starters.tereyagli-soganli-yaprak-ciger.name": "Телешки дроб на листи с масло и лук",
    "item.starters.tereyagli-soganli-yaprak-ciger.description": "Телешки дроб на листи, запържен с лук и масло. Традиционен вкус с неговата мека текстура и богат аромат.",
    "item.starters.pacanga-boregi.name": "Бюрек паджанга",
    "item.starters.pacanga-boregi.description": "Приготвен с пастърма, пресен кашкавал, домати и чушка. Топло и вкусно начало с хармонията на съставките и хрупкавата външна обвивка.",
    "item.starters.pacanga-boregi.review0.comment": "Прекрасна закуска с хрупкава външна част и вкусна вътрешност.",
    "item.starters.pacanga-boregi.review1.comment": "Хармонията на пастърмата и сиренето е перфектна, ще поръчам отново.",
    "item.starters.patates-kizartmasi.name": "Пържени картофи",
    "item.starters.patates-kizartmasi.description": "Златисти и хрупкави пържени картофи, с опция за сирене. Класически вкус, приятен при всяка хапка.",
    "item.starters.ev-yapimi-patates-kizartmasi.name": "Домашни пържени картофи",
    "item.starters.ev-yapimi-patates-kizartmasi.description": "Хрупкави домашни пържени картофи, с опция за сирене. Топъл и засищащ вкус.",
    "item.starters.kizartma-sepeti.name": "Плато с Пържени Храни",
    "item.starters.kizartma-sepeti.description": "Ароматно разнообразие, състоящо се от пържени картофи, халуми, лучени кръгчета, наденица, пилешки пръчици и чийзбургер бьорек.",
    "item.starters.sarkuteri-tahtasi.name": "Плато с Деликатеси",
    "item.starters.sarkuteri-tahtasi.description": "Това изискано плато с деликатеси, приготвено с местни меса, сирена и плодове, предлага различно вкусово изживяване при всяка хапка.",

    // Items - Salads (Translated from English) (BG)
    "item.salads.bruschetta.name": "Брускета",
    "item.salads.bruschetta.description": "е приготвена с препечени филийки хляб с чесън, гарнирани с домати в песто сос, сирене и босилек. Лек и освежаващ италиански класически.",
    "item.salads.yesil-salata.name": "Зелена салата",
    "item.salads.yesil-salata.description": "е микс от средиземноморски зеленчуци, сервирани с дресинг от зехтин и горчица. Тази свежа и лека салата е идеална за тези, които търсят здравословна опция.",
    "item.salads.peynirli-yesil-salata.name": "Зелена салата със сирене",
    "item.salads.peynirli-yesil-salata.description": "се сервира със сирене, микс от средиземноморски зеленчуци и дресинг от зехтин и горчица. Тази здравословна и вкусна салата ще зарадва вашето небце.",
    "item.salads.roka-salata.name": "Салата от рукола",
    "item.salads.roka-salata.description": "е приготвена с рукола, сушени на слънце домати, балсамов дресинг и настърган тракийски кашкавал.",
    "item.salads.shopska-salata.name": "Шопска салата",
    "item.salads.shopska-salata.description": "е приготвена с домати, лук, краставици, чушки, магданоз, маслини и настъргано бяло сирене. Сервира се с препечен квасен хляб.",
    "item.salads.shopska-salata.review0.comment": "Различно поднасяне от това, което съм опитвал в България, браво",
    "item.salads.shopska-salata.review1.comment": "Беше много вкусно",
    "item.salads.istanbul-salata.name": "Истанбулска салата",
    "item.salads.istanbul-salata.description": "е приготвена с домати, червен лук, пресен мащерка и крутони. Увенчана с балсамов доматен дресинг.",
    "item.salads.sezar-salata.name": "Салата Цезар",
    "item.salads.sezar-salata.description": "е приготвена с хрупкава айсберг маруля и мариновано пиле, дресинг Цезар, чеснови крутони и пармезан.",
    "item.salads.ananas-ve-buzlu-badem-salatasi.name": "Салата с ананас и ледени бадеми",
    "item.salads.ananas-ve-buzlu-badem-salatasi.description": "е свеж микс от средиземноморски зеленчуци, резени ананас, бадеми и балсамов дресинг, предлагащ тропически вкус.",

    // Main Dishes
    "item.mainDishes.edirne-koftesi.name": "Edirne Meatballs",
    "item.mainDishes.edirne-koftesi.description": "Regionally famous Edirne meatballs, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.name": "Keşan Butcher's Meatballs",
    "item.mainDishes.kesan-satir-kofte.description": "Special butcher's meatballs made with the traditional Keşan cleaver technique, served with roasted peppers, onions, and rice.",
    "item.mainDishes.kesan-satir-kofte.review0.comment": "The cleaver technique really makes a difference, delicious!",
    "item.mainDishes.kesan-satir-kofte.review1.comment": "Best meatballs I've had in Edirne.",
    "item.mainDishes.bosnak-kofte.name": "Bosnian Meatballs",
    "item.mainDishes.bosnak-kofte.description": "Traditional Bosnian meatballs (pljeskavica) served with pita bread, ajvar, onions, and potatoes.",
    "item.mainDishes.bosnak-kofte.review0.comment": "Authentic Balkan taste, just like homemade.",
    "item.mainDishes.bosnak-kofte.review1.comment": "Very generous portion and great flavor.",
    "item.mainDishes.izgara-kasap-sucugu.name": "Grilled Butcher's Sausage",
    "item.mainDishes.izgara-kasap-sucugu.description": "Flavorful grilled butcher's sausage, served with roasted peppers, onions, and rice.",
    "item.mainDishes.izgara-tavuk-sis.name": "Grilled Chicken Skewers",
    "item.mainDishes.izgara-tavuk-sis.description": "Tender grilled chicken skewers, served with roasted peppers, onions, and rice.",
    "item.mainDishes.pilic-kulbasti.name": "Chicken Külbastı",
    "item.mainDishes.pilic-kulbasti.description": "Grilled chicken fillet marinated in yogurt and spices, served with roasted peppers, onions, and rice.",
    "item.mainDishes.tavuk-schnitzel.name": "Chicken Schnitzel",
    "item.mainDishes.tavuk-schnitzel.description": "Breaded and fried chicken cutlet, served with french fries and lemon.",
    "item.mainDishes.tereyagli-dana-bonfile.name": "Butter Beef Tenderloin",
    "item.mainDishes.tereyagli-dana-bonfile.description": "Juicy beef tenderloin cooked in butter, served with grilled vegetables.",
    "item.mainDishes.antrikot-sis.name": "Ribeye Skewers",
    "item.mainDishes.antrikot-sis.description": "Marinated ribeye skewers, grilled to perfection, served with roasted peppers, onions, and rice.",
    "item.mainDishes.antrikot-sis.review0.comment": "The meat was incredibly tender and flavorful.",
    "item.mainDishes.antrikot-sis.review1.comment": "A must-try for meat lovers!",
    "item.mainDishes.coban-kavurma.name": "Shepherd's Sauté",
    "item.mainDishes.coban-kavurma.description": "Diced beef sautéed with onions, tomatoes, and peppers, served with rice.",
    "item.mainDishes.kuzu-tandir.name": "Lamb Tandoori",
    "item.mainDishes.kuzu-tandir.description": "Slow-cooked lamb tandoori, tender and flavorful, served with rice and grilled vegetables.",

    // Pasta
    "item.pasta.peynirli-edirne-koy-eristesi.name": "Edirne Noodles",
    "item.pasta.peynirli-edirne-koy-eristesi.description": "are cooked in a sauce of butter, mint, red pepper flakes, and parsley, then crowned with crumbled cheese and walnuts.",
    "item.pasta.peynirli-edirne-koy-eristesi.review0.comment": "Edirne's famous noodles, the combination of butter and cheese is perfect.",
    "item.pasta.peynirli-edirne-koy-eristesi.review1.comment": "Tastes like homemade noodles, the walnut and cheese combination is great.",
    "item.pasta.kiyma-el-acmasi-makarna.name": "Homemade Minced Meat Pasta",
    "item.pasta.kiyma-el-acmasi-makarna.description": "is a delicious dish made with roasted ground beef and fresh homemade pasta. It adds a warm, homemade touch to your table.",
    "item.pasta.penne-alfredo.name": "Penne Alfredo",
    "item.pasta.penne-alfredo.description": "brings together penne pasta with Alfredo sauce made from chicken, cream, mushrooms, Parmesan, and pesto sauce.",
    "item.pasta.penne-napoliten.name": "Penne Napoliten",
    "item.pasta.penne-napoliten.description": "combines penne pasta with a basil and garlic tomato sauce made from summer tomatoes, topped with Thrace aged kashar cheese.",

    // Burgers
    "item.burgers.la-strada-burger.name": "La Strada Burger",
    "item.burgers.la-strada-burger.description": "is made of ground beef ribs, cheddar cheese, iceberg lettuce, pickles, tomatoes, and crispy onion pieces. This unique burger offers a rich and satisfying flavour with every bite.",
    "item.burgers.la-strada-crispy-burger.name": "La Strada Crispy Burger",
    "item.burgers.la-strada-crispy-burger.description": "has crispy chicken thighs, pickles, pickled red onions, and tomatoes. This delicious burger offers a crispy and fresh flavour experience with every bite.",
    "item.burgers.balkan-burger.name": "Balkan Burger",
    "item.burgers.balkan-burger.description": "brings the flavours of the Balkans to your table with roasted red pepper sauce, tomatoes, red onions, crispy pastrami slices, and ground beef ribs. This unique burger offers a rich and satisfying taste experience.",
    "item.burgers.balkan-burger.review0.comment": "A magnificent flavor with pastrami and roasted pepper sauce.",
    "item.burgers.balkan-burger.review1.comment": "A great idea combining Balkan flavors with a burger, very tasty.",

    // Desserts
    "item.desserts.cup-dondurma.name": "Cup Dondurma",
    "item.desserts.cup-dondurma.description": "is a delightful ice cream extravaganza with wafer and fresh fruits! This delicious ice cream offers a refreshing and sweet treat.",
    "item.desserts.trilece.name": "Trileçe",
    "item.desserts.trilece.description": "is the famous caramel three-milk cake from the Balkans. With its soft texture and rich milk aroma, it offers a sweet explosion of flavor with every bite.",
    "item.desserts.karamelli-affogato.name": "Caramel Affogato",
    "item.desserts.karamelli-affogato.description": "is a magnificent dessert with a cake base, ice cream, espresso, chocolate chips, walnuts, and caramel sauce.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.name": "Baked Edirne Cheese Halva",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.description": "is prepared with a traditional recipe and served with an option of ice cream. Each bite offers a unique flavour.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review0.comment": "It's great to find Edirne's famous cheese halva here, perfectly cooked.",
    "item.desserts.firinlanmis-edirne-peynir-helvasi.review1.comment": "Serving it with ice cream is a great idea, perfect harmony.",
    "item.desserts.brownie.name": "Brownie",
    "item.desserts.brownie.description": "is served intensely chocolatey with an option of ice cream. Enjoy a chocolate extravaganza with every bite, featuring a warm and soft texture.",
    "item.desserts.fistikli-havuc-dilim-baklava.name": "Baklava with Pistachio",
    "item.desserts.fistikli-havuc-dilim-baklava.description": "will delight your palate with its crispy texture and intense pistachio flavour in every bite.",

    // Drinks
    // Coffee
    "item.drinks.turk-kahvesi.name": "Τούρκικος Καφές",
    "item.drinks.turk-kahvesi.description": "Παραδοσιακός τούρκικος καφές, σερβίρεται σκέτος, μέτριος ή γλυκός κατόπιν αιτήματος.",
    "item.drinks.espresso.name": "Εσπρέσο",
    "item.drinks.espresso.description": "Έντονος ιταλικός εσπρέσο.",
    "item.drinks.double-espresso.name": "Διπλός Εσπρέσο",
    "item.drinks.double-espresso.description": "Διπλή δόση εσπρέσο.",
    "item.drinks.americano.name": "Αμερικάνο",
    "item.drinks.americano.description": "Παρασκευάζεται με εσπρέσο και ζεστό νερό.",
    "item.drinks.latte.name": "Λάτε",
    "item.drinks.latte.description": "Παρασκευάζεται με εσπρέσο και γάλα στον ατμό.",
    "item.drinks.cappuccino.name": "Καπουτσίνο",
    "item.drinks.cappuccino.description": "Παρασκευάζεται με εσπρέσο, γάλα στον ατμό και αφρόγαλα.",
    "item.drinks.sicak-cikolata.name": "Ζεστή Σοκολάτα",
    "item.drinks.sicak-cikolata.description": "Ζεστό ρόφημα με έντονη γεύση σοκολάτας.",
    "item.drinks.salep.name": "Σαλέπι",
    "item.drinks.salep.description": "Παραδοσιακό τούρκικο ρόφημα, σερβίρεται με κανέλα.",
    "item.drinks.filter-coffee.name": "Καφές Φίλτρου",
    "item.drinks.filter-coffee.description": "Παρασκευάζεται από καθημερινά αλεσμένους κόκκους καφέ.",
    "item.drinks.sade-kahve.name": "Σκέτος Καφές",
    "item.drinks.sade-kahve.description": "Τούρκικος σκέτος καφές.",
    "item.drinks.sutlu-kahve.name": "Καφές με Γάλα",
    "item.drinks.sutlu-kahve.description": "Τούρκικος καφές με γάλα.",
    "item.drinks.soguk-kahve.name": "Κρύος Καφές (Cold Brew)",
    "item.drinks.soguk-kahve.description": "Παγωμένος κρύος καφές.",
    "item.drinks.frappe.name": "Φραπέ",
    "item.drinks.frappe.description": "Ελληνικός αφρώδης κρύος καφές.",
    // Soft Drinks
    "item.drinks.cay.name": "Τσάι",
    "item.drinks.cay.description": "Παραδοσιακό τούρκικο τσάι.",
    "item.drinks.bitki-cayi.name": "Τσάι Βοτάνων",
    "item.drinks.bitki-cayi.description": "Διάφορα τσάγια βοτάνων (Τίλιο, Φασκόμηλο, Χαμομήλι, Πράσινο Τσάι).",
    "item.drinks.su-small.name": "Νερό (Μικρό)",
    "item.drinks.su-small.description": "Φυσικό μεταλλικό νερό.",
    "item.drinks.su-large.name": "Νερό (Μεγάλο)",
    "item.drinks.su-large.description": "Φυσικό μεταλλικό νερό.",
    "item.drinks.san-pellegrino.name": "San Pellegrino",
    "item.drinks.san-pellegrino.description": "Ιταλικό μεταλλικό νερό.",
    "item.drinks.soda.name": "Σόδα (Ανθρακούχο Νερό)",
    "item.drinks.soda.description": "Απλό ή με λεμόνι ανθρακούχο νερό.",
    "item.drinks.kola.name": "Κόλα",
    "item.drinks.kola.description": "Coca-Cola, Diet Coke, Coca-Cola Zero.",
    "item.drinks.ayran.name": "Αριάνι",
    "item.drinks.ayran.description": "Παραδοσιακό τούρκικο ρόφημα γιαουρτιού.",
    "item.drinks.meyve-suyu.name": "Χυμός",
    "item.drinks.meyve-suyu.description": "Πορτοκάλι, βύσσινο, ροδάκινο, βερίκοκο, ανανάς.",
    "item.drinks.limonata.name": "Λεμονάδα",
    "item.drinks.limonata.description": "Σπιτική φρέσκια λεμονάδα.",
    "item.drinks.tonic.name": "Tonic",
    "item.drinks.tonic.description": "Schweppes Tonik.",
    "item.drinks.red-bull.name": "Red Bull",
    "item.drinks.red-bull.description": "Energy drink.",
    // Fresh Juices
    "item.drinks.portakal-suyu.name": "Χυμός Πορτοκάλι",
    "item.drinks.portakal-suyu.description": "Φρεσκοστυμμένος χυμός πορτοκάλι.",
    "item.drinks.nar-suyu.name": "Χυμός Ρόδι",
    "item.drinks.nar-suyu.description": "Φρεσκοστυμμένος χυμός ρόδι.",
    "item.drinks.elma-havuc-bal.name": "Μήλο Καρότο Μέλι",
    "item.drinks.elma-havuc-bal.description": "Φρεσκοστυμμένος χυμός μήλου και καρότου, γλυκαμένος με μέλι.",
  },
}

// Create provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("tr") // Default to Turkish
  const [isLoaded, setIsLoaded] = useState<boolean>(false)

  // Load language preference from localStorage on client side
  useEffect(() => {
    // Only run on client-side
    if (typeof window === 'undefined') return;
    
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "tr", "el", "bg"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
    
    // Mark as loaded from localStorage
    setIsLoaded(true)
  }, [])

  // Save language preference to localStorage when it changes
  useEffect(() => {
    // Only save to localStorage after initial loading and when on client-side
    if (!isLoaded || typeof window === 'undefined') return;
    localStorage.setItem("language", language)
  }, [language, isLoaded])

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t, isLoaded }}>{children}</LanguageContext.Provider>
}

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext)
