const fs = require('fs');
const path = require('path');

// Import Turkish translations
const trTranslations = require('../locales/tr.json');

// Function to extract translations from the TypeScript language context file
const extractTranslationsFromContext = () => {
  try {
    // Read the language context file
    const contextPath = path.join(__dirname, '../contexts/language-context.tsx');
    const contextContent = fs.readFileSync(contextPath, 'utf8');
    
    // Extract translations object using regex
    const translationsMatch = contextContent.match(/const translations: Record<Language, Record<string, string>> = ({[\s\S]*?});/);
    
    if (!translationsMatch) {
      console.warn('Could not extract translations from language context, using fallback');
      return getFallbackTranslations();
    }
    
    const translationsStr = translationsMatch[1];
    
    // Parse each language section
    const translations = {
      en: {},
      tr: trTranslations,
      el: {},
      bg: {}
    };
    
    // Extract English translations
    const enMatch = translationsStr.match(/en:\s*{([\s\S]*?)},\s*tr:/);
    if (enMatch) {
      extractKeyValuePairs(enMatch[1], translations.en);
    }
    
    // Extract Greek translations
    const elMatch = translationsStr.match(/el:\s*{([\s\S]*?)},\s*bg:/);
    if (elMatch) {
      extractKeyValuePairs(elMatch[1], translations.el);
    }
    
    // Extract Bulgarian translations
    const bgMatch = translationsStr.match(/bg:\s*{([\s\S]*?)}\s*$/);
    if (bgMatch) {
      extractKeyValuePairs(bgMatch[1], translations.bg);
    }
    
    return translations;
    
  } catch (error) {
    console.error('Error reading language context:', error);
    return getFallbackTranslations();
  }
};

// Helper function to extract key-value pairs from a string
const extractKeyValuePairs = (content, targetObj) => {
  // Match quoted key-value pairs, handling multi-line values
  const regex = /"([^"]+)":\s*"([^"]*(?:\\.[^"]*)*)"/g;
  let match;
  
  while ((match = regex.exec(content)) !== null) {
    const key = match[1];
    const value = match[2].replace(/\\"/g, '"'); // Unescape quotes
    targetObj[key] = value;
  }
};

// Fallback translations with email keys
const getFallbackTranslations = () => {
  return {
    en: {
      "email.newOrderReceived": "🍽️ New Order Received",
      "email.orderManagementSystem": "La Strada Restaurant - Order Management System",
      "email.orderDetails": "Order Details",
      "email.orderNumber": "Order Number",
      "email.orderTime": "Order Time",
      "email.location": "Location",
      "email.customerEmail": "Customer Email",
      "email.orderItems": "Order Items",
      "email.qty": "Qty",
      "email.item": "Item",
      "email.price": "Price",
      "email.note": "Note",
      "email.total": "Total",
      "email.actionRequired": "📋 Action Required:",
      "email.prepareOrderMessage": "Please prepare this order and ensure it's delivered to {location}.",
      "email.autoGeneratedMessage": "This email was automatically generated by the La Strada Restaurant ordering system.",
      "email.orderConfirmation": "✅ Order Confirmation",
      "email.thankYouMessage": "Thank you for your order!",
      "email.yourOrderDetails": "Your Order Details",
      "email.deliveryLocation": "Delivery Location",
      "email.orderSummary": "Order Summary",
      "email.estimatedTime": "🕐 Estimated Preparation Time:",
      "email.estimatedTimeValue": "15-25 minutes",
      "email.deliveryLocationLabel": "📍 Delivery Location:",
      "email.thankYouFooter": "Thank you for choosing La Strada Restaurant!",
      "email.contactMessage": "If you have any questions about your order, please contact our reception."
    },
    tr: trTranslations,
    el: {
      "email.newOrderReceived": "🍽️ Νέα Παραγγελία Ελήφθη",
      "email.orderManagementSystem": "La Strada Restaurant - Σύστημα Διαχείρισης Παραγγελιών",
      "email.orderDetails": "Λεπτομέρειες Παραγγελίας",
      "email.orderNumber": "Αριθμός Παραγγελίας",
      "email.orderTime": "Ώρα Παραγγελίας",
      "email.location": "Τοποθεσία",
      "email.customerEmail": "Email Πελάτη",
      "email.orderItems": "Προϊόντα Παραγγελίας",
      "email.qty": "Τεμ.",
      "email.item": "Προϊόν",
      "email.price": "Τιμή",
      "email.note": "Σημείωση",
      "email.total": "Σύνολο",
      "email.actionRequired": "📋 Απαιτούμενη Ενέργεια:",
      "email.prepareOrderMessage": "Παρακαλούμε προετοιμάστε αυτή την παραγγελία και φροντίστε να παραδοθεί στο {location}.",
      "email.autoGeneratedMessage": "Αυτό το email δημιουργήθηκε αυτόματα από το σύστημα παραγγελιών του La Strada Restaurant.",
      "email.orderConfirmation": "✅ Επιβεβαίωση Παραγγελίας",
      "email.thankYouMessage": "Σας ευχαριστούμε για την παραγγελία σας!",
      "email.yourOrderDetails": "Λεπτομέρειες της Παραγγελίας σας",
      "email.deliveryLocation": "Τοποθεσία Παράδοσης",
      "email.orderSummary": "Σύνοψη Παραγγελίας",
      "email.estimatedTime": "🕐 Εκτιμώμενος Χρόνος Προετοιμασίας:",
      "email.estimatedTimeValue": "15-25 λεπτά",
      "email.deliveryLocationLabel": "📍 Τοποθεσία Παράδοσης:",
      "email.thankYouFooter": "Σας ευχαριστούμε που επιλέξατε το La Strada Restaurant!",
      "email.contactMessage": "Εάν έχετε ερωτήσεις σχετικά με την παραγγελία σας, επικοινωνήστε με τη ρεσεψιόν μας."
    },
    bg: {
      "email.newOrderReceived": "🍽️ Получена е Нова Поръчка",
      "email.orderManagementSystem": "La Strada Restaurant - Система за Управление на Поръчки",
      "email.orderDetails": "Детайли на Поръчката",
      "email.orderNumber": "Номер на Поръчката",
      "email.orderTime": "Час на Поръчката",
      "email.location": "Местоположение",
      "email.customerEmail": "Имейл на Клиента",
      "email.orderItems": "Продукти от Поръчката",
      "email.qty": "Бр.",
      "email.item": "Продукт",
      "email.price": "Цена",
      "email.note": "Бележка",
      "email.total": "Общо",
      "email.actionRequired": "📋 Необходимо Действие:",
      "email.prepareOrderMessage": "Моля, пригответе тази поръчка и се уверете, че се доставя до {location}.",
      "email.autoGeneratedMessage": "Този имейл е генериран автоматично от системата за поръчки на La Strada Restaurant.",
      "email.orderConfirmation": "✅ Потвърждение на Поръчката",
      "email.thankYouMessage": "Благодарим ви за поръчката!",
      "email.yourOrderDetails": "Детайли на Вашата Поръчка",
      "email.deliveryLocation": "Адрес за Доставка",
      "email.orderSummary": "Резюме на Поръчката",
      "email.estimatedTime": "🕐 Приблизително Време за Приготвяне:",
      "email.estimatedTimeValue": "15-25 минути",
      "email.deliveryLocationLabel": "📍 Адрес за Доставка:",
      "email.thankYouFooter": "Благодарим ви, че избрахте La Strada Restaurant!",
      "email.contactMessage": "Ако имате въпроси относно поръчката си, моля свържете се с нашата рецепция."
    }
  };
};

// Export translations
module.exports = {
  getTranslations: extractTranslationsFromContext,
  t: (key, language, translations) => {
    return translations[language]?.[key] || key;
  }
}; 